### ISSUE TITLE
Adapter startet nicht.

### ISSUE THREAD

**Issue by funboxbolzer** [iobroker-community-adapters/ioBroker.tr-064#100]
Hallo,
ich habe den Adapter neu installiert. 
v 3.2.0
Vorher mein Raspberry Pi 4 neu aufgesetzt und Biobroker neu installiert. 
js. 2.28 
node 10.18.1.

im Screenshot ist der Log Auszug zu sehen.
<img width="1355" alt="Bildschirmfoto 2020-02-08 um 18 14 30" src="https://user-images.githubusercontent.com/49862965/74089214-3fde2500-4a9f-11ea-88af-0309dab2cba5.png">

ist der Fehler schon bekannt? gibt es einen Workaround?

Danke Gruß Klaus

**Comment by Kampfratte** [comment]
Hatte die 3.2.0 heute auch installiert und das selbe Problem. Bin wieder zurück auf die vorige.

**Comment by funboxbolzer** [comment]
Ich habe die 3.1.4 von npm installiert. Habe noch etwas gelesen und da stand im forum das die latest von git broken ist. 
3.1.4 läuft bei mir auch

**Comment by Apollon77** [comment]
Naja ... die 3.2.0 existiert nur auf GitHub. Das ist die Development Version und hat außer der Entwickler sagt es nie eine stabilitätszusage. 

Bitte version aus dem latest nehmen und nicht immer ungebeten von GitHub installieren ;-)

**Comment by funboxbolzer** [comment]
> Bitte version aus dem latest nehmen und nicht immer ungebeten von GitHub installieren ;-)

Danke 😊. Das war nicht bekannt. Jetzt bin ich wieder schlauer.
