### ISSUE TITLE
secret is not defined

### ISSUE THREAD

**Issue by AlZiBa** [iobroker-community-adapters/ioBroker.tr-064#101]
Adapter does not start since encryption of the password was introduced

I get debug log:
```
info	(1463) Terminated (NO_ERROR): Without reason
info	(1463) terminating
error	at process._tickCallback (internal/process/next_tick.js:68:7)
error	at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
error	at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
error	at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:71697)
error	at objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2491:65)
error	at adapter.getForeignObject (/opt/iobroker/node_modules/iobroker.tr-064/main.js:115:13)
error	at main (/opt/iobroker/node_modules/iobroker.tr-064/main.js:1119:49)
error	(1463) ReferenceError: secret is not defined
error	(1463) uncaught exception: secret is not defined
```

does
`secret = (systemConfig && systemConfig.native && systemConfig.native.secret) || 'Zgfr56gFe87jJOM';`
result in a string?

 - Adapter version: 3.2.0
 - JS-Controller version: 
 - Node version: v10.19.0
 - Operating system: armbian

**Comment by Apollon77** [comment]
Yes, do not use current GitHub version, use npm 3.1.4 in latest. GitHub version is only Development version and relevant if the developer asks for testing. Thank you.

I leave it open so that other can also see it

**Comment by DutchmanNL** [comment]
fixed in updated admin adapter version already :)

**Comment by Apollon77** [comment]
Nope ;-)

**Comment by HabibA007** [comment]
Sorry guys, I've done a fresh installation and after I fixed the community issue I get this error too... I've read in the current code is an develeoper requestet issue included but it should fix 2 days ago, but it isn't?
Very confusing... how I can downgrad to 3.14 easily?

**Comment by Apollon77** [comment]
Simply install the version from Latest repository from npm

**Comment by stefanoklett** [comment]
which  repository you mean? http://download.iobroker.net/sources-dist-latest.json ?
This version dosen't works.

Thanks

**Comment by Apollon77** [comment]
The 3.1.4 is in latest at the moment. Will come to stable soon

**Comment by Lueghi** [comment]
Sorry for the question but I'm not so familiar with this:
can someone explain to me how to downgrade to version 3.1.4?

**Comment by Apollon77** [comment]
Simply choose "Latest" repository in Admin and install version there. Select 3.1.4 at "Adapters" list at the icon most right

**Comment by Lueghi** [comment]
@Apollon77 : Thanks a lot, an it was so easy that I didn't found the way for myself .... :(.
