### ISSUE TITLE
callee value timestamp is not updated if it is the same number but a new call

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.tr-064#103]
tr-064.0.callmonitor.outbound.callee state timestamp will not be updated if the same number will be called a second time.
Maybe it is the same for inbound callee (didn't tested yet).

adapter 3.1.4
js-controller 2.2.9
node-js 10.19.0
npm 6.13.7

**Comment by Apollon77** [comment]
Yes, states are only updated when they get changed in this adapter. If you want to know if something happens please use the json or the timestamp state ... they will change
