### ISSUE TITLE
Neues Feature der Anwesenheitserkennung

### ISSUE THREAD

**Issue by gammler2003** [iobroker-community-adapters/ioBroker.tr-064#107]
Hallo zusammen, 

wäre es möglich, dem Adapter einen neuen Datenpunkt zu spendieren? Was mir unheimlich helfen würde, wäre
-> ein oder mehrere der eingetragenen WLAN-Geräte anwesend (true/false)

Vielen Dank vorab,
gammler2003

**Comment by robotastic-io** [comment]
Hi,

das geht doch bereits? In den Adapter Einstellungen auf Geräte->Geräte suchen klicken und dann die Geräte auswählen. Anschließend erstellt der Adapter unter tr-064.0/devices einen Datenpunkt für jedes Gerät. "active" zeigt dabei ob das Gerät im W-Lan ist oder nicht.

VG
robotastic

**Comment by Scotty-89** [comment]
Hallo zusammen,

ich würde mich hier mal einklinken zum entsprechenden Datenpunkt.
Ist es möglich eine einstell Option in der GUI bereit zustellen in der man die Zeit einstellen kann ab wann ein Gerät "true" oder "false" gemeldet wird ?  aktuell sind es meine ich 8 min. 
ich würde das gern auf meine Bedürfnisse einstellen wollen ...

**Comment by Apollon77** [comment]
Müssen auch aufpassen das wir aus "convenience" Gründen nicht die Funktion des Adapters arg verwischen. Der Adapter stellt die Informationen zur Verfügung o ein gerät anwesend ist oder nicht ... Je mehr man hier jetzt noch konfigurierbar macht umso komplexer und Fehleranfälliger wird das alles. EIgentlich sollte man eher ggf einen anderen Adapter oder kleine Javascripte sehen die dann mehr erlauben

**Comment by Ilovegym66** [comment]
Richtig,  für  Anwesenheit gibt's ja den fb-presence Adapter...

**Comment by Scotty-89** [comment]
Hallo,

Ja ich kann das verstehen danke fur den Hinweis den Adapter kenne ich noch nicht. Muss ich mit mal anschauen ggf ist es genau das was ich suche. Vielen Dank.
