### ISSUE TITLE
Cannot find module 'tr-O64

### ISSUE THREAD

**Issue by elzershark** [iobroker-community-adapters/ioBroker.tr-064#110]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  

npm error.. Cannot find module 'tr-O64
0.. not O

edit..
i think this was a old install... hm...

**Comment by Apollon77** [comment]
Install newest version please 3.1.4 or such.

**Comment by elzershark** [comment]
Hab den "Fehler" gefunden. Hab ja schon älteres iobroker. Damals gabs n bug wo tr-O64 installiert wurde. Man kann innstalieren was man will, der Fehler bleibt, da es quasy nicht gelöscht wird. Erst wenn wirklich alles gelöscht wird aus iobroker, was mit dem Adapter mal zu tun hat/hatte, läuft alles so wie es sein soll. mist... Deswegen gibs so viele "Probleme" mit "einigen"
