### ISSUE TITLE
Externe IP wird bei Fritzbox 6660 nicht mehr ermittelt.

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.tr-064#111]
Bin heute von der Fritzbox 7490 (DSL) auf die 6660 (Kabelmodem) umgezogen.
Seitdem weist der State **tr-064.0.states.externalIP** die IP der Fritzbox selbst und nicht mehr die externe IP-Adresse aus.

Gruß, Ralf

**Comment by maeb3** [comment]
Also bei meiner FB 6490 (ebenfalls Kabelmodem) wird die korrekte externe IP angezeigt. 
Grüße,
 maeb3

**Comment by RK62** [comment]
Oha, ich habe scheinbar einen Unitymedia Anschluss ohne IPv4:
_FRITZ!Box verwendet einen DS-Lite-Tunnel_
Daher sind meine Dienste auch nicht mehr ohne weiteres von aussen erreichbar :-/
Dann kann ich das hier wohl schließen...

Danke, Ralf
