### ISSUE TITLE
Datapoint "tr-064.0.callmonitor.lastCall.type" not updating!

### ISSUE THREAD

**Issue by MikeEcho0815** [iobroker-community-adapters/ioBroker.tr-064#113]
**Describe the bug**  
Datapoint "tr-064.0.callmonitor.lastCall.type" is not updating.

With two missed calls in a row, the second is not recognized as an update.

**To Reproduce**  
1. Create a script to monitor the Datapoint "type" on update.
2. Initiate a "missed call"
3. Initiate a second "missed call"
4. See the Update of the second call isn't showing.

**Expected behavior**  
The Update of the DP triggers the script.

**Versions:**  
 - Adapter version: 4.0.0
 - JS-Controller version: 3.0.13
 - Node version: 10.20.1
 - Operating system: Linux (proxmox VM)

**Link**
https://forum.iobroker.net/topic/32458/avm-tr-064

**Comment by Apollon77** [comment]
Yes states are only updated if changed, to get a real "trigger" that somethings happened use the json state

**Comment by Ilovegym66** [comment]
Ich setz das hier mal drunter, denke, passt vielleicht:
Version 4.0.9 - aktualisiert die Callists nicht mehr, egal ob ausgehende, gesamte, etc. Zurück auf 4.0.8 und schon sind die Lists wieder aktuell. ( haben das im Forum schon angesprochen.. , kann es nachvollziehen, sehe aber auch nicht, warum das Change das bewirken sollte.. )
Egal ob FritzOS 7.12 oder 7.20, tritt auch unter Containern mit Debian Buster, als auch in der VM mit Linux Mint 18.3 auf.
