### ISSUE TITLE
Password error: Please re-enter the password in Admin. Stopping

### ISSUE THREAD

**Issue by rebel1985** [iobroker-community-adapters/ioBroker.tr-064#118]
adapter ist online aber schaltet die objekte nicht oder stellt eine verbindung mit der fritzbox her.
jedes mal beim neustart kommt:
Password error: Please re-enter the password in Admin. Stopping
das passwort vom adapter auf der fritzbox ist schon neu
was sit damit gemeint und warum arbeitet der adapter nicht richtig?

**Comment by Apollon77** [comment]
Admin version? js.controller Version?

Hast Du getan was da steht? In die Konfiguration gegangen und das Passwort neu eingegeben?

**Comment by rebel1985** [comment]
ja hatte ich.
nach einem update heute auf
Titel: JS controller Verfügbar: 3.0.17
admin habe ich 4.0.9
und ändern des passwortes scheint der adapter erst mal wieder zu laufen, ich beobachte es aber noch da in den letzten wochen öfters zicken mit dem tr-064 hatte
