### ISSUE TITLE
(8873) Password error: Please re-enter the password in Admin. Stopping

### ISSUE THREAD

**Issue by EvilEls** [iobroker-community-adapters/ioBroker.tr-064#119]
Adapter v4.0.0 constantly reporting 

tr-064.0 | error | (8873) Password error: Please re-enter the password in Admin. Stopping
tr-064.0 | info | (8873) starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.tr-064, node: v10.20.1, js-controller: 3.0.17

I removed and reset password.
I removed and resinstalled adapter.

Prior versions of the adapter are working fine.

**Comment by JBSullivan** [comment]
Problem immer noch vorhanden auch mit Version 4.0.1

FritzBox User gelöscht und in der FB einen neuen User angelegt. Das hat in der Vergangenheit immer als Workaround funktioniert - bringt jetzt aber auch keinen Erfolg mehr.

Der Fehler tauchte erst auf nach dem Update auf js-controller 3.0.18 (vorher Admin 4.0.9 & js-controller 2.2.9 war alles OK)
`

tr-064.0 | 2020-04-25 08:00:09.695 | error | (8072) Password error: Please re-enter the password in Admin. Stopping
-- | -- | -- | --
tr-064.0 | 2020-04-25 08:00:09.668 | info | (8072) starting. Version 4.0.1 in C:/iobroker/GLT/node_modules/iobroker.tr-064, node: v10.17.0, js-controller: 3.0.18

`

**Comment by xdaamg** [comment]
Version 4.0.1 von tr-064 lief hier ohne Probleme unter js-controller 2.2.10.
Heute ein Update des js-controllers auf 3.0.18, seitdem funktioniert der tr-064 Adapter nicht mehr. Es wurde sonst nichts verändert. Log entspricht dem ein Posting vorher.

**Comment by JBSullivan** [comment]
Ich habe auch den Rollback auf 3.1.4 versucht, was wieder einmal zum totalen System Zusammbruch unter js-controller 3.xx geführt hat. Seit js-controller 3.xx kann man mit viel Glück Adapter installieren, aber bei Downgrades oder Deinstallationen kollabiert das System regelmäßig.

Hier das Fehlerlog zum Downgrade:

`$ ./iobroker upgrade tr-064@3.1.4
Update tr-064 from @4.0.1 to @3.1.4
NPM version: 6.11.3
npm install iobroker.tr-064@3.1.4 --loglevel error (System call)
ERROR: internal/modul
ERROR: es/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Upload.uploadAdapter (C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:5
ERROR: 33:24)
    at installNpm (C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\setup\setupUpgrade.js:183:28)
    at installNpm (C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\setup.js:2267:9)
    at finishUpgrade (C:\iobroker\GLT\node_modules\iobroker.js-c
ERROR: ontroller\lib\setup\setupUpgrade.js:163:13)
    at install.downloadPacket (C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\setup\setupUpgrade.js:264:21)
    at that.npmInstallWithCheck (C:\iobroker\GLT\node_modules\iobroker.js-con
ERROR: troller\lib\setup\setupInstall.js:220:55)
ERROR: process exited with code 1`

**Comment by Koalabaer** [comment]
Same here... nach Update js-controller auf 3..... ist das Problem anaylisiert und wird an einer Lösung gearbeitet oder werden noch Infos benötigt?

**Comment by Apollon77** [comment]
Wenn js Controller 3 dann bitte ein „iobroker upload tr-064“. Tut es dann? Controller Version 3.0.19 heute Abend sollte das dann auch ohne upload fixen.

**Comment by Apollon77** [comment]
@JBSullivsn der Fehler hat hier nichts verloren und auch nichts mit dem Controller update zu tun! Bitte wenn im Forum melden wegen Diskussion und Lösung.

**Comment by Koalabaer** [comment]
@Apollon77 sorry ich meinte js-controller v 3.0.18. 
Und sorry, was meinst du mit iobroker upload tr-064?

**Comment by Apollon77** [comment]
Ich meine das Kommando "iobroker upload tr-064" ausführen oder den Upload Button im Admin unter Adapter drücken ... oder auf controller 3.0.19 warten

**Comment by Koalabaer** [comment]
Mit dem Update auf 3.0.19 läuft es wieder - Danke!

**Comment by EvilEls** [comment]
First updated to js-controller 3.0.19, rebooted, then update to 4.0.1
After just re-entering and saving the password, I got wrong credentials error.
I had to blank the password field, save settings and re-enter password again. After saving, I could start the adapter successfully. 

`(4800) starting. Version 4.0.1 in /opt/iobroker/node_modules/iobroker.tr-064, node: v10.20.1, js-controller: 3.0.19`

✔Issue solved

thank you guys!
