### ISSUE TITLE
2 von 4 Instanzen starten nicht

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.tr-064#122]
Ich habe das Problem, daß 2 von 4 Instanzen nicht starten. Die Zugangsdaten sind 100%ig richtig, trotzdem startet die Instanz nicht. 

![Bildschirmfoto 2020-05-02 um 12 47 12](https://user-images.githubusercontent.com/8560588/80862197-4c73b300-8c73-11ea-82ff-f7a1b654e0e7.png)

Im Log erscheint trotz "DEBUG"-Level ncihts.

![Bildschirmfoto 2020-05-02 um 12 50 15](https://user-images.githubusercontent.com/8560588/80862238-ab392c80-8c73-11ea-8703-c31428d932a3.png)

Die Instanzen sind auf einem Multihost System auf dem SLAVE installiert.

**Comment by Apollon77** [comment]
Passwort wirklich neu eingegeben? Was steht im log des slaves auf der Platte?

**Comment by Ilovegym66** [comment]
An der Anzahl der Instanzen kanns nicht liegen, bei mir laufen meist 9-10 Instanzen des TR-064 einwandfrei ohne zicken und murren.. :-) 
Node 12 - js-controller 3.0.20
Wie hast du die Fritzboxen/Repeater beim Kennwort konfiguriert, wenn du einen Repeater einbinden willst, musst der a) im Mesh sein und b) das Kennwort dort "abgeschaltet" werden, wobei er dann Username+Kennwort des Mesh-Masters haben will, und genau das funktioniert mit dem TR-064-Adapter :-)

**Comment by LJSven** [comment]
Also jetzt sind alle Instanzen grün - gemacht habe ich nichts. 

@Apollon77 Im Log vom Slave steht nichts, auch nicht, wenn ich auf Debug oder Silly stelle. Hatte die 3.x.x auch schon installiert -  wo die Meldung mit dem PW kam. Danach ging es schonmal. Heute trat das Problem wieder auf. Komisch ist / war, daß es immer die gleichen Instanzen waren.

@Ilovegym66 Instanz 1-3 sind Repeater / alle im Mesh. Das sind die Einstellungen ->

![Bildschirmfoto 2020-05-02 um 20 18 25](https://user-images.githubusercontent.com/8560588/80872420-23264780-8cb2-11ea-80d9-da3271f55de3.png)
![Bildschirmfoto 2020-05-02 um 20 20 40](https://user-images.githubusercontent.com/8560588/80872467-6c769700-8cb2-11ea-9077-ce4850a95e51.png)

Also in meinen Augen alles richtig.

**Comment by Apollon77** [comment]
Hm ... naja wenns wieder tut ...
