### ISSUE TITLE
caller (inbound) not shown if the same caller as previous

### ISSUE THREAD

**Issue by huk13** [iobroker-community-adapters/ioBroker.tr-064#125]
If the same caller and callerName calls a second (or more often) time consecutively the appropriate inbound caller and callerName states remain empty. 

js controller 3.x, node 12.16.2 on raspi 4, fritzbox 7490, os 07.12

**Comment by Apollon77** [comment]
Hm ... really? Whey the state is empoty? The adapter DO NOT empty the state. Could it be that you have some script running that emoties these states? 

The adapter logic is jkust not updating values that are unchanged from his point of view ... so

**Comment by huk13** [comment]
You are right, the states are empty after the first call is ended. They are not filled during the consecutive call from the same number. In the call list of the Fritzbox the name and number show up. 

I have stopped the skript and look only at the object states. The caller and callerName remain empty. The json state and timestamp are updated. This is easy to verify if you have the adapter running in connection to a Fritzbox.

**Comment by Apollon77** [comment]
to test that you need to restart the adapter and then it will write anew (or if a different claler calls)
