### ISSUE TITLE
.outbound wird nicht aktualisiert, wenn Telefonbucheintrag korrigiert wird

### ISSUE THREAD

**Issue by myssv** [iobroker-community-adapters/ioBroker.tr-064#127]
Mir ist heute ein kleiner Fehler aufgefallen.

Ich habe im Telefonbuch einen Rechtschreibfehler korrigiert. Dieser Eintrag ist bereits unter ".inbound" und unter ".outbound" gelistet.

In den Datenpunkten ".inbound" werden die Daten danach aktualisiert und neu aus dem Adressbuch geladen.

Bei".outbound" passiert das nicht. Dort bleibt der Name falsch geschrieben.

**Comment by myssv** [comment]
Ich muss es scheinbar mit der Box selber verwechselt haben. Heute noch mal getestet und es wird nirgendwo aktualisiert. In der Box dagegen schon.

Evtl. kein Fehler aber ein kommendes Feature?

**Comment by Apollon77** [comment]
Was ist die Box? Soweit ich weiß wird die History immer nur ergänzt. Alte Werte bleiben also wie sie sind.

**Comment by myssv** [comment]
Sorry, Ich meine die Fritz!Box. In meinem Fall eine 7580

Dort gibt es auf der Startseite den Bereich "Abrufe heute"

Und dort werden die Namen definitiv aktualisiert, wenn ich sie im 
Telefonbuch der Fritz!Box anpasse.


und tschüss

myssv

Am 21.05.2020 um 18:10 schrieb Ingo Fischer:
