### ISSUE TITLE
command with with Fritz!BOX

### ISSUE THREAD

**Issue by stefanoklett** [iobroker-community-adapters/ioBroker.tr-064#135]
I tried out to set a custom command, but the comandResult is anytime {}.
I tried to set command "dumpServices", but the answer is {}.
I'm definitely doing something wrong, but with so little documentation and examples it's hard to understand how to use.
I'm using the TR-064 interface to enable WLAN and more, no problem.
But I'd like to be able to add or remove a route.
I'd be grateful if you could give me some insight.

regards

**Comment by Apollon77** [comment]
Please show how you tried it. Please show your script.

**Comment by Feuer-sturm** [comment]
Hello @Herazzer ,

I am just doing my first steps as well with the tr-064 commands. You will find detailed informations to the commands here https://avm.de/service/schnittstellen/?spm=a2c6h.14275010.0.0.202628cfwq7844 and e.g. for TAM here https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_tam.pdf

For "SetEnable" your params are not correct. 
To switch it on: 
`{"service": "urn:dslforum-org:service:X_AVM-DE_TAM:1","action": "SetEnable", "params": {"NewIndex": "0","NewEnable": "1"}}`

To switch it off: 
`{"service": "urn:dslforum-org:service:X_AVM-DE_TAM:1","action": "SetEnable", "params": {"NewIndex": "0","NewEnable": "0"}}`

I just tested it and for me I could use the commands to switch it on and off

**Comment by Apollon77** [comment]
@Feuer-sturm Would you be so kind and add a PR for the Readme to add such an example? Else I would take over your example from here

**Comment by Feuer-sturm** [comment]
@Apollon77 I will try it (it will be my first pull request :-) )

**Comment by Apollon77** [comment]
Not problematic. just select the file klick the pencil button and change what you want and then scroll sown ad "propose change"

**Comment by Feuer-sturm** [comment]
@Apollon77 I added the example to the readme.
