### ISSUE TITLE
Compatbility Fritz Os 7.20

### ISSUE THREAD

**Issue by cburghardt** [iobroker-community-adapters/ioBroker.tr-064#138]
I have noticed that since upgrading the Fritz box to 7.20 the tr-064 adapter (latest and greatest) marks devices as offline every few minutes. It even jumps from online to offline and back to online with the poll interval (10 secs).
This issue did not occur with the previous version of Fritz OS.

**Comment by Apollon77** [comment]
Then this should be reported to AVM to be fixed, or ?! ;-(

**Comment by vepman** [comment]
> 
> 
> I have noticed that since upgrading the Fritz box to 7.20 the tr-064 adapter (latest and greatest) marks devices as offline every few minutes. It even jumps from online to offline and back to online with the poll interval (10 secs).
> This issue did not occur with the previous version of Fritz OS.

No, it occurs on 7.12 on my Cable 6490 too.
Every few minutes it jumps from online to offline and back.
It seems to be that way since version 4.0.9

**Comment by Ilovegym66** [comment]
I've tested some devices are connected with cable to the router, and the history say a stable 100% connection. 
FritzOs 7.20 at 7590 ( 2 Router, 5 connected devices ).

Can it be, that you have wifi devices ?

**Comment by vepman** [comment]
> Can it be, that you have wifi devices ?

yes, but before that it worked.
With radar2 it works even when the phone display is off, also with tr-064 before.

**Comment by cburghardt** [comment]
I just reverted back to version 4.0.8 and it really looks like @vepman is right and I don't see the problem anymore. I will monitor the behavior.

**Comment by Apollon77** [comment]
interesting  ... the only change was:
https://github.com/iobroker-community-adapters/ioBroker.tr-064/commit/498e2d51ee660e2192ca6575e0fe5616f0f25369

**Comment by Apollon77** [comment]
Könntet Ihr ggf mal diese änderungen nacheinander testen an welches liegt? Es gab vorhr einen Crash case der reportet wurde der damit an sich abgefangen werden sollte

**Comment by Apollon77** [comment]
Anyone?

**Comment by Ilovegym66** [comment]
Bei mir geht's auch nicht mehr.. Muss mal testen und Debugger anwerfen...

**Comment by Apollon77** [comment]
am besten bitte mel die beiden genannten Änderungen rückgäng machen unr mir sagen welche schuld ist. denke brauchst keinen Debugger, aber der test wäre super. hab leider kein 7.20

**Comment by Ilovegym66** [comment]
Also ich hab weder mit FritzOs 7.12 noch mit 7.20 Verbindungsabbrüche ( 100% line up for hours ).  Weder mit Version 4.0.8 noch mit 4.0.9 vom iobroker-tr-064-Adapter Probleme damit.
Könnte es sein, dass hier jemand bei FritzOs 7.20 das WPA3 eingeschaltet hat, und es sich um Wlan Geräte handelt? Mit über 300 Devices im Netz und 4 FritzBoxen nicht nachvollziehbar.

**Comment by gaudes** [comment]
Hi,
also ich habe nun das gleiche Problem.
Meine FritzBox 7490 war defekt. Habe nun eine 7590 mit 7.20. Sonstige Umgebung war identisch (iOS-Geräte+Version,Adapter).

Konfig ist sonst identisch (auch kein WPA3 aktiv). Ich habe die Konfig allerdings nicht aus der 7490 wiederhergestellt, sondern dachte mir es wird mal Zeit für eine neue Konfig, da ich die alte glaub schon > 10 Jahre mitziehe.

Bei mir siehts im Moment also nach 7.20 aus. Möchte das vielleicht jemand mal mit einem Update auf 7.20 nachvollziehen ?

VG Ralf

**Comment by Apollon77** [comment]
Can you please try version 4.0.8 of the adapter? Is it solved there? Else I can just repeat my questions above ... I do not have any device which is capable to get 7.20

**Comment by gaudes** [comment]
@Apollon77 Sorry, it was another problem. My Mesh configuration with an additional repeater was incorrect. After fixing this, it works again without problems with version 4.0.9.
Thanks and regards, Ralf

**Comment by Apollon77** [comment]
Ok, @gaudes @vepman @cburghardt is there now an issue or not?

**Comment by cburghardt** [comment]
I can't reproduce this anymore since I upgraded to the latest version of the adapter
