### ISSUE TITLE
Warning: ForEachConfiguredDevice: in GetSpecificHostEntry 2

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.tr-064#140]
**Describe the bug**  
Ich bekomme in regelmässigen Abständen ein Warning im Log ->
ForEachConfiguredDevice: in GetSpecificHostEntry 2(Dianas-iPhone....

**To Reproduce**  
Keine Idee, wann und warum die Meldung auftaucht

**Versions:**  
 - Adapter version: 4.0.9
 - JS-Controller version: 3.1.6
 - Node version: v12.18.2
 - Operating system: Debian Stretch with Armbian Linux 4.19.69-rockchi

**Comment by Apollon77** [comment]
Es wurde bereits einmal analysiert. Das tritt scheinbar auf wenn das DHCP Lease eines Geräten ausläuft. Kann das sein?

**Comment by LJSven** [comment]
Das wäre aber ziemlich oft - oder verstehe ich es falsch? Lt. FritzBox steht der Wert auf 10 Tage - im Log kommt die Meldung alle paar Stunden ->

![Bildschirmfoto 2020-07-21 um 09 24 45](https://user-images.githubusercontent.com/8560588/88025273-54d1e080-cb34-11ea-82d3-d60d629566fd.png)
![Bildschirmfoto 2020-07-21 um 09 25 36](https://user-images.githubusercontent.com/8560588/88025285-58fdfe00-cb34-11ea-8a30-5b7b46d7216a.png)

**Comment by Apollon77** [comment]
Dann weiss ich auch nicht warum, passiert bei mir nicht (haben auch mehrere iphones und ipads)
