### ISSUE TITLE
Der Adapter lässt sich nicht mehr starten - nach uninstall

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.tr-064#142]
Bei mir wurde die "CALLLISTS" nicht aktualisiert - da habe ich den Adapter komplett gelöscht inkl. tr-064 Verzeichnis unter node_modules. Anschließend wollte ich den Adapter neu installieren. Auf dem Master kommt im LOG folgende Meldung:
`2020-07-28 12:45:12.721  - info: host.tinkerboardmaster instance system.adapter.tr-064.0 started with pid 19668
--
2020-07-28 12:45:13.478  - info: host.tinkerboardmaster instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
2020-07-28 12:45:16.368  - error:  tr-064.0 (19668) Error: getaddrinfo ENOTFOUND fritz.box -  {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"fritz.box"}
2020-07-28 12:45:16.370  - error: tr-064.0 (19668) ~
2020-07-28 12:45:16.371  - error: tr-064.0 (19668) ~~ Fatal error. Can not connect to your FritzBox.
2020-07-28 12:45:16.371  - error: tr-064.0 (19668) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
2020-07-28 12:45:16.372  - error: tr-064.0 (19668) ~
2020-07-28 12:45:16.373  - warn: tr-064.0 (19668) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
2020-07-28 12:45:16.905  - error: host.tinkerboardmaster instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2020-07-28 12:45:16.906  - info: host.tinkerboardmaster Restart adapter system.adapter.tr-064.0 because enabled
2020-07-28 12:45:46.990  - info: host.tinkerboardmaster instance system.adapter.tr-064.0 started with pid 20920
2020-07-28 12:45:49.594  - error:  tr-064.0 (20920) Error: getaddrinfo ENOTFOUND fritz.box -  {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"fritz.box"}
2020-07-28 12:45:49.596  - error: tr-064.0 (20920) ~
2020-07-28 12:45:49.597  - error: tr-064.0 (20920) ~~ Fatal error. Can not connect to your FritzBox.
2020-07-28 12:45:49.597  - error: tr-064.0 (20920) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
2020-07-28 12:45:49.598  - error: tr-064.0 (20920) ~
2020-07-28 12:45:49.599  - warn: tr-064.0 (20920) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
2020-07-28 12:45:50.177  - error: host.tinkerboardmaster instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
`

Auf dem Slave kommt folgende Meldung im Log ->

`

host.raspberrypi | 2020-07-28 12:52:28.136 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
tr-064.0 | 2020-07-28 12:52:27.190 | warn | (1410) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2020-07-28 12:52:27.186 | error | (1410) ~
tr-064.0 | 2020-07-28 12:52:27.185 | error | (1410) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2020-07-28 12:52:27.184 | error | (1410) ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2020-07-28 12:52:27.183 | error | (1410) ~
tr-064.0 | 2020-07-28 12:52:27.178 | error | (1410) Error: Device responded with fault Error: Credentials incorrect - {}
host.raspberrypi | 2020-07-28 12:52:19.620 | info | instance system.adapter.tr-064.0 started with pid 1410
host.raspberrypi | 2020-07-28 12:51:49.596 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.raspberrypi | 2020-07-28 12:51:49.596 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-07-28 12:51:49.595 | error | Caught by controller[0]: }
host.raspberrypi | 2020-07-28 12:51:49.594 | error | Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.tr-064/main.js' ]
host.raspberrypi | 2020-07-28 12:51:49.594 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-07-28 12:51:49.593 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
host.raspberrypi | 2020-07-28 12:51:49.593 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
host.raspberrypi | 2020-07-28 12:51:49.592 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:985:32)
host.raspberrypi | 2020-07-28 12:51:49.592 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
host.raspberrypi | 2020-07-28 12:51:49.591 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
host.raspberrypi | 2020-07-28 12:51:49.591 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/main.js:14:21)
host.raspberrypi | 2020-07-28 12:51:49.590 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi | 2020-07-28 12:51:49.590 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
host.raspberrypi | 2020-07-28 12:51:49.589 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
host.raspberrypi | 2020-07-28 12:51:49.581 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
host.raspberrypi | 2020-07-28 12:51:49.580 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.tr-064/main.js
host.raspberrypi | 2020-07-28 12:51:49.580 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-07-28 12:51:49.579 | error | Caught by controller[0]: Error: Cannot find module 'tr-O64'
host.raspberrypi | 2020-07-28 12:51:49.579 | error | Caught by controller[0]:   ^
host.raspberrypi | 2020-07-28 12:51:49.578 | error | Caught by controller[0]:   throw err;
host.raspberrypi | 2020-07-28 12:51:49.576 | error | Caught by controller[0]: internal/modules/cjs/loader.js:968
host.raspberrypi | 2020-07-28 12:51:48.142 | info | instance system.adapter.tr-064.0 started with pid 1343
host.raspberrypi | 2020-07-28 12:51:18.113 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.raspberrypi | 2020-07-28 12:51:18.112 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-07-28 12:51:18.111 | error | Caught by controller[0]: }
host.raspberrypi | 2020-07-28 12:51:18.111 | error | Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.tr-064/main.js' ]
host.raspberrypi | 2020-07-28 12:51:18.110 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-07-28 12:51:18.110 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
host.raspberrypi | 2020-07-28 12:51:18.109 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
host.raspberrypi | 2020-07-28 12:51:18.109 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:985:32)
host.raspberrypi | 2020-07-28 12:51:18.108 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
host.raspberrypi | 2020-07-28 12:51:18.107 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)
host.raspberrypi | 2020-07-28 12:51:18.107 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/main.js:14:21)
host.raspberrypi | 2020-07-28 12:51:18.106 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi | 2020-07-28 12:51:18.106 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1025:19)
host.raspberrypi | 2020-07-28 12:51:18.105 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
host.raspberrypi | 2020-07-28 12:51:18.105 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
host.raspberrypi | 2020-07-28 12:51:18.104 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.tr-064/main.js
host.raspberrypi | 2020-07-28 12:51:18.103 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-07-28 12:51:18.103 | error | Caught by controller[0]: Error: Cannot find module 'tr-O64'
host.raspberrypi | 2020-07-28 12:51:18.102 | error | Caught by controller[0]:   ^
host.raspberrypi | 2020-07-28 12:51:18.101 | error | Caught by controller[0]:   throw err;
host.raspberrypi | 2020-07-28 12:51:18.100 | error | Caught by controller[0]: internal/modules/cjs/loader.js:968
`

Die Zugangsdaten sind nach meinem empfinden korrekt - zumindest kann ich mich so auf der FritzBox einloggen.

Mein System ist ein Master & Slave - überall die neusten Versionen. 

**Versions:**  
 - Adapter version: 4.0.11
 - JS-Controller version: 3.1.6
 - Node version: 12.8.3
 - Operating system: linux

**Comment by Ilovegym66** [comment]
Hi, der Adapter findet die Fritzbox nicht, ist die IP richtig eingetragen im Adapter? Normal einfach "192.168.178.1" oder welche du da konfiguriert hast...

**Comment by LJSven** [comment]
Ist definitiv korrekt. Hatte es auch schon mit fritz.box versucht.

![image](https://user-images.githubusercontent.com/8560588/88659248-0ba20380-d0d5-11ea-9695-a0b6aa659d3c.png)

**Comment by Ilovegym66** [comment]
zeig bitte n screenshot von der Config des Adapters, vielleicht noch irgendwas davor? http oder sowas?

**Comment by LJSven** [comment]
![Bildschirmfoto 2020-07-28 um 14 51 05](https://user-images.githubusercontent.com/8560588/88667812-2169f580-d0e2-11ea-8f83-fc004feadf38.png)

**Comment by Ilovegym66** [comment]
hmm sieht gut aus, evt. ein Leerzeichen drin ? kommst du vom iobroker-system aus auf die fritzbox?

**Comment by LJSven** [comment]
Wie kann ich das testen?

**Comment by LJSven** [comment]
Das Problem ist gelöst - als ich vor 7 Wochen meine FB neu gemacht habe, habe ich bei "Anmeldung bei Zugriff aus dem Heimnetz", "Anmeldung mit dem FRITZ!Box-Kennwort" angehakt. Es muss aber "Anmeldung mit FRITZ!Box-Benutzernamen und Kennwort" sein - jetzt geht es. Komisch allerdings, daß es trotzdem "teilweise" die letzten Wochen funktioniert hat.
![Bildschirmfoto 2020-07-28 um 21 10 34](https://user-images.githubusercontent.com/8560588/88710926-a3284600-d117-11ea-80d4-dab197c26162.png)
