### ISSUE TITLE
Status Geräteliste wird nicht aktualisiert

### ISSUE THREAD

**Issue by Hans-Zwiesel** [iobroker-community-adapters/ioBroker.tr-064#160]
Geräte in der Geräteliste werden mit tr-064.0.devices.Galaxy-J5.active = true angegeben, obwohl
die schon seit Stunden nicht mehr im FritzBox/Netzwerk zu sehen sind.
Es betrifft zwei Geräte von 4 Einträgen.
Irgendwann stimmt dann der Eintrag wieder, Auslöser unbekannt.

**Versions:**  
 - Adapter version: 4.0.9
 - JS-Controller version: 3.1.6
 - Node version: v10.19.0
- FritzBox 7590 V 7.20

**Comment by Apollon77** [comment]
Irgendetwas im ioBroker Log wenn es nicht tut? Mehr Infos?

**Comment by Hans-Zwiesel** [comment]
Nur für das eine Gerät (Galaxy-J5) eine Warnung, sonst nichts auffälliges:
2020-09-12 02:43:02.048 - warn: tr-064.0 (1046) forEachConfiguredDevice: in GetSpecificHostEntry 3(Galaxy-J5/94:7B:E7:51:1E:37):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}

Die beiden Geräte sind in der FB als Gast angemeldet,
zwei weitere Geräte, (normal, kein Gast) werden richtig angezeigt.

**Comment by Siggi0904** [comment]
Hallo,

ich bekomme die gleiche Meldung, wenn das Handy das WLAN verlässt.
Bei Rückkehr ist wieder alles super.
Aufgrund des Fehlers bzw. dieser Warnung wird das entsprechende Blockly Script nicht getriggert.

`2020-09-14 13:00:02.069 - warn: tr-064.0 (9302) forEachConfiguredDevice: in GetSpecificHostEntry 1(Mario-Handy/C0:EE:xx:D8:xx:62):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}`

**Comment by Apollon77** [comment]
Hilft es wenn du "dieses Gert immer gleiche IP geben" einstellst?

**Comment by Hans-Zwiesel** [comment]
Das ist im Gast-Netz nicht möglich.

**Comment by Apollon77** [comment]
Hm ... gastnetz ... Interessante Info ;-)

Vllt hat es damit zu tun?

Am Ende meldet die fritzbox den Fehler bei der Abfrage des Gerätes. Ich kenne den Fehler sonst nur wenn das DHCP lease ausgelaufen ist und daher das Gerät unbekannt ist. Vllt passiert  das im Gastnetz schneller/anders.

**Comment by Hans-Zwiesel** [comment]
Im Anhang ein Programm (Arduino IDE) für ESP8266.
Dieses Programm zeigt mir über TR-064 den Status (unabhängig vom ioBroker) für die Wlan Geräte an.

Das interessante dabei:
Seit dieses Programm in einem ESP8266 läuft, werden auch im ioBroker die Zustände richtig angezeigt!!

Jetzt gerade habe ich den ESP8266 ausgeschaltet und der Zustand im ioBroker wurde immer noch aktualisiert??

Ich muß jetzt erst einmal herausfinden, ob und wie lange das anhält, aber ein Ansatz dürfte das immerhin sein, auch
die "sendSOAPActionRequest Error" im Log.


[home-indicator.zip](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/5222646/home-indicator.zip)

**Comment by Siggi0904** [comment]
Also bei mir kommt der Fehler nicht, wenn ich die Geräte des TR64 unter Objekte nicht umbenenne.
Die Geräte aus dem TR64 kann ich im Adapter zwar umbenennen, das kommt aber in den Objekten nicht an.
Dann scheint es auch so, das mehr oder wenig gut, die Geräte erkannt werden.

Da die Fritzboxen Geräte nicht zuverlässig schnell erkennen, bin ich von der Lösung wohl wieder weg.
Gestern sah der ping Adapter als Alternative gut aus.
Heute morgen waren aber im Ping Adapter mein Handy meine Alexas und andere Geräte als Abwesend gekennzeichnet obwohl ich diese über das Terminal sauber anpingen konnte.

Die Anfrufkontrolle des TR64 habe ich mir noch nicht angesehen, ich hoffe das die wenigstens richtig funktioniert.

Da ich auf die Anwesenheit zeitnah eine Alarmanlage einrichten will, muss das zuverlässig klappen.
Ich werde wohl auf eine Taster-Lösung zur Anwesenheit wechseln.
Weiß da aber noch keine gescheite Umsetzung.

**Comment by Ilovegym66** [comment]
Hi, für die Anwesenheit ist der fb-checkpresence-Adapter zu empfehlen, der funktioniert einwandfrei und hat auch noch ein paar mehr Features. Ist problemlos zusätzlich zum TR-064 Adapter zu installieren.

**Comment by Hans-Zwiesel** [comment]
@Ilovegym66 
Vielen Dank für den Hinweis, mir wäre es aber lieber, wenn das der TR-064 Adapter mit erledigen könnte und nicht jede
Funktion einen eigenen Adapter braucht.
Ausserden sollten doch irgendwann die Bugs aus den verfügbaren Adaptern entfernt werden.

**Comment by Siggi0904** [comment]
@Ilovegym66 
Wenn die Erkennung seitens der Fritzbox schon nicht richtig funktioniert, dann funktioniert es auch mit einem anderen Adapter auf gleicher Protokollbasis schon nicht. Aber den Adapter kenn ich. Ich wäre ehr bei dem Skript [Github](https://github.com/Mic-M/iobroker-presence-script-for-tr-064-community-adapter/blob/master/presence-script-for-tr-064-community-adapter.js) dann gelandet.

@Hans-Zwiesel 
Gibt es gegen den o.g. Bug schon eine Idee oder Lösung?
Ich habe den Fehler sehr oft anstehen,wenn ich das Haus mit dem Handy verlasse.

Z.B. Wieder heute:
`

tr-064.0 | 2020-09-22 08:52:04.600 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
-- | -- | -- | --
tr-064.0 | 2020-09-22 08:51:52.771 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:51:40.938 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:51:28.897 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:51:17.070 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:51:04.840 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:50:52.406 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5
tr-064.0 | 2020-09-22 08:50:38.258 | warn | (10959) forEachConfiguredDevice: in GetSpecificHostEntry  15(Android-3/C0:EE:FB:D8:99:62):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 5`

Großen Dank.

**Comment by Hans-Zwiesel** [comment]
@Siggi0904 
Es geht nur, den TR-064 Adapter in der Log-Stufe auf "Error" zu stellen, dann erfolgt wenigstens kein Eintrag mehr im Log.
Die finden den  Fehler nicht.

**Comment by Siggi0904** [comment]
Hi,
Stufe Error geht ja aich nicht, da die Variable nicht aktualisiert wird und dann das Anwesenheitsscript nicht getriggert wird.
Aber erstmal gut zu hören, dass ich nicht allein mit Fehlern da stehe.

Was gibt es denn alternativ zur "Eier legenden Wollmilchsau" ?

**Comment by Hans-Zwiesel** [comment]
Seit 7 Tagen werden bei mir die Zustände richtig angezeigt und weiß immer noch nicht warum.
Ich wollte damals unabhängig vom ioBroker die Zustände aus der FritzBox auslesen um zu sehen, ob der Fehler von der 
FritzBox kommt.
Näheres habe ich vor 7 Tagen unter "Im Anhang ein Programm (Arduino IDE) für ESP8266." beschrieben.

Also mit dem  ioBroker ist für mich ein Traum in Erfüllung gegangen. Das ist genau das was ich schon immer wollte. Incl. MQTT, mySQL und einen Host, der nur ein paar Watt benötigt.
Ich hatte vor zwei Jahren sogar schon angefangen, selbst so etwas ähnliches zu programmieren. (Vorige Woche habe ich die Skizzen dazu weggeschmissen :-)
Hoffentlich wird das mit den Fehlern einmal besser und die Entwickler machen sich daran, bevor sie neue Features "zaubern",
was sicher erfreulicher ist, als Fehler aufzuspüren. Ich kann das irgenwie verstehen, wenn es auch nicht erfreulich ist.

**Comment by Apollon77** [comment]
>  Hoffentlich wird das mit den Fehlern einmal besser und die Entwickler machen sich daran, bevor sie neue Features "zaubern"

Naja option 1 ist Fehler nicht als Fehler loggen - hilft das? Kurzfristig vielleicht ... sobald mal ein echter Fehler kommt wundern sich alle das es nicht tut und nix loggt. Also wat nu? ;-) ... Was sollen wir denn tun wenn die Fritzbox einen Error 500 auf eine Anfrage zurückliefert? Scheinbar werden in Gast-Netzwerken (sowas war auch mal das Thema das es primär da auftritt) die Devices schneller komplett rausgeworfen und wenn es dann weg ist ist es dann weg. Versuch mal im normalen WLAN.

Am Ende ist das immer einfach auf die Entwickler zu schieben das "die Typen die Fehler nicht in den Griff bekommen". Wenn aber ein Entwickler das nicht nachstellen und reproduzieren kann ... ja was soll er tun? Wenn die Community, also die User die das Problem haben sich nicht hinsetzen und alles durchprobieren und diese Infos für die Devs "kondensieren" - je ausführlicher umso besser.

**Comment by Hans-Zwiesel** [comment]
"_die User die das Problem haben sich nicht hinsetzen und alles durchprobieren_"
Ich habe vollstes Verständnis dafür, dass man nichts reparieren kann, was man nicht kennt, ist bei den Autos das selbe Problem.
Aber Vermutungen und Versuche sind ja auch nicht verboten.

Vielleicht ein Tipp aus meiner früheren Tätigkeit:
Baut doch eine "Debug"-Version für die User, die da mitmachen und fügt da einen Code ein, der das in einer Datei mitprotokolliert, was ihr wissen wollt und die so versendet werden kann.
Oder eine zweite Log-Datei, speziell für Debugging. Die "normale" Log-Datei sollte dem normalen Ablauf vorbehalten bleiben.
Die Fehler kommen manchmal so selten, dass man mit dem normalen Log nicht weiterkommt.
Dann müssen wir den schwarzen Peter nicht immer hin- und herschieben.
Jeder Betroffene wird auch nichts dagegen haben, wenn ihr einmal mit dem TeamViewer auf unseren PC schauen wollt, wenn
ihr so nicht weiterkommt.

**TR-064**
Bei mir kommt der Error 500 jetzt nicht mehr, seit die Anwesenheit richtig angezeigt wird.
Ich habe nichts verändert, was mit der FritzBox zu tun hat, lediglich das, was ich in meinem Beitrag
vor 8 Tagen unter "Im Anhang ein Programm (Arduino IDE) für ESP8266." beschrieben habe.
Zusätzlich lasse ich den JS und MQTT Adapter zweimal/Woche neu starten, weil sonst irgendwann manche Objekte nicht mehr vom js erkannt werden.

**Comment by Hans-Zwiesel** [comment]
Ich habe heute bei einem Device die Objekte "lastInactive" und "lastInactive-ts" manuell angelegt, weil sie nach Tagen
immer noch fehlten.

Seitdem erscheint im Log wieder der Error 500!!!!!!!
**2020-10-01 18:32:33.375  - warn:  tr-064.0 (9852) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-J5-2016/A0:10:81:07:47:D0):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}**

**Comment by Apollon77** [comment]
Dann lösch die states doch mal wieder? ;-)
Die States werden angelegt wenn Sie zum ersten mal relevant werden bei dem Adapter hier

**Comment by Hans-Zwiesel** [comment]
Benutzer hat neues Handy, deshalb das Device komplett gelöscht und neues Gerät eingetragen.
Adapter hat neues Device mit States angelegt, wieder ohne Objekte "lastInactive" und "lastInactive-ts" .
Seitdem wieder jede Menge Einträge:
`2020-10-05 05:31:42.938 - warn: tr-064.0 (21454) forEachConfiguredDevice: in GetSpecificHostEntry 3(PC-192-168-179-5/50:85:69:E6:48:7E):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}
`

**Comment by Apollon77** [comment]
Und das Handy ist aktuell gerade online im Netzwerk oder nicht?

**Comment by Hans-Zwiesel** [comment]
Das Handy ist aktuell bei der FritzBox im Gastnetz angemeldet

**Comment by Apollon77** [comment]
und trotzdem kommt der fehler? zeigt die fritzbox ui es korrekt an?

**Comment by Hans-Zwiesel** [comment]
Das ist wirklich so, FritzBox Netzwerk war die Anzeige o.k.
Keine FritzBox UI sondern eine FritzBox 7590.

Neu:
Ich hatte mich geirrt, das Device "PC-192-168-179-5" war falsch. Gerät deshalb gelöscht und das richtige Gerät (Galaxy-S7-edge)
neu angelegt (Ändert aber an meiner Fehlerbeschreibung nichts). 
Selber Vorgang wie mit dem falschen Gerät.
Adapter hat neues Device mit States angelegt, wieder ohne Objekte "lastInactive" und "lastInactive-ts" .
Seitdem KEINE Fehler Einträge (nach 8 Stunden)!!!!!!!!!!

**Comment by Apollon77** [comment]
Also war das Device falsch angelegt oder wie?

So wie ich es verstehe kommt der Fehler wenn der Adapter ein gerät mit einer IP oder Mac abfragen will die es aber in der netzwerkansicht nicht mehr gibt ... das ist meine vermutung. Ist die jetzt kroreekt oder nciht? Wenn korrekt dann könnte man den Error 500 da einfach als "Device nicht da" deuten und nicht als error loggen und fertig sind wir

**Comment by Siggi0904** [comment]
Also ich hab gerade zwei Geräte hinzugefügt, da werden die benannten Datenpunkte sauber angelegt.

@Apollon77 
Wenn du mit mit "nicht mehr gibt" nicht mehr erreichbar, da WLAN aus oder nicht mehr in Reichweite, dann könnte die Auswertung von Fehler 500 als active=false richtig sein. Das passt ja auch, zumindest bei mir.
Ich hab das Haus verlassen und nach gewisser Zeit kam dann der Fehler 500.

Evtl. wäre eine doppelte Prüfung gut. Dann kann das Wiedereinbuchen des Handy's ins WLAN besser abgefangen werden.
Es kann ja auch ein Fehler 500 auftreten, wenn das Handy wiederkommt, aber das Anmelden noch nicht abgeschlossen ist.

**Comment by Hans-Zwiesel** [comment]
@Apollon77
Neben der FB läuft auch noch ein Ubiquiti Access Point und ein FB PowerLine 540 AP.
Es ist ja möglich, dass die FB einen anderen Zustand meldet, wenn ein Gerät vom AP an und abgemeldet wird, als wenn
das Gerät direkt an der FB an und abgemeldet wird.
In der FB Netzwerkansicht ist kein Unterschied erkennbar, mit welchem AP das Gerät angemeldet ist/war.
Evtl. wird das Abmelden vom AP mit Fehler 500 ausgewertet.

Den Fehler 500 als active=false auszuwerten wäre auf jeden Fall einen Versuch wert, und bitte auch noch
die beiden States  "lastInactive" und "lastInactive-ts" mit den anderen States anlegen und nicht erst wenn sie benötigt werden.
Vielen Dank.

**Comment by Ilovegym66** [comment]
@Hans-Zwiesel kein Wunder funktioniert das nicht. Andere AP teilen der Fritzbox weniger Informationen mit, welche Geräte dort angemeldet sind, habe das gleich mit einem TP-Link, auf dem OpenWRT ist, was dort angemeldet ist, bekommt die Fritzbox garnicht mit.

**Comment by Hans-Zwiesel** [comment]
@Ilovegym66
Alle angemeldeten Geräte an den AP's sind in der Netzwerkumgebung der FB sehr wohl aufgeführt!!

**Comment by Hans-Zwiesel** [comment]
@Apollon77
Heute morgen wieder Error 500. 

Das Gerät Galaxy-S7-edge war an der FB angemeldet und hat sich irgendwann an einem AP angemeldet.
Seit 7:43 nicht mehr angemeldet, seit dem jede Minute der Error 500.
Die Abwesenheit wird nicht erkannt und die beiden States "lastInactive" und "lastInactive-ts" fehlen immer noch.
Es ist also so:
Aus irgendeinem Grund wird die Abwesenheit nicht erkannt und dafür der Error 500 ausgegeben.

Also bitte den Error 500 als abwesend auswerten, wie vorgeschlagen.
Vielen Dank.



2020-10-07 06:55:06.497  - warn:  tr-064.0 (21962) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-S7-edge/8C:F5:A3:7A:A1:AE):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}
2020-10-07 07:02:11.793  - warn:  tr-064.0 (21962) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-S7-edge/8C:F5:A3:7A:A1:AE):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}
2020-10-07 07:03:12.528  - warn:  tr-064.0 (21962) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-S7-edge/8C:F5:A3:7A:A1:AE):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}
2020-10-07 07:04:13.631  - warn:  tr-064.0 (21962) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-S7-edge/8C:F5:A3:7A:A1:AE):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}
2020-10-07 07:05:14.334  - warn:  tr-064.0 (21962) forEachConfiguredDevice: in GetSpecificHostEntry  3(Galaxy-S7-edge/8C:F5:A3:7A:A1:AE):Error: sendSOAPActionRequest Error  action=GetSpecificHostEntry  serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}

**Comment by Siggi0904** [comment]
Also ich kann das Verhalten bestätigen.
Sobald mein Android Handy die Fritzbox verlässt, bekomme ich diesen Fehler 500.

Können wir kurzfristig mit einer neuen Version rechnen, die den Fehler 500 einfängt und den Status auf false setzt?

Großen Dank im Voraus.

**Comment by Hans-Zwiesel** [comment]
@Apollon77
Es sind 4 Handy's angemeldet.
Der Fehler 500 erscheint nur bei einem Handy, bei den 3 anderen wird aktiv/inaktiv richtig angezeigt.
Ursache unbekannt.

**Comment by Apollon77** [comment]
Ok, hab mal reingeschaut weil es heute wegen FB Wechsel auch bei mir zu solchen Fehlern kam. Es sollte nur passieren wenn eine MAC-Adresse für einen Eintrag hinterlegt ist. macht den mal weg. geht es dann? Das zu fixen wird einiges an Aufwand, weil der Code an der Stelle die erfolgreich zurückkommenden Daten von der FB nutzt um die States zum "schreiben" zu finden ... ergo: Keine Antwort keine Info was der korrekte State Name ist (es wird hier der FB name über dem in der Konfig eingetragenen genutzt) ... Da muss ich mal ganz tief drüber nachdenken

**Comment by Hans-Zwiesel** [comment]
Handy nicht an FB und nicht an AP angemeldet – Fehler vorhanden.

Wenn die MAC Adresse gelöscht wird, dann wird der ganze Eintrag gelöscht.

Neuer Eintrag nur mit MAC Adresse möglich.

Eintrag manuell wieder hergestellt – Fehler wieder da (auch wenn mein ESP-8266 Programm läuft-Verdacht nicht bestätigt)

 

D.h. ich kann Fehler reproduzieren, wenn ich einen Eintrag anlege mit einer MAC die es nicht gibt.

Ein Objekt wird dabei nicht angelegt.

 

Es muss aber mit der MAC und NICHT mit der IP funktionieren, weil die Gastnetz IP vom Raspbi aus nicht erreichbar ist.

 

-          Kann sich denn der Adapter die Daten zu „Schreiben“ nicht merken wenn er sie zum Schreiben benötigt und nur feststellen dass das Gerät nicht da ist?

-          Wieso funktioniert es bei meinen 3 anderen Handy’s, auch wenn sie nicht angemeldet sind?

 

 

Von: Ingo Fischer [mailto:notifications@github.com] 
Gesendet: Sonntag, 18. Oktober 2020 16:01
An: iobroker-community-adapters/ioBroker.tr-064
Cc: hanss; Mention
Betreff: Re: [iobroker-community-adapters/ioBroker.tr-064] Status Geräteliste wird nicht aktualisiert (#160)

 

Ok, hab mal reingeschaut weil es heute wegen FB Wechsel auch bei mir zu solchen Fehlern kam. Es sollte nur passieren wenn eine MAC-Adresse für einen Eintrag hinterlegt ist. macht den mal weg. geht es dann? Das zu fixen wird einiges an Aufwand, weil der Code an der Stelle die erfolgreich zurückkommenden Daten von der FB nutzt um die States zum "schreiben" zu finden ... ergo: Keine Antwort keine Info was der korrekte State Name ist (es wird hier der FB name über dem in der Konfig eingetragenen genutzt) ... Da muss ich mal ganz tief drüber nachdenken

**Comment by Hans-Zwiesel** [comment]
@Siggi0904
> 
> Also ich kann das Verhalten bestätigen.
> Sobald mein Android Handy die Fritzbox verlässt, bekomme ich diesen Fehler 500.
> 
> Können wir kurzfristig mit einer neuen Version rechnen, die den Fehler 500 einfängt und den Status auf false setzt?
> 
> Großen Dank im Voraus.

Abhilfe, bis der Fehler gefixt wird - tr-064 Adapter muß Log-Stufe INFO haben:

`
let TimerC
function checkWarn(data) {
    if(data.message.includes("forEachConfiguredDevice: in GetSpecificHostEntry 3(Galaxy-S7-edge")){ 
        setState('tr-064.0.devices.Galaxy-S7-edge.active',false)
        clearTimeout(TimerC)
        TimerC = setTimeout(function () {           
            setState('tr-064.0.devices.Galaxy-S7-edge.active',true)  // Anwesend
        },3 * 60 * 1000)                          // wenn 3min. kein Abwesend, dann Anwesend
    }
}
onLog("warn", checkWarn)
`

**Comment by Siggi0904** [comment]
Ja, das kenn ich. Das blendet aber nur die Meldungen aus.
Die Variable Anwesenheit wird aber beim Fehler 500 nicht gesetzt/geändert.
Somit werden auch keine Skripte getriggert.

Danke.

**Comment by Hans-Zwiesel** [comment]
Getriggert wird hiermit (warn-logs): onLog("warn", checkWarn)
Das Script muß natürlich noch für die Geräte angepasst werden.

**Comment by Siggi0904** [comment]
Wie soll ich mit Blockly auf eine Warnmeldung triggern.

Ich glaub das führt hier zu nichts.
Erstmal muss das richtig im Adapter korrigiert werden.
Bis dahin bleibt das Handy draußen.

**Comment by Apollon77** [comment]
Also ich habe jetzt mal für die Übergangszeit bis zu einer richtigen Lösung in die aktuellste Version eingebaut das der Error 500 Fall erkannt und "nur" als "info "geloggt wird. Ich hatte noch keine Zeit mir was sauberes zu überlegen für den "offline definieren" Fall

**Comment by Apollon77** [comment]
Ok, da ist mir doch glatt ne Idee gekommen ... Wer mag bitte mal GitHub version testen?

WENN das gerät in der fritzbox beim start des adapters da ist und kein error 500 liefert dann merkt sich der adapter den letzten Stand und nutzt den um im Fall eines Error 500 es zu nutzen und das Gerät offline zu setzen. Die Lösung geht nur schieff (und dann wird info geloggt) wenn das gert schon beim adapterstart den Fehler wirft weil dann fehlt die Initialisierung.

Bitte testen!!

**Comment by Hans-Zwiesel** [comment]
Heute morgen die Version 4.1.1 installiert.
Funktioniert einwandfrei. (Gerät war beim Adapterstart vorhanden)
Beim Abmelden wurden auch die Objekte LastInaktive.. angelegt.
Vielen Dank.

**Comment by Apollon77** [comment]
Cool, dann release ich das heute Abend mal. vllt findet noch jemand zeit zu testen

**Comment by Hans-Zwiesel** [comment]
Vielleicht findest Du bis dahin auch noch einen Trick, damit man den Adapter auch starten kann,
wenn das Gerät abgemeldet ist.

**Comment by Siggi0904** [comment]
Hallo,
wann geht denn die Version ins stable? Ich bin sehr an einer Lösung zu dem Fehler interessiert.
Ich möchte aber nicht aber Beta umstellen.
Danke.

**Comment by Apollon77** [comment]
Der offizielle Prozess ist das ein Adapter zuerst in Latest geht, dann wird gewartet bis eine bestimmte ANzahl User die Verison hat und keine Probleme aufgetauscht sind. Erst dann geht es in Stable (was der Name so sagt)

**Comment by Apollon77** [comment]
4.2.0 geht jetzt auf npm und ins latest damit.

@Siggi0904 Alternativ zu Umstellung auf Beta kannst du auch nur den Adapter vom GitHub installieren

**Comment by Siggi0904** [comment]
Dann hoffe ich, dass die Version dann kurzfristig auch ins stable wandert.
Ich würde gern beim stable channel bleiben.

**Comment by Apollon77** [comment]
Ohne das Sie jemand testet und bestätigt das Sie irgendwas fixt geht Sie nicht wirklich ins Stable.

**Comment by Siggi0904** [comment]
Danke für das übernehmen ins Stable.

Riesen Dank auch für die neue Schaltfläche auf dem Dashboard.
Könntest du die Schaltfläche im Dashboard Instanzen-Abhängig machen?
Ich habe zwei Fritzboxen mit unterschiedlichen IP's. Da wäre das toll, wenn die auch so auf dem Dashboard im IOBroker wären.

**Comment by Apollon77** [comment]
hä?? Was hat das hiermit zu tun? Und was ist generell das Problem?

**Comment by Apollon77** [comment]
PS: Speichere rmal beide instanzen im Admin neu ... dann ists wie DU willst

**Comment by Siggi0904** [comment]
Sehr cool, danke für den Hinweis.

Fehler scheint auch weg zu sein.
Ich stelle nachher meine Anwesendheitserkennung wieder um.
Dann schau ich, dass alles super läuft.
