### ISSUE TITLE
Adapter startet nicht mit Frizbox 3390

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.tr-064#161]
Hallo,

ich möchte die aktuelle Version vom TR-064 mit der Fritzbox 3390 verwenden.
Leider wird keine Verbindung hergestellt.

Fritzbox: 3390 mit letzter Softwareversion
Benutzeranmeldung umgestellt auf Benutzername und Kennwort
Benutzer angelegt und eingericht
Fritzbox neu gestartet nach Anlegen des FritzBox-Nutzers

Werden bestimmte Fritzboxen nicht unterstützt?
Was ist die Mindestanforderung an die Fritzbox?
![Einstellung TR--064](https://user-images.githubusercontent.com/4992106/92782796-8d0fd580-f3a5-11ea-8490-56ca1912af25.jpg)
[Log-TR064 - Fritzbox 3390.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/5204005/Log-TR064.-.Fritzbox.3390.txt)

**Comment by Apollon77** [comment]
Bisher ist nichts bekannt. Ist auch alles eingestellt wie in der Readme gesagt? Da ist noch eine Einstellung beim user nötig.

**Comment by Siggi0904** [comment]
So ist der Nutzer auf der Fritzbox eingerichtet.

![grafik](https://user-images.githubusercontent.com/4992106/92994256-20a5eb00-f4f9-11ea-9ae4-52fc1b1781f7.png)

Was mich wundert ist der Eintrag im Log:
`tr-064.0	2020-09-10 20:26:56.775	error	(25502) !device - "!device"`

**Comment by Apollon77** [comment]
Bitte mal Log auf Debug stellen und volles Debug Log posten

**Comment by Siggi0904** [comment]
Hängt dem ersten Post schon an.

**Comment by Apollon77** [comment]
Interessant, ich kann mir nur vorstellen das die konfig falsch ist. Die Ip passt? 

Versuch mal von dem Rechner wo ioBroker läuft ein

curl -v http://IP:49000/tr64desc.xml

"IP" bitte mit deiner IP bzw exakt das was du angegeben hast im Adapter tauschen. Kommt da en XML dokument zurück?

Es sieht aus wie ein Timeout beim abrufen dieser Info

**Comment by Siggi0904** [comment]
Das ist die curl Rückgabe:
![grafik](https://user-images.githubusercontent.com/4992106/92994838-39fd6600-f4fe-11ea-8559-3bd72e55324c.png)

**Comment by Apollon77** [comment]
Dann ist das das Problem ... ich glaube da war noch eine andere EInstellung ind er Fritzbox generell das das überhaupt "exposed" wird.

Hast DU auch https://www.google.com/search?q=fritzbox+tr-064+einstellungen&safe=off&client=firefox-b-d&tbm=isch&source=iu&ictx=1&fir=HQULsrt3TgjiyM%252ClqeE8CXxys78aM%252C_&vet=1&usg=AI4_-kRyOm3DnEvhN9R7V7bQ51zojMT0pg&sa=X&ved=2ahUKEwjtra2ly-PrAhUsIcUKHfGyDHkQ9QF6BAgIEAM#imgrc=HQULsrt3TgjiyM gesetzt?

**Comment by Siggi0904** [comment]
Super, das wars. Die Option war in der Fritzbox deaktiviert.
Nach Aktivierung konnte ich den Adapter online schalten.

Der Hinweis, was zu aktivieren ist, sollte in die Readme aufgenommen werden.
Also die folgenden Punkte:
- Benutzeranmeldung umgestellt auf Benutzername und Kennwort
- Benutzer anlegen und einrichten
- Auf der Fritzbox Menü Heimnetz -> Netzwerk ->Heimnetzfreigaben -> Zugriff für Anwendungen -> aktiviert

**Comment by Apollon77** [comment]
Danke,mache ich!
