### ISSUE TITLE
**gelöst** - Bitte IP Adresse der Konfig statt des Namens verwenden

### ISSUE THREAD

**Issue by roadie33** [iobroker-community-adapters/ioBroker.tr-064#165]
Hallo zusammen,
warum wird statt der IP Adresse aus der Konfiguration des Adapters der Name "fritz.box" verwendet?
![grafik](https://user-images.githubusercontent.com/58664090/94348462-c51d4680-003c-11eb-9fc4-a9e0f62dc07b.png)
Ich habe tmporär die Namensauflösung in meiner hosts Datei meines ioBroker eingetragen. So kann aber nur 1  Instanz des Adapters betrieben werden, da eine Unterscheidung über die IP Adresse so nicht mehr möglich ist.

**Comment by Apollon77** [comment]
Wie sieht die Konfig denn aus? Welche Adapter Version?

**Comment by roadie33** [comment]
![grafik](https://user-images.githubusercontent.com/58664090/94362541-54b60a00-00bc-11eb-89be-558545c523c1.png)
![grafik](https://user-images.githubusercontent.com/58664090/94362558-70211500-00bc-11eb-9ceb-052144eda0be.png)
![grafik](https://user-images.githubusercontent.com/58664090/94362622-fccbd300-00bc-11eb-8282-404b6a8e23a8.png)

**Comment by Apollon77** [comment]
Ja ich hab den Fehler gesehen. Speichert mal die Einstellungen neu. Dann ist’s gefixt oder auf fix version warten

**Comment by roadie33** [comment]
Ich habe in der Konfig die IP Adresse auf eine "falsche" Adresse gestellt und abgespeichert. Im Log ist zu sehen, dass die IP Adresse angesprochen wird.
![grafik](https://user-images.githubusercontent.com/58664090/94393126-81b8fa00-015a-11eb-96ad-51b5529ccc50.png)
Nach dem Löschen der Namensauflösung in der /etc/hosts Datei und dem konfigurieren der "richtigen" IP Adresse ist der Adapter gestartet und hat die Verbindung zur Fritzbox aufgenommen.
Danke für die schnelle Hilfe und den Workaround.

**Comment by roadie33** [comment]
Danke an Apollon77 für die schnelle Unterstützung und den Workaround. Der Fehler wird in einem der nächsten fix version behoben.
Ich schließe die Frage
