### ISSUE TITLE
WOL einbauen

### ISSUE THREAD

**Issue by MCepheus** [iobroker-community-adapters/ioBroker.tr-064#167]
Hi, erst einmal danke für den tollen Adapter und die Arbeit die hineingesteck wurden und werden.

Request: Vielleicht ist es möglich unter "Devices" noch den Punkt "Wake on Lan" hinzuzufügen um über diesen Adapter Geräte aus der Ferne starten zu können.
Danke!

**Comment by Apollon77** [comment]
... weiss jemand wie das mit tr-064 als protokoll geht?

**Comment by MCepheus** [comment]
HI, ich habe keine Ahnung vom tr-064 Protokoll und auch sonst krame ich mir die Sachen immer per "learning by doing" zusammen.
Google hat mir das hier vorgeschlagen. Vielleicht hilft es dir dabei?
https://www.ip-phone-forum.de/threads/fritzbox-7490-wake-on-lan-%C3%BCber-udp-port-9-klappt-nicht-mehr.284397/post-2259644
VG

**Comment by Azathoth88** [comment]
Ich würde mich grundsätzlich auch dafür aussprechen. Mein ioBroker befindet sich in einem anderen Netzwerk, sodass ich die Geräte innerhalb des FritzBox-Netzwerkes nicht vom ioBroker ansprechen kann bzw. das Magic-Packet nicht versenden kann.

> ... weiss jemand wie das mit tr-064 als protokoll geht?


Heimnetz
LanDeviceHosts | Heimnetzgeräte, Wake-on-LAN, FRITZ!Mesh | 15.08.18 | [hostsSCPD.pdf](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/hostsSCPD.pdf)

2.8 X_AVM-DE_WakeOnLANByMACAddress sieht mir beinah nach dem benötigten Punkt aus.

**Comment by mczeus** [comment]
wäre genau das was ich auch benötigen würde!
Sollte doch eignetlich schon händisch mit dem Command DP im Adapter möglich sein.
