### ISSUE TITLE
Umbenennen der hinzugefügten Geräte wird nicht übernommen

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.tr-064#169]
Wenn man beim Einlesen von Geräten diesen Gerätenamen aus der Fritzbox überschreibt, 
wird dieser nicht übernommen und nicht unter den Objekten angezeigt.

Dort erscheint weiterhin der ursprüngliche Name aus der Fritzbox.

In der Geräteübersicht des Adapters steht aber der neue Name des jeweiligen Gerätes,

**Comment by Siggi0904** [comment]
Hallo,

kann der Fehler bestätigt werden?

**Comment by Apollon77** [comment]
Kannst Du bitte den Fehler genauer beschreiben? Das was Du überschreibst ist wie die "Objekt-IDs" benannt werden so wich ich es verstehe. Der Name der bei den Device-Objekten angezeigt wird ist aktuell immer das was aus der Fritzbox kommt.

**Comment by Siggi0904** [comment]
Ich habe den Namen im Adapter selbst unter Geräte geändert.
Der wird aber nicht in den die Objekte-Übersicht übernommen.

![grafik](https://user-images.githubusercontent.com/4992106/98579851-6ac00880-22bf-11eb-88a8-833e0d36fba4.png)

Und in den Objekten lässt mich der Adapter den Namen ja ändern.

![grafik](https://user-images.githubusercontent.com/4992106/98579984-a22eb500-22bf-11eb-811d-aa381072a9ce.png)

**Comment by Apollon77** [comment]
Ok, wie bereits oben gesagt: Der Name in der Konfig ist aktuell nur da relevant. Der Name aus der Fritzbox ist "der" master name. Um das zu ändern müsste man erstmal sinnvoll definieren wie es denn besser ist.

**Comment by Siggi0904** [comment]
Naja, ich würde alles an den IP-Adressen festmachen. Egal ob V4 oder V6.
Der Name aus der Fritzbox wird als Initialwert übernommen, kann dann aber im IOBroker geändert werden.

Am Besten ist es, dies nicht an den symbolischen Bezeichnungen der Geräte festzumachen sondern nur an den IP-Adressen.
Denn die wird sich ja nicht ändern.

**Comment by Apollon77** [comment]
Ist nicht korrekt ... wenn man die IPs nicht festpinnt können sich die schnell ändern. Weiterhin wäre eine Umstellung komplett Breaking für den Adapter, also in meinen Augen keine echte Option

**Comment by Siggi0904** [comment]
Oh, okay.
Dann bin ich nur von meiner Einrichtung ausgegangen.

Dann muss man das ganze neu denken.
