### ISSUE TITLE
Anwesenheitserkennung nicht korrekt bei Access Points != AVM, Fritz!OS Problem?

### ISSUE THREAD

**Issue by jayfizzle** [iobroker-community-adapters/ioBroker.tr-064#173]
Hallo zusammen,

mir ist aufgefallen das Geräte die mit einem anderen AP (nicht AVM) verbunden  sind, nicht korrekt dargestellt werden bzw.
werden diese vom Adapter sowie auch von der FB selbst als offline angezeigt, obwohl diese online sind.

Kann dies mit der aktuellsten Fritz OS zusammenhängen? 

Vor dem Update des Fritz OS meine ich hätte dies definitiv korrekt funktioniert, die Geräte hinter dem AP (nicht AVM) wurden alle per LAN verbunden aufgelistet, nun gar nicht.
Kann das jmd. bestätigen?

Habe eine FB 7490, den Fritz Repeater 2400 als AP und einen Xiaomi Router als AP in Benutzung, sobald ein mobiles Gerät mit dem Xiaomi AP verbunden ist, denkt die FB 7490 
das Gerät sei offline, dementsprechend zeigt der Adapter dies natürlich auch falsch an.

Fritz!OS 07.21
Fritzbox 7490
iobroker Adapter 4.1.0
Node.js v12.19.0
NPM 6.14.8

**Comment by Apollon77** [comment]
Wenn die FB sie auch als offline anzeigt dann muss der Fehler dort sein, der Adapter kann dann nichts dafür
