### ISSUE TITLE
Anruf von gleicher Telefonnummer

### ISSUE THREAD

**Issue by HolgerOnGithub** [iobroker-community-adapters/ioBroker.tr-064#176]
Hallo,
mein SIP Türsprechstellentelefon Ruf immer die gleiche Externe (da es mit interner ja gar nicht geht) Rufnummer an.
Leider ist daher der Wert von Caller unter tr-064-callmonitor-inbound-caller nicht auswertbar wenn nacheinander geklingelt wird ohne das zwischendurch jemand angerufen hat.
Nun habe ich gelesen das es der Adapter auch gar nicht mag wenn man diesen Wert einfach überschreibt.
Wie kann ich das Problem lösen ohne den Umweg zu gehen mittels ioBroker und asterisk einen anruf durchzuführen.
Danke im Voraus
Gruss Holger

**Comment by Ilovegym66** [comment]
Du triggerst auf ringing und dann fragst du die Nummer ab.. 🙂

**Comment by HolgerOnGithub** [comment]
so einfach kanns sein *ankoppPatsch*

**Comment by HolgerOnGithub** [comment]
> 
> 
> Du triggerst auf ringing und dann fragst du die Nummer ab.. 🙂

Jetzt ist der Adapter nur zu langsam also nach ringring steht noch die "letzte" Nummer drin also wird dennoch ausgeführt (ja natürlich kann ich verzögern) aber da verzögert sich ja alles immer mehr und wir reden von der Türklingel und den flüchtenden Lieferdiensten :-D

**Comment by Feuer-sturm** [comment]
@HolgerOnGithub kannst du nicht einfach auf den Zeitstempel der letzten Aktualisierung prüfen? Dann brauchst du nicht den Umweg über Ringing.

**Comment by HolgerOnGithub** [comment]
> 
> 
> @HolgerOnGithub kannst du nicht einfach auf den Zeitstempel der letzten Aktualisierung prüfen? Dann brauchst du nicht den Umweg über Ringing.

ich wüsste nicht wie, die json wird ja aktualisiert und dort steht alles drin (neue uhrzeit etc) aber ich weis nicht wie ich sie in segmenten überprüfen kann.

**Comment by Feuer-sturm** [comment]
Mir ist glaub ich noch nicht ganz klar worauf du reagieren möchtest, bzw. was du auswerten möchtest.

Möchtest du den Datenpunkt tr-064.0.callmonitor.inbound.caller überwachen und etwas triggern, wenn eine spezielle Nummer anruft? Das könnte man so lösen:

```
on({id: "tr-064.0.callmonitor.inbound.caller", change: "any"}, function (obj) { 
    if(getState("tr-064.0.callmonitor.inbound.caller").val == "0123456"){
        console.log("Türklingel hat angerufen");
    }
});
```

Ansonsten wäre es hilfreich, wenn du noch etwas genauer beschreibst was du vorhast.

**Comment by HolgerOnGithub** [comment]
Hallo @Feuer-sturm 
erst einmal vielen Dank. Ja ich möchte wenn die Tür anruft (hat eine spezielle Rufnummer und ruft auch eine spezielle Rufnummer an) im weiteren Analyseprozess eine Telegramnachricht mit angehängten Fotos der Türkamera senden. Das Skript zum Telegramsenden funktioniert. Jedoch die Auslösung durch die Caller "rufnummer" halt nur einmal. Nun ist es natürlich nicht untypisch das mehrfach am Tag geklingelt wird ohne das zwischendurch jemand angerufen hat. Also ändert sich der Caller Wert nicht da der TR-064 den Wert nur überschreibt wenn es einen neuen gibt. Dieses PRoblem versuche ich zu lösen. Normalerweise würde ich den Caller-Wert einfach anders überschreiben, jedoch mag das der Adapter wohl so gar nicht.

**Comment by Feuer-sturm** [comment]
Dann probier doch meinen Codeschnipsel einmal aus, damit solltest du einen Schritt weiter kommen.

Wenn du in ioBroker die Statusansicht aktivierst, dann siehst du auch den Zeitstempel. Dieser wird sich ändern, auch wenn mehrfach deine Haustür bei dir anruft.
![grafik](https://user-images.githubusercontent.com/25422320/97790333-0c609f00-1bc8-11eb-989f-6f37e66df8c9.png)

 Durch das change: "any" wird der Trigger immer ausgeführt, sobald sich am Objekt etwas ändert (wie zum Beispiel der Zeitstempel). Wenn du bei change: ein "ne" einträgst für not equal, wird der Trigger nur ausgeführt, wenn sich der Wert ändert.

**Comment by HolgerOnGithub** [comment]
seltsamer weise geht es heute mit ringring auch bei gleicher nummer in caller
