### ISSUE TITLE
"+ Geräte hinzufügen" funktioniert nicht

### ISSUE THREAD

**Issue by The-Batchman** [iobroker-community-adapters/ioBroker.tr-064#179]
Ein Hinzufügen von Geräten mit "+ Geräte hinzufügen" funktioniert nicht.
Wenn nach dem Eintragen der Daten "Speichern und Schließen" angeklickt wird,
ist beim nächsten Öffnen der Geräteseite die Zeile leer.

Ich kann derzeit nur über "Geräte suchen" ein Gerät hinzufügen.
Das bedeutet, ich kann nur Geräte hinzufügen, die derzeit im Netz
angemeldet sind.

 - Adapter version: 4.1.0
 - JS-Controller version: 3.1.6
 - Node version: 14.15.0
 - Operating system: Linux

**Comment by Ilovegym66** [comment]
auch mit Node 12.19.0 das gleiche verhalten.

**Comment by McWoolf** [comment]
Hi.
Vielleicht eine doofe Frage, aber wozu soll (muss) man in dem Adapter Geräte hinzufügen? Vor allem welche? Nur Fritz!Geräte oder sämtliche Geräte welche angemeldet sind? Und was macht dieser Adapter mit den hinzugefügten Geräten?
Danke für Antworten.

**Comment by The-Batchman** [comment]
> 
> 
> Hi.
> Vielleicht eine doofe Frage, aber wozu soll (muss) man in dem Adapter Geräte hinzufügen? Vor allem welche? Nur Fritz!Geräte oder sämtliche Geräte welche angemeldet sind? Und was macht dieser Adapter mit den hinzugefügten Geräten?
> Danke für Antworten.

Na, zum Beispiel Mobiltelefone. Aus deren Vorhandensein im WLAN kann dann z.B. eine An-/Abwesenheit von Personen im Haus abgeleitet werden.

**Comment by McWoolf** [comment]
Hmm ist dafür nicht der Fritzbox CheckPresents Adapter zuständig??
