### ISSUE TITLE
Bug? Gast-Wlan und Anrufbeantworter lässt sich nur noch einschalten

### ISSUE THREAD

**Issue by Lucifor1976** [iobroker-community-adapters/ioBroker.tr-064#182]
**Describe the bug**  
Mir ist heute aufgefallen das sich das Gast -WLan und der AB nur noch einschalten lassen. Ausschalten ist nicht mehr möglich. Loglevel auf Debug zeit das die Befehle an die Fritzbox gehen. Aber on den Objekten wird nur das Einschalten mit "grün" bestätigt, das abschalten jedoch mit rot. Im Tooltip wird das Einschalten als bestätigt angezeigt, das ausschalten jedoch nicht (false).
Neu installation des Adapters bringt keine Abhilfe. Firmware der Fritzbox 7.21, ging aber schon vorher nicht mehr.
Andere Datenpunkte, zumindest DECT Schalter funktionieren einwandfrei.
Apapter ist latest.

**Comment by Feuer-sturm** [comment]
Ich habe eine Fritzbox 7530 mit der Firmware 7.20
Ich kann über den Datenpunkt tr-064.0.states.ab den Anrufbeantworter ein und ausschalten.
Gleiches gilt für das Gäste-Wlan, welches ich über den Datenpunkt tr-064.0.states.wlanGuest ein und ausschalten kann.

Als TR-064 Adapterversion hab ich 4.1.0 im Einsatz.

Welche Adapterversion nutzt du?

**Comment by Lucifor1976** [comment]
4.2.0 
Ich spiele gerade 4.1.0 ein, ich meine das ist seit einem Update, entweder von TR oder von JS. Ich versuch es mal mit 4.1.0

**Comment by Lucifor1976** [comment]
Yes, das wars. Scheint also ein Bug ab Version 4.1.x zu sein!

**Comment by Apollon77** [comment]
Was ist mit 4.1.1?

**Comment by Lucifor1976** [comment]
Lässt sich nicht installieren...

$ ./iobroker upgrade tr-064@4.1.1
Update tr-064 from @4.2.0 to @4.1.1
NPM version: 6.14.8npm install iobroker.tr-064@4.1.1 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.tr-064@4.1.1.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-11-13T22_16_18_380Z-debug.log
upload [2] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/words.js words.js application/javascript
upload [1] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/tr-064.png tr-064.png image/png
upload [0] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/index_m.html index_m.html text/html
Adapter "tr-064" updated
process exited with code 0

**Comment by Apollon77** [comment]
aah ok ...

**Comment by Apollon77** [comment]
Bitte 4.2.1 versuchen, kommt gleich auf npm (10 mins)

**Comment by Lucifor1976** [comment]
Ist noch nicht angekommen, ich geh nun aber schlafen, ich versuchs morgen erneut..

$ ./iobroker upgrade tr-064@4.1.1
Update tr-064 from @4.2.0 to @4.1.1
NPM version: 6.14.8
npm install iobroker.tr-064@4.1.1 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ETARGET
npm
 ERR! notarget No matching version found for iobroker.tr-064@4.1.1.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-11-13T23_14_10_901Z-debug.log
upload [2] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/words.js words.js application/javascript
upload [1] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/tr-064.png tr-064.png image/png
upload [0] tr-064.admin /opt/iobroker/node_modules/iobroker.tr-064/admin/index_m.html index_m.html text/html
Adapter "tr-064" updated
process exited with code 0

**Comment by Apollon77** [comment]
4.2.1 !!

**Comment by Lucifor1976** [comment]
Ohhh.. War schon spät :) 4.2.1 ist installiert und es funktioniert ebenfalls :) Danke.
