### ISSUE TITLE
Frage zu Polling Intervall

### ISSUE THREAD

**Issue by PatrickDa87** [iobroker-community-adapters/ioBroker.tr-064#185]
Hi zusammen,

Standardmäßig ist ja ein Poll Intervall von 10s eingetragen. Ich habe meine Alarmanlage an den Active-State meines Smartphones gekoppelt und würde daher gerne so schnell wie möglich erkennen lassen, dass ich wieder zuhause bin.

Macht ein Poll Intervall von 1s Sinn bzw. kann es da zu Problemen kommen?

Danke vorab :-)

**Comment by Apollon77** [comment]
Probleme sind pot overload der fritzbox. Musst du experimentieren. würde mich langsam nach unten annähern

**Comment by PatrickDa87** [comment]
Kann ich irgendwo in der Fritzbox / ioBroker sehen, wenn es zum "pot overload" kommt?

**Comment by Apollon77** [comment]
ich kenne nur diese "Energieverbrauchsabzeige" und am Ende wird das ding plötzlich unresponsive wenn du es per Web bedienen willst oder ganz schlimm der Adapter wirft komische fehler ....
