### ISSUE TITLE
Information missing in "States" !?

### ISSUE THREAD

**Issue by bauerpower69** [iobroker-community-adapters/ioBroker.tr-064#187]
Dear all,

I checked even the closed Issues but I was not able find the right information. 
Is there any possibility to extend "states" with something like 

**- Firmware version installed
- Firmware version avaiable 
- Update (.t.)/ (.f.)**

![image](https://user-images.githubusercontent.com/25681982/101740763-8cccc680-3ac9-11eb-89a7-5cc91805cd5e.png)

Best regards

Joerg

**Comment by Apollon77** [comment]
if tr-064 protocol offers these fieldfs then yes, else no ... all in states are kind of "commands" and not pure data

**Comment by bauerpower69** [comment]
... I will check it :-)

THX

**Comment by bauerpower69** [comment]
@Apollon77 

Hallo Ingo,

habe mir mal die TR-064 Doku angesehen... jetzt bin ich lein Profi aber im Bereich ACTION --> GetInfo gibt es 
X_AVM-DE_CheckUpdate für mich hinweise auf Verfügbarkeit. Habe auch mal bei AVM nachgefragt .... 

![image](https://user-images.githubusercontent.com/25681982/101750656-9f49fe80-3acf-11eb-8f69-e7adc10f08d8.png)


Lieben Dank 

Jörg
