### ISSUE TITLE
Adapter schaltet Device auf FALSE / keine Ereignisse in der FB

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.tr-064#188]
Ich habe das Problem, daß meine Devices (iPhone SE 1. Gen) auf false / true switchen, wenn diese über einen bestimmten Repeater eingewählt sind. In den Ereignissen der FritzBox erscheint nicht von Ab- & Anmeldungen der WLAN Geräte, obwohl dieses aktiviert ist. Ich habe den Eindruck, daß es seit dem letzten Update so ist / vielleicht sind es aber auch einfach nur äusserliche Umstände?!

**Versions:**  
 - Adapter version: 4.10.8
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: Armbian Linux 4.19.69-rockchip

**Comment by Apollon77** [comment]
Was ist denn dad für ein "bestimmter Repeater? Wo ist der anders wie andere?

**Comment by LJSven** [comment]
Ob es am Repeater liegt, weiß ich halt nicht. das iPhone loggt sich um 15:35 Uhr an der FB aus ->

![Bildschirmfoto 2020-12-10 um 15 51 16](https://user-images.githubusercontent.com/8560588/101787752-b86aa380-3aff-11eb-883c-ec7eb078fb4a.png)

Danach meldet es sich aber über den tr-064 Adapter wieder an ->

![Bildschirmfoto 2020-12-10 um 15 51 29](https://user-images.githubusercontent.com/8560588/101787803-c7515600-3aff-11eb-8bd1-4e7c66851bc4.png)

**Comment by Apollon77** [comment]
Du könntest ja mal die Frage beantworten ... ist es ein AVM Repeater oder ein anderer oder was?

**Comment by LJSven** [comment]
Ja, AVM Repeater 310

Von meinem iPhone gesendet

**Comment by Apollon77** [comment]
Hm ... ok ... dann keine Idee. passiert bei mir nicht. frage ist ja auch ob es - wenn es passiert - auch in der FB kurz aus/an ist - es muss nicht immer im anmelde/abmelde logh stehen wenns ne ummmeldung ist
