### ISSUE TITLE
Changes in FritzOS higher 7.24 in the API

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.tr-064#191]
Hi,
take attention to the next FritzOS, please.

https://avm.de/fritz-labor/frisch-aus-der-entwicklung/bekannte-probleme/

The API and Login with username and password should be changed and need some changes in the assigned tools ( adapters, scripts.. ).

**Comment by Apollon77** [comment]
Thank you for bringing this to our attention.
According to https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Empfehlungen%20zur%20Benutzerfu%CC%88hrung%20bei%20der%20Anmeldung%20an%20einer%20FRITZ%21Box_v1.1.pdf the main change is that "ONLY logins with username and password are possible starting 7.24 ... becaus ethe adapter already only uses that I would not see any change, correct?

**Comment by Ilovegym66** [comment]
yes, but if the user don't create a user in the fritzbox, the FritzOS create itself a user "fritz" .. looks like it make sense to make a link to this in the docu? 
I use since Monday FritzOS 7.24-84707 beta, no problems.

**Comment by Apollon77** [comment]
I would expect that this user is then shown in the Userlist in Fritzbox admin or?!

**Comment by Ilovegym66** [comment]
yes, I don't test this, but in the docu from AVM it's written down.. :-)
