### ISSUE TITLE
FRITZ!OS 7.25: Änderungen

### ISSUE THREAD

**Issue by latzi0710** [iobroker-community-adapters/ioBroker.tr-064#195]
Laut AVM gibt es ab 7.25 Änderungen in der Anmeldung (kann mit 7.24 derzeit getestet werden). Hier der Link dazu: `https://avm.de/service/schnittstellen/`
Ist dies schon berücksichtigt?

**Comment by Apollon77** [comment]
yes, please see #191 ... duplicate
