### ISSUE TITLE
Guest Wifi lässt sich nicht mehr aktivieren

### ISSUE THREAD

**Issue by mariomm** [iobroker-community-adapters/ioBroker.tr-064#196]
**Describe the bug**  
Guest Wifi lässt sich über den Datenpunkt nicht mehr aktivieren

**To Reproduce**  
1. tr-064.0.states.wlanGuest -> true
2. check Fritzbox Guest Wifi ist offline
Alles andere scheint zu funktionieren
Manuelles aktivieren des Guest Wifi über die Fritzbox GUI funktioniert.

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: 2.2.9
 - Node version: v10.19.0
 - Operating system: Debian GNU/Linux 9.12 (stretch)
 - - Fritzbox 7390 OS 6.86 und 7430 OS 7.12

**Comment by SliX185** [comment]
Funktioniert wirklich alles andere?
Bei mir fällt es auch nur immer durch das Guest Wifi auf, wobei sich die anderen Werte auch nicht mehr ändern.

Das Log im iobroker ist hat keine Auffälligkeiten bezüglich Anmeldeprobleme in Richtung Fritzbox, jedoch schaut das Log der Fritzbox anders aus....

![fritz anemeldung](https://user-images.githubusercontent.com/47434006/103474840-00e84a80-4da8-11eb-9788-509c09549060.JPG)

Dieses Log kommt ohne Eingriff von meiner Seite zustande. Manchmal funktioniert anscheinend die Anmeldung, manchmal auch nicht.

**Versions:**  
 - Adapter version: 4.2.2
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: Debian GNU/Linux 10 (buster)
 - Fritzbox 6490 Cable (KD Mietbox) OS 7.12

**Comment by mariomm** [comment]
Es läuft wieder. Irgendwie wollte er die Anmeldung nicht. Adapter neu installiert, dann gings wieder
