### ISSUE TITLE
Verbindungsprobleme bestehen immer noch

### ISSUE THREAD

**Issue by scripthase** [iobroker-community-adapters/ioBroker.tr-064#202]
Guten Morgen,

wie in einem anderen Issue schon erklärt bestehen bei mir Probleme mit der Verbindung der Fritz!Box.
Alle Einstellungen wurden wie in der Readme gesetzt und auch der Benutzer mit den Berechtigungen, die er benötigt eingerichtet.

Nachdem man nun den Adapter startet und einen kleinen Augenblick wartet, taucht dann immer diese Fehlermeldung auf und Daten werden nicht übermittelt.

```
tr-064.0 (30836) Error: read ECONNRESET - {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
tr-064.0 (30836) ~
tr-064.0 (30836) ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 (30836) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
tr-064.0 (30836) ~
tr-064.0 (30836) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
host.iobroker instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker Restart adapter system.adapter.tr-064.0 because enabled`
```

Kann mir hier vielleicht jemand helfen, damit der Adapter wieder vernünftig und stabil funktioniert?
Vielen Dank schon Mal für die Hilfe!

Gruß
Scripthase

**Comment by Apollon77** [comment]
ECONNRESET bedeutet, wie im anderen Thread bereits gesagt,das die Fritzbox die Verbindung schliesst. Bitte mal Fritzbox neu starten, da hilft manchmal. SOnst alle settings prüfen. AM besten bei solchen Thema im Forum schreiben, da sind mehr User die helfen können
