### ISSUE TITLE
Türsprechanlage FON1 auslesen?

### ISSUE THREAD

**Issue by Strobel2k** [iobroker-community-adapters/ioBroker.tr-064#206]
Moin!
Bevor ich zu iobroker kam, habe ich mir den Klingelpaul zugelegt. Dieser ist zwischen meiner Fritzbox 'Fon1' als Türsprechanlage und der Klingel angeschlossen. Sobald jemand an der Haustür klingelt, klingelt das Telefon.
Jetzt möchte ich gerne zusätzlich das Klingelsignal in iobroker bekommen um weitere Ideen umzusetzen (Alexa, Telegram,..). Hat Könnte ich das mit dem TR-064 realisieren? Kann ich FON1 auslesen? brauche ja theoretisch nur das Signal. Oder gibt es einen anderen Weg?

DANKE! Viele Grüße

**Comment by fs-plugins** [comment]
die Fritzbox signalisiert keine internen Anrufe - deshalb kann man die auch nicht auslesen/überwachen

**Comment by Strobel2k** [comment]
> die Fritzbox signalisiert keine internen Anrufe - deshalb kann man die auch nicht auslesen/überwachen

Danke für die Antwort. Auch wenn sie mir leider nicht weiterhilft. Wie könnte ich mein Problem lösen? Hat jemand eine Idee für mich?

**Comment by fs-plugins** [comment]
tja - zum weiterhelfen müssten mal die tausenden Leute welche im Internet damit hadern massiv direkt bei AVM vorsprechen und diese Funktion einfordern 
bei Suche nach zB Fritzbox intern signalisieren findet man sehr viele Klagen - aber auch Umgehungsvarianten wie z B
Man kann im normalen Fritz-Telefonbuch einen neuen Eintrag mit Namen Türklingel anlegen, mit einer nicht-existierenden VoIP-Telefonnummer, z.B. Tuerklingel@127.0.0.1 (die IP-Adresse ist egal, sie sollte nur nicht nach draussen gehen). Dann kann man eine Kurzwahl zuweisen, z.B. **799, die man von der Haustür anrufen lässt
