### ISSUE TITLE
Wlan object manuell geändert agiert nicht als trigger

### ISSUE THREAD

**Issue by jake840** [iobroker-community-adapters/ioBroker.tr-064#208]
Hi Zusammen,

ich habe meine fritzbox 7490 über den adapter an meinen iobroker auf dem raspi angebunden. hierbei habe ich mir einen schalter erstellt, über welchen ich das wlan meiner fritzbox 2.4 und 5 ghz deaktivieren kann. Dies funktioniert soweit super

Gleichzeitig habe ich meine alexa bzw smart home (homee) so mit dem iobroker verbunden, dass diese den status des wlans auf befehl hin auch ändern können. in den objekten wird der status auch korrekt von true auf false gesetzt...genauso wie wenn ich den schalter im iobroker setze. ALLERDINGS wird dieses setzen auf false oder true nicht über den adapter auf die fritzbox übertragen
Mache ich hier etwas falsch, sollte der objektstatus nicht automatisch auch übertragen werden? bin mir nicht sicher ob es ein issue sein könnte oder der adapter dies so gar nicht vorsieht

danke euch und beste grüße
Jake

**Comment by Apollon77** [comment]
Ich verstehe die Frage nicht. was meinst Du mit " ALLERDINGS wird dieses setzen auf false oder true nicht über den adapter auf die fritzbox übertragen" Wie genau triggerst du?

**Comment by jake840** [comment]
Ich triggere im iobroker über blocky...ich habe eine Abfrage zu meinem smart home und blocky setzt auch den status des objektes richtig um. auch in der vis geht der schalter auf off...aber in der fritzbox wird das wlan eben nicht ausgeschaltet
![image](https://user-images.githubusercontent.com/73329943/106622593-0934d080-6574-11eb-950a-db8a70bcd6aa.png)

ich hoffe mein screenshot wird angezeigt. das objet für wlan 5ghz ist in den objekten auf false...in der fritzbox ist es aber noch an

würde ich es in der visualisierung über den Schalter auf off setzen, sieht es in den objekten genauso aus...und dann geht es in der fritzbox auch aus

**Comment by Apollon77** [comment]
Naja da ist der Fehler ... aktualisiere bewirkt NIEMAND eine Steuerung!! Es wird nur der Wert im Adapter überschrieben. "Steure" musst du im Blockly nutzen
