### ISSUE TITLE
host.raspberrypi | 2021-02-16 16:12:40.666 | Fehler | Instanz system.adapter.tr-064.0 beendet mit Code 1 

### ISSUE THREAD

**Issue by JogiBarbarski** [iobroker-community-adapters/ioBroker.tr-064#216]
Raspberry Pi 4, 8GB
ioBroker.admin 4.2.1
Node.js: v12.20.2
NPM: 6.14.6
js-controller
JS controller Installiert: 3.2.16
OS: linux
Stable (default)
ich bekomme den Adapter tr.064.0 nicht zum laufen. In den Objekten taucht er auch nicht auf. Geräte lassen sich nicht suchen. Das ist der Fehlercode aus dem Log.

host.raspberrypi | 2021-02-16 16:30:00.118 | info | instance system.adapter.daswetter.0 started with pid 21865
tr-064.0 | 2021-02-16 16:29:36.353 | info | (21791) starting. Version 4.2.2 in /opt/iobroker/node_modules/iobroker.tr-064, node: v12.20.2, js-controller: 3.2.16
host.raspberrypi | 2021-02-16 16:29:33.822 | info | instance system.adapter.tr-064.0 started with pid 21791
host.raspberrypi | 2021-02-16 16:29:03.703 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.raspberrypi | 2021-02-16 16:29:03.702 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
tr-064.0 | 2021-02-16 16:29:03.018 | warn | (21423) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2021-02-16 16:29:03.016 | error | (21423) ~
tr-064.0 | 2021-02-16 16:29:03.015 | error | (21423) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2021-02-16 16:29:03.015 | error | (21423) ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2021-02-16 16:29:03.014 | error | (21423) ~
tr-064.0 | 2021-02-16 16:29:03.013 | error | (21423) Error: connect ETIMEDOUT 192.168.188.1:49000 - {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"192.168.188.1","port":49000}
host.raspberrypi | 2021-02-16 16:29:02.513 | info

**Comment by Apollon77** [comment]
The fritzbox is not responing ... Are all settings correct? Access activated in fritzbox?

**Comment by JogiBarbarski** [comment]
Hallo, IP und Passwort stimmen. In der FritzBox unter Netzwerkeinstellungen ist der Harken gesetzt.Heimnetzfreigaben
Zugriff für Anwendungen zulassen
Diese Einstellung ermöglicht Anwendungen, Einstellungen der FRITZ!Box zu lesen und zu bearbeiten. Dazu gehören beispielsweise FRITZ!App Fon für Smartphones, das FRITZ!Box AddOn für Internet Browser oder ein Einrichtungprogramm Ihres Diensteanbieters. Die Übertragung erfolgt nach dem Standard TR-064.
Für den Zugriff muss die Anwendung sich an der FRITZ!Box anmelden. Unter "System > FRITZ!Box-Benutzer" verwalten Sie die zugehörigen Anmeldedaten. Um eine Anwendung über das Internet anzumelden, muss ein FRITZ!Box-Benutzer mit Erlaubnis für den Zugang aus dem Internet genutzt werden.
Statusinformationen über UPnP übertragen
Über Universal Plug & Play (UPnP) werden im Heimnetz Statusinformationen der FRITZ!Box zum Netzwerkstatus und zu Portfreigaben bereitgestellt. Die Funktion hat keinen Einfluss auf Sicherheitseinstellungen der FRITZ!Box.

**Comment by Apollon77** [comment]
Effektuv bedeutet "ETIMEDOUT 192.168.188.1:49000" das der Adapter keine Netzwerkverbindung zur fritzbox unter der IP und dem Upnp Port 49000 öffnen kann ...

**Comment by JogiBarbarski** [comment]
Und was könnte ich da tun? Im iobroker oder auf der Fritz!Box?

**Comment by JogiBarbarski** [comment]
Bleibt alles das gleiche. Egal was ich veränder. Hab den Adapter auch mal gelöscht und neu geladen. Fehler bleibt der gleiche.
host.raspberrypi | 2021-02-16 17:36:59.236 | info | Adapter system.adapter.tr-064.0 neu starten, weil aktiviert -- | -- | -- | -- host.raspberrypi | 2021-02-16 17:36:59.232 | Fehler | Instanz system.adapter.tr-064.0 beendet mit Code 1 (JS_CONTROLLER_STOPPED) tr-064.0 | 2021-02-16 17:36:58.527 | warnen | (32047) Beendet (JS_CONTROLLER_STOPPED): Schwerwiegender Fehler. Es kann keine Verbindung zu Ihrer FritzBox hergestellt werden. tr-064.0 | 2021-02-16 17:36:58.526 | Fehler | (32047) ~ tr-064.0 | 2021-02-16 17:36:58.525 | Fehler | (32047) ~~ Wenn Konfiguration, Netzwerk, IP-Adresse usw. in Ordnung sind, versuchen Sie, Ihre FritzBox neu zu starten tr-064.0 | 2021-02-16 17:36:58.525 | Fehler | (32047) ~~ Schwerwiegender Fehler. Es kann keine Verbindung zu Ihrer FritzBox hergestellt werden. tr-064.0 | 2021-02-16 17:36:58.524 | Fehler | (32047) ~ tr-064.0 | 2021-02-16 17:36:58.523 | Fehler | (32047) Fehler: connect ETIMEDOUT 192.168.188.1:49000 - {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"192.168.188.1","port":49000}

**Comment by Apollon77** [comment]
Ich kann Dir da wenig helfen versuch doch mal im Forum zu suchen bzw dort zu fragen

**Comment by JogiBarbarski** [comment]
ok danke für die Mühe.

**Comment by JogiBarbarski** [comment]
Hallo 
Noch eine Info. Ich habe es hinbekommen. Adapter läuft. Und zwar bin ich vom Raspi in die Config gegangen und habe da unter WLAN nochmal DE angewählt. Jetzt geht es. Dankeschön für eure Arbeit die ihr da leistet um uns das Leben im Alltag zu erleichtern . Viele Grüße Jörg Barbarski

**Comment by Apollon77** [comment]
Danke für die Rückmeldung!
