### ISSUE TITLE
State: tr-064.0.states.ab arbeitet nicht

### ISSUE THREAD

**Issue by Lucifor1976** [iobroker-community-adapters/ioBroker.tr-064#218]
**Describe the bug**  
Das Einschalten des AB über diesen State funktioniert, das Abschalten nicht. Hatten wir ein paar Versionen vorher bereits auch.

**Expected behavior**  

**Screenshots & Logfiles**  

tr-064.0 | 2021-02-20 11:49:18.959 | debug | (5291) updateDevices
-- | -- | -- | --
tr-064.0 | 2021-02-20 11:49:18.958 | debug | (5291) in updateAll
tr-064.0 | 2021-02-20 11:49:13.470 | debug | (5291) forEachConfiguredDevice
tr-064.0 | 2021-02-20 11:49:13.470 | debug | (5291) updateDevices
tr-064.0 | 2021-02-20 11:49:13.469 | debug | (5291) in updateAll
tr-064.0 | 2021-02-20 11:49:10.348 | debug | (5291)  State changed: tr-064.0.states.ab =  {"val":"0","ack":false,"ts":1613818150346,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1613818150346}
tr-064.0 | 2021-02-20 11:49:07.863 | debug | (5291) forEachConfiguredDevice
tr-064.0 | 2021-02-20 11:49:07.863 | debug | (5291) updateDevices
tr-064.0 | 2021-02-20 11:49:07.861 | debug | (5291) in updateAll
tr-064.0 | 2021-02-20 11:49:02.301 | debug | (5291)  State changed: tr-064.0.states.ab =  {"val":"1","ack":true,"ts":1613818142298,"q":0,"from":"system.adapter.tr-064.0","user":"system.user.admin","lc":1613818142298}
tr-064.0 | 2021-02-20 11:49:02.220 | debug | (5291) forEachConfiguredDevice
tr-064.0 | 2021-02-20 11:49:02.220 | debug | (5291) updateDevices
tr-064.0 | 2021-02-20 11:49:02.218 | debug | (5291) in updateAll
tr-064.0 | 2021-02-20 11:49:01.597 | debug | (5291)  State changed: tr-064.0.states.ab =  {"val":1,"ack":false,"ts":1613818141593,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1613818141593}

**Versions:**  
 - Adapter version: 4.2.6
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: Debian

**Additional context**

**Comment by Apollon77** [comment]
Please send a boolean!! You send strings that have a special meaning; in fact the last try with the number 1 should have worked ... or ?! Was ist bei abIndex gesetzt? Das ist der Index des ABs
