### ISSUE TITLE
Fritzbox Adapter funktioniert nicht

### ISSUE THREAD

**Issue by guthubps1304** [iobroker-community-adapters/ioBroker.tr-064#220]
habe via Github URL installiert - Adapter funzt aber leider nicht - siehe Log:
ich komme aber via Adapter auf die Fritzbox UI, der Adapter findet aber weder die FB noch fir angeschlossenen Geräte.

tr-064.0 | 2021-02-26 15:21:30.122 | warn | (6036) Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
-- | -- | -- | --
tr-064.0 | 2021-02-26 15:21:30.121 | error | (6036) ~
tr-064.0 | 2021-02-26 15:21:30.121 | error | (6036) ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2021-02-26 15:21:30.121 | error | (6036) ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2021-02-26 15:21:30.120 | error | (6036) ~
tr-064.0 | 2021-02-26 15:21:30.120 | error | (6036) Error: read ECONNRESET - {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
tr-064.0 | 2021-02-26 15:19:42.185 | info | (6036) starting. Version 4.2.6 in /opt/iobroker/node_modules/iobroker.tr-064, node: v12.21.0, js-controller: 3.2.16

**Comment by Apollon77** [comment]
ECONNRESET bedeutet das die Fritzbox die Verbindung abgelehnt bzw zurückgesetzt hat. Hast Du alles korrekt (siehe Readme) eingerichtet und die nötigen Features aktiviert?

**Comment by guthubps1304** [comment]
Danke für das Feedback, lustigerweise hat nach einem Reboot der Fritzbox alles funktioniert, echt komisch; aber IT verschluckt sich halt mal.
