### ISSUE TITLE
V4.2.8 - html template fine, but calllists get no update any more..

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.tr-064#224]
since V4.2.7 or .6 ? the calllists are not updated any more. 
Was fixed with 4.2.5

**Comment by Apollon77** [comment]
Please try 4.2.8

**Comment by Apollon77** [comment]
4.2.6 was exactly that what you tested in https://github.com/iobroker-community-adapters/ioBroker.tr-064/issues/212 ... 4.2.8 is just an optimization

**Comment by Ilovegym66** [comment]
hmm I know, with the tests the objects are updated, and everything was fine for me. 
Now in 4.28 ( updated some minutes before from github) the objects where written, but the callerlists not updated in there.
Same with the object "count" - that stays on the same number, and I call me again and again with different options (missed, inbound, outbound, and summary not updated.. ) doesnt matter what I do..

I know its a topic with a nightmare... no high priority on this, please. We have other issues and tasks.. :-)

**Comment by Apollon77** [comment]
Can I get a debug log pelase? There was changed NOTHING on other calllist stuff

**Comment by Ilovegym66** [comment]
email with debuglog is send out. I know the difference, AVM released FritzOs7.25, we tested it with a labor 7.24xxx .. should be the reason..??

**Comment by Apollon77** [comment]
no idea if AVM changed sometjhing here

**Comment by Ilovegym66** [comment]
I reboot in the night the router and the iobroker lxc and make some tests tomorrow again. feedback followes asap.
