### ISSUE TITLE
callmonitor inbound callerName und caller Zeitstempel wird nicht aktualisiert

### ISSUE THREAD

**Issue by testit2020** [iobroker-community-adapters/ioBroker.tr-064#231]
`v4.2.11`
Der json-Wert unter **tr-064.0.callmonitor.inbound.json** wird bei einem Anruf direkt aktualisiert. Der zugehörige **tr-064.0.callmonitor.inbound.callerName** und **caller** werden aber nicht aktualisiert, wenn die Nummer bzw der Anrufer schon in den Objekten (caller, callername) stehen.

**Comment by Apollon77** [comment]
Ja da sist "as designed". Der Adapter schreibt nur Werte wenn Sie geändert werden. Wenn es darum geht einen "trigger" zu haben dann am besten das json nutzen weil das immer aktualisiert wird
