### ISSUE TITLE
Calllist - incoming call dont change anything..

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.tr-064#236]
Hi,
we tested the calllist functions, but I dont test it with incoming calls, only with outgoing. 
With incoming calls the callists are not changed. Can you take a look, please?

**Comment by Apollon77** [comment]
Hä? More details and logs please. What exactly is not working? Was it never working or did it start after a reboot/udate of FB?

**Comment by Ilovegym66** [comment]
Ja! Error found - I answer a incoming call via FritzFon-App, and this is not recognized via tr-064...  
Incoming calls, that are answered with a normal phone on the fritzbox, are fine.
I dont think, that this is a issue for the adapter, I think this is designed in the fritzbox software.
And I'd answered the call very fast, from ring to collect are 1sec. Let us close this.
