### ISSUE TITLE
htmlTemplate ändert sich immer wieder

### ISSUE THREAD

**Issue by hgschiller** [iobroker-community-adapters/ioBroker.tr-064#238]
Ich weiss nicht ob ich es falsch mache oder ob es ein Fehler ist. Unter dem Datenpunkt tr-064.0.calllists.htmlTemplate.htmlTemplate kann man ja die Vorlage bzw. das Aussehen der html Datenpunkte ändern. Ich kann dort das Aussehen super ändern, aber nach einem Restart des Adapters, steht da immer wieder der Initial Wert drin und ich muss ihn wieder überschreiben. 

---

**System data:**

Distribution: Raspbian GNU/Linux
Architecture: arm
Platform: linux
Model: ARMv7 Processor rev 3 (v7l)
RAM: 7.69 GB
Node.js: v12.22.1
NPM: 6.14.12
Model: ARMv7 Processor rev 4 (v7l)
RAM: 924.21 MB
Node.js: v12.22.1
NPM: 6.14.12
Model: ARMv7 Processor rev 4 (v7l)
RAM: 924.21 MB
Node.js: v12.22.1
NPM: 6.14.12
JS-Controller (1): 3.2.16
Admin: 4.2.1
TR-064: 4.2.11

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Bitte Debug Log aktivieren und bereitstellen vom Adapterstart. An sich sollte der Wert des States gelten und übernommen werden

**Comment by hgschiller** [comment]
[tr-064.log.gz](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6301876/tr-064.log.gz)

**Comment by hgschiller** [comment]
Ich sehe zwar auch im Log, die Zeile:
2021-04-13 08:59:20.692  - [34mdebug[39m: tr-064.0 (15679) Set Template: "<!-- GSVariables:
(habe das GS mit rein geschrieben um schnell zu sehen ob es das neue oder das alte ist)
Aber aus irgendwelchen Gründen, ist nachher der Initial wieder dort drin.

**Comment by Apollon77** [comment]
Ok, dann itte nichmal GitHub version installieren, manuell neu starten und log von den Starts und so bis es wieder passiert :-)

**Comment by hgschiller** [comment]
So ich hoffe ich habe es richtig gemacht. Habe erst einmal die Instanz und den Adapter gelöscht und dann über Installation von GitHub neu installiert und zwar "tr-064 [iobroker-community-adapters]"
Habe dann erst die Instanz konfiguriert und gestartet. Dann den Datenpunkt 
tr-064.0.calllists.htmlTemplate.htmlTemplate 
auf den Wert:
`<!-- GSVariables: id, type, caller, called, callednumber, name, numbertype, device, port date, duration, count, path.to use with %() e.g. %(date) --> <div> 	<table> 		<th>Zeitpunkt</th><th>Name</th><th>Nummer</th><th>Anschluss</th> 		<!!--Entry--><tr><td>%(date)</td><td>%(name)</td><td>%(caller)</td><td>%(callednumber)</td></tr><!!--EntryEnd--> 	</table> </div>`
gesetzt.

Ab hier läuft es erst mal gut. Dann die Instanz gestoppt, Log auf debug gestellt und Instanz neu gestartet.
Jetzt steht wieder der alte Wert bzw. der Inital Wert drin.
Hier der Log:
[tr-064.log.gz](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6319029/tr-064.log.gz)

**Comment by Apollon77** [comment]
Ok, next try please ...  grmpf

**Comment by hgschiller** [comment]
Erst einmal Danke, das du am Thema bleibst.
Meine Frage ist, ob ich es auch richtig mache um die neue Version runter zu laden. Ich lösche alles, also Instanz und Adapter und gehe dann über 
![grafik](https://user-images.githubusercontent.com/78852559/114981711-b25e4800-9e8e-11eb-89b4-30b5b3f15928.png)
und installiere den Adapter. Danach lege ich die neue Instanz an. 
Wenn das so richtig ist, dann habe ich immer noch das Problem.
[tr-064.log.gz](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6322988/tr-064.log.gz)

**Comment by Apollon77** [comment]
A sich sollte löschen niocht nötig sein... "einfach" drüberinstallieren über den "Custom install" dialog ist korrekt

**Comment by Apollon77** [comment]
Ok, dann hab ichs glaub ich gefunden ... hoffentlich letzter Versuch :-)

**Comment by hgschiller** [comment]
Perfekt !
Vielen Dank jetzt funktioniert es. Habe jetzt mehrfach restartet und so, aber der Inhalt ändert sich jetzt nicht mehr.
Issue kann geschlossen werden.
