### ISSUE TITLE
Wrong types with new js-contoller 3.3.7

### ISSUE THREAD

**Issue by MK-66** [iobroker-community-adapters/ioBroker.tr-064#246]
Hello, i get following log info messages with the new js-controller 3.3.7:

```
State value to set for "tr-064.0.callmonitor.lastCall.id" has to be type "number" but received type "string"
State value to set for "tr-064.0.callmonitor.lastCall.caller" has to be type "number" but received type "string"
State value to set for "tr-064.0.callmonitor.connect.id" has to be type "number" but received type "string"
State value to set for "tr-064.0.callmonitor.connect.caller" has to be type "number" but received type "string"
```

Hope this info helps to fix wrong types in TR-064 Adapter.

**Comment by DocGame69** [comment]
Ich wollte mal Nachfragen ob Hoffnung auf Behebung des Fehlers besteht.
Jeder 2 Adapter bringt nach dem JS-Controller Update diese Meldung.
Habe die meisten Adapter schon von Info auf Error gestellt. Das kann ja aber auf dauer nicht die Lösung sein, da ich ja auch wissen will was mein System so macht.

**Comment by Apollon77** [comment]
Ja kommt noch, ich arbeite gerade eine lange liste ab ...

**Comment by sokrates-sith** [comment]
ich schließe mich an :) wäre super hier eine lösung zu bekommen

**Comment by Apollon77** [comment]
Can you please delete the affected ojects in Admin and restart the adapter to let him recreate the objects. Error then gone or still there?

**Comment by MK-66** [comment]
@Apollon77 
I have now installed the adapter from Github and then deleted approx. 10 data points (objects), where the messages regarding the wrong type came.

However, these data points are not created again when the adapter is restarted, but apparently only after a call has been made. After that, however, it looks as if the messages regarding the wrong type have disappeared. 

So in my eyes it looks like everything is fine now with the adapter and the new js-controller.
