### ISSUE TITLE
Verbindungsstörung zwischen Adapter und FritzBox

### ISSUE THREAD

**Issue by raschy** [iobroker-community-adapters/ioBroker.tr-064#268]
[Log_Auszug_tr-064_2021_0626.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6721927/Log_Auszug_tr-064_2021_0626.txt)
Nach meiner Beobachtung verliert der Adapter die Verbindung zur FB und signalisiert somit keine Telefonereignisse im ioB. Nach einem Neustart des Adapters funktioniert alles. Ich habe den Adapter mal auf Silly gestellt um möglichst viel mitzubekommen. Hier das Log über zwei Anrufe:

Alle späteren Anrufe wurden nicht mehr registriert. Nächster Versuch wäre jetzt, den Adapter alle 30 Minuten neu zu starten und dann - je nach Erfolg - die Zeit stufenweise hochfahren.

**Comment by Apollon77** [comment]
Ojk, bitte GitHub version installieren, habe noch zwei Logs in Debug Modus hinzugefügt um das Socket besser zu sehen. Also an sich sieht es eher so aus als ob die FB keine Daten mehr auf das callonitor socket sendet.

Bitte neues Debug Log vo Adapterstart und solchen Aktionen

**Comment by Rainier55** [comment]
Habe heute morgen die gepatchte Version von Github installiert. Seit ca. 9:17 gab es keine Auffälligkeit -  Adapter ist konstant verbunden, Anrufe werden sofort im ioB angezeigt.
Im Log ist für mich auffällig, dass 'Request Calllist JSON' nach meinem dafürhalten mehrfach (10:56 2x, 11:55 2x, 12:33 2x, 13:19 1x + 3x) abgefragt wird. Werden daher die html-Ausgaben mehrfach erzeugt? Ich warte weiter auf einen möglichen "Aussetzer".
[Log_Auszug_tr-064_2021_0628.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6726722/Log_Auszug_tr-064_2021_0628.txt)

**Comment by Rene5555** [comment]
Habe heute morgen die gepatchte Version von Github installiert. Seit ca. 9:17 gab es keine Auffälligkeit - Adapter ist konstant verbunden, Anrufe werden sofort im ioB angezeigt.
Im Log ist für mich auffällig, dass 'Request Calllist JSON' nach meinem dafürhalten mehrfach (10:56 2x, 11:55 2x, 12:33 2x, 13:19 1x + 3x) abgefragt wird. Werden daher die html-Ausgaben mehrfach erzeugt? Ich warte weiter auf einen möglichen "Aussetzer".
[Log_Auszug_tr-064_2021_0628.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/6726827/Log_Auszug_tr-064_2021_0628.txt)

**Comment by GermanBluefox** [comment]
Es ist nicht 2 mal, sondern "ALL" und "MISSED".

**Comment by Apollon77** [comment]
It is the same ... rason is that it seems that callmonitor.lastCall.timestamp was written multiple times short after each other and so the same update was triggered - maybe also because of testing like let it ring shortly and hand up or such. I now added a 100ms delay for this case which should be acceptable to maybe optimize such multiple calls. Please check GitHub version. Restart adapter manually after installing

**Comment by Rene5555** [comment]
@GermanBluefox Danke für die Aufklärung, für mich sehen beide Requests gleich aus und bringen auch, wenn ich die URL im Browser absetzte, die gleiche XML-Datei.

**Comment by Apollon77** [comment]
Update ist drauf

**Comment by Rene5555** [comment]
Update ist gemacht. Ich hab noch etwas gefunden: 

2021-06-28 17:13:49.506 | info | State value to set for "tr-064.0.callmonitor.lastCall.extension" has to be type "number" but received type "string"

**Comment by Apollon77** [comment]
Extension fixed on github

**Comment by Rene5555** [comment]
Gerade 22:01 versucht, einen Anruf zu machen - Adapter bleibt taub. Zwischen 17:14 und 22:04 Uhr nur die 10sekündlichen Debug-Ausgaben - aber kein Hinweis auf irgendeinen Fehler.

**Comment by Apollon77** [comment]
Auch nix in "debug" Loglevel? Wenn nein, dann ehrlich ,... keine Ahnung was mit deienr FB ist ... Mal rebooten?

**Comment by Rene5555** [comment]
@Apollon77 
Adapter steht auf silly, im Log ist nichts zu sehen was auf einen Verbindungsabbruch hinweist.

2021-06-29 09:11:56.917  - debug: tr-064.0 (2252) in updateAll
2021-06-29 09:11:58.414  - debug: tr-064.0 (2252) setting 0 enable=true
2021-06-29 09:11:58.414  - debug: tr-064.0 (2252) setting 1 enable=true
2021-06-29 09:11:58.415  - debug: tr-064.0 (2252) setting 2 enable=false
2021-06-29 09:11:58.415  - debug: tr-064.0 (2252) setting 3 enable=true
2021-06-29 09:11:58.415  - debug: tr-064.0 (2252) setting 4 enable=true

Ich kann die FB gerne mal rebooten - nur: wenn ich allein den Adapter neu starte, läuft sofort wieder alles.

**Comment by Apollon77** [comment]
> wenn ich allein den Adapter neu starte, läuft sofort wieder alles.

naja scheinbar hört die FB auf bei bestehender callmonitor-Verbindung Daten zu senden! Es gibt Logik für reconnect wenn Verbindung getrennt wird und sowas - aber wenn die Verbindung ok ist dann kann der Adapter ja nicht vermuten das es kaputt gegangen ist.

**Comment by Rene5555** [comment]
Das hört sich absolut logisch an. Ich werd mal mit den Adapter-Neustarts anfangen. Aktuell bin ich seit gestern 20:00 im Stundentakt - werd dann langsam hochschrauben. Dennoch- Danke für die Zeit und Mühe.

**Comment by funknerGER** [comment]
> Das hört sich absolut logisch an. Ich werd mal mit den Adapter-Neustarts anfangen. Aktuell bin ich seit gestern 20:00 im Stundentakt - werd dann langsam hochschrauben. Dennoch- Danke für die Zeit und Mühe.

Ich habe das identische Problem. Mit welchem Intervall der Neustarts läuft dein Adapter korrekt?
Oder hast du noch eine andere Möglichkeit gefunden, dass der Adapter zuverlässig funktioniert?

**Comment by Apollon77** [comment]
AM Ende könnte man ggf nur hingehen und generell nach Zeit X die Verbindung erneuern ... aber am ende seid Ihr jetzt 2 von mehreren tausend usern mit so einem Problem ...

**Comment by Rene5555** [comment]
@funknerGER Ich habe das Neustart-Intervall auf eine Stunde belassen. Nur zu Info für @Apollon77: Ich habe einen zweiten Callmonitor mit einem esp8266 aufgebaut. Der läuft seit Wochen ohne Verbindungsabbruch. Der sendet aber auch in regelmäßigen Abständen "client.write("x"); // Send dummy data to "refresh" connection state". Vielleicht wäre das eine Lösung des Problems, das nur zwei Leute haben.

**Comment by Apollon77** [comment]
Ich hab schon gegoogelt was amn ggf als PING/PONG nutzen könnte. hast Du das "x" irgendwo gefunden oder einfach versucht?

**Comment by guergen1** [comment]
Ich muss meinen tr-Adapter auch im Stundentakt neu starten sonst geht nix mehr

**Comment by Rene5555** [comment]
Ich habe meine "Weißheit" hierher: Copyright (C) 2014 by Tobias Link - (https://github.com/ranger81/fritzbox-callmonitor).
[Jetzt sind wir schon zu dritt]

**Comment by Apollon77** [comment]
Aaahja ... alsoalle 10s ... na dann versuchen wir das doch mal :-)

**Comment by manoloxxl** [comment]
Hab das gleiche Problem. Bei euch hilft nur der stündliche Adapterneustart?
