### ISSUE TITLE
Dauer des internen Anrufes über Türsprechanlage beträgt immer nur 15 Sekunden

### ISSUE THREAD

**Issue by m50434** [iobroker-community-adapters/ioBroker.tr-064#275]
Hi,
ich habe unter Fon1 eine "Türsprechanalge" angelegt, die das Livebild einer Haustürkamera hinterlegt hat.

Das Signal wird an ein DECT-Telefon, dass das Livebild anzeigt, weitergeleitet (umgesetzt mit der Einstellung "Wählhilfe" in der Fritzbox), sodass ich unter Bearbeitung des States "ring" mit dem Eintrag **610 tatsächlich auch das Livebild auf meinem Fritzfon (C5) angezeigt bekomme. Das funktioniert also.

Das Problem:
Egal, welchen Parameter ich als Dauer in den ring-State schreibe, die Dauer des Anrufes beträgt nur ca. 10 bis 15 Sekunden.
Das ist natürlich zu kurz für das Anzeigen des Livebildes.
Also z.B. **610 ,40  sollte ja eigentlich den Anruf 40 Sekunden klingeln lassen. Leider bleibt es aber bei den 10 bis 15 Sekunden.

Wenn ich z.B. mein Handy auf der Fritz-App mit **622, 40 anrufe, dann klingelt es auch tatsächlich 40 Sekunden (das scheint also grundsätzlich zu klappen).

Warum klappt das nicht mit der "Türsprechanlage". Gib es da eine Idee, woran das liegen könnte. Gibt es vielleicht noch einen anderen Datenpunkt, den man dafür benutzen kann?

**Comment by Apollon77** [comment]
Bitte Debug Log vom Adapter mit so einer Aktion bzw send Kommando bereitstellen

**Comment by Apollon77** [comment]
Plesse try without a space after the comma ... does it work then?

**Comment by Apollon77** [comment]
Hm ... ok should it not be ...

In fact the code sends a call and then sends a timoeut to end the call ... and this is done with the specified number of seconds.I added debug to check that, so

Please install version from Github sdo a manual restart of the adapter and enable debug log, do such a ring and check the log. There is one logline written when "ring" starts and a second when the adapter ends the ring

**Comment by m50434** [comment]
Hi,
thanks for the fast reply.
Im on holiday right now. I will try it in a few days.

**Comment by m50434** [comment]
Hi,
Finally I could do a debug-log.

When the ring starts, there is this line:
`tr-064.0 | 2021-07-31 09:39:57.449 | debug | (30332) State changed: tr-064.0.states.ring = {"val":"**610,  60","ack":false,"ts":1627717197443,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1625914434779}`

But thats it. There is no further debug-log for a "ring-stop". 
The ring ends after round about 15 sec. (as I already descriped).

**Comment by Apollon77** [comment]
Then I assume it somehow is the fritzbox :-(

**Comment by m50434** [comment]
Hmmm.... thats a pity.

What do you think, is this assumption correct? -> https://forum.iobroker.net/topic/4749/fritzfon-klingeln-lassen-tr-64-adapter/127?_=1628440207810#

**Comment by Apollon77** [comment]
Honestly ... No idea, but if these are the "facts from testing" ... then ...
