### ISSUE TITLE
tr-064.0.devices.jsonDeviceList Device Active value false

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.tr-064#279]
`v4.2.14`
FritzBox Cable 6591, v7.27
![image](https://user-images.githubusercontent.com/84818934/126847012-b88cfe76-2558-4f61-8ca6-7de1d94cf841.png)

![image](https://user-images.githubusercontent.com/84818934/126847027-8adf8b70-d861-44f6-b3af-bff653c4dbae.png)

[{"active":true,"ip":"192.168.178.58","name":"MICHAEL-S8","mac":""...

Device Active is shown as "false" in the list. This is correct, but in the jsondeviceList it is shown as Active true, that is wrong for that time.
Sometimes if status active is changed, the jsondevicelist are not updated. (When active goes to false)

**Comment by Apollon77** [comment]
Pleas eprovide a debug log from such a case. Code wise the hsonDeviceList should get updated after all other states ...
