### ISSUE TITLE
Adapter Dont work anymore

### ISSUE THREAD

**Issue by tommyMX** [iobroker-community-adapters/ioBroker.tr-064#295]
Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500 - {"code":500}

**Comment by Apollon77** [comment]
then your fritzbox is returning this error. try restarting fritzbox ... else: provide kore infos in what you got before it stopped working

**Comment by tommyMX** [comment]
I restarted already 

put my admin account and password and the correct ip Adress

I only installed the new admin5, and all new controllers and iobroker version 

I found in forum that somebody means with the new fritz Box Version doesn’t work

**Comment by tommyMX** [comment]
07.27 

Cable 6490

**Comment by Apollon77** [comment]
No other report so far. Using the admin user might not be the best idea ... create an own user, try to deactivate the tr-064 setting, save, reboot and activate again

**Comment by tommyMX** [comment]
okay its working now thank you

**Comment by Apollon77** [comment]
And what did the trick?

**Comment by tommyMX** [comment]
I made a new user abs restart the adapter
