### ISSUE TITLE
State value to set for "tr-064.0.callmonitor.outbound.caller" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by Grothesk242** [iobroker-community-adapters/ioBroker.tr-064#312]
Wrong value type delivered: 

`State value to set for "tr-064.0.callmonitor.outbound.caller" has to be type "number" but received type "string"`

**Comment by Apollon77** [comment]
Bitte mal Objekt löschen und Adapter neu starten. Kommts danach immer noch?

**Comment by Grothesk242** [comment]
Sorry, natürlich... 
Hatte die Objekte schon mal vor längerer Zeit komplett gelöscht. Jetzt nochmal gezielt den einen Datenpunkt, funktioniert jetzt.
