### ISSUE TITLE
ring state doesn't work

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064#32]
_From @cm86 on January 9, 2019 23:16_

Hallo,
ich möchte gerne des Ring Sie des Adapters nutzen...
Hier gebe ich **610 ein allerdings passiert nix...

--> Wählhilfe ist aktiviert in der Fritzbox
--> Adapter-Version 0.4.18
--> Fritzbox 7490 OS 07.01
--> der Befehl (Command) 
`{ "service":"urn:dslforum-org:service:X_VoIP:1", "action": "X_AVM-DE_DialNumber", "params": { "NewX_AVM-DE_PhoneNumber": "**610#" }}` 
funktioniert auch nicht...

Im log der Fritzbox ist auch nix zu finden...

Hat jemand noch einen Lösungsansatz für mich?!

Mit freundlichen Grüßen
Chris

_Copied from original issue: soef/ioBroker.tr-064#86_

**Comment by Apollon77** [comment]
@cm86  Details bitte. Um was genau geht es hier?

**Comment by Apollon77** [comment]
@cm86 Bitte nochmals versuchen mit aktueller GitHub Version und Debug log posten/senden an iobroker@fischer-ka.de

**Comment by cm86** [comment]
entschuldige, aber ich nutze iobroker nicht mehr. Somit kann ich den Fehler auch aktuell nicht nachstellen.

**Comment by FabiVerFranzt** [comment]
@Apollon77 bei mir wird nach der Nutzung der folgende Fehler im Log ausgegeben.

`(28359)Ring Error: Error: sendSOAPActionRequest Error  action=X_AVM-DE_DialNumber  serviceType=urn:dslforum-org:service:X_VoIP:1: 500`

**Comment by Strobelix80** [comment]
Hast du auch die Wählhilfe in der Fritzbox aktiviert? Sonst kommt genau dieser Fehler

**Comment by FF-17** [comment]
@Strobelix80 Korrekt, wenn die Wählhilfe deaktiviert ist kommt der o.g. Fehler. Nach der Aktivierung kommt kein Fehler, die Nebenstellle klingelt aber trotzdem nicht. Mit der Version 3.1.4 getestet.
