### ISSUE TITLE
tr-064.0.states.command LOG der Fritzbox einlesen

### ISSUE THREAD

**Issue by Cabohne** [iobroker-community-adapters/ioBroker.tr-064#320]
Hi!
Ich hätte gerne die LOG-Informationen meiner Fritzbox im ioBroker verfügbar.
Meine Idee ist, dass ich die LOG-Informationen über den Command-Datenpunkt erfrage und dann im commandResult-Datenpunkt erhalte.
Leider verstehe ich die Möglichkeiten vom TR-064-Command-Datenpunkt noch nicht ganz.
Das Beispiel aus der Anleitung (Anrufbeantworter aktivieren und deaktivieren) funktioniert bei mir indem ich in den Command-Datenpunkt Folgendes schreibe:

`{"service": "urn:dslforum-org:service:X_AVM-DE_TAM:1","action": "SetEnable", "params": {"NewIndex": "0","NewEnable": "1"}}`
bzw.:

`{"service": "urn:dslforum-org:service:X_AVM-DE_TAM:1","action": "SetEnable", "params": {"NewIndex": "0","NewEnable": "0"}}`

... so weit so gut.

Nachdem ich mich mit der AVM-Schnittstellenbeschreibung (DeviceInfo - [Link zur PDF](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/deviceinfoSCPD.pdf)) auseinandergesetzt habe, wäre (meinem Verständnis nach) für die Abfrage der LOG-Informationen folgendes Kommando nötig:

`{"service": "urn:DeviceInfo-com:serviceId:DeviceInfo1","action": "GetDeviceLog", "params": {"NewDeviceLog": "DeviceLog"}}`

Das commandResult lautet daraufhin aber einfach nur {}.

Im ioBroker.net-Forum habe ich dazu bereits einen Eintrag gefunden: [Link ins Forum](https://forum.iobroker.net/topic/44730/solved-fritz-box-ereignisse-bzw-log-auslesen?_=1640010786909&lang=de). Mir ist allerdings nicht klar, warum dort z.B. "urn:dslforum-org:service:DeviceInfo:1" steht?!
Übernehme ich das Kommando wie im Forum beschrieben, lautet das Ergebnis bei mir nur: {"NewDeviceLog": ""}
Die tatsächlichen LOG-Einträge erscheinen also ebenfalls nicht.

Würde mich sehr über Hilfe freuen und wenn es letztendlich klappt, die LOG-Einträge im commandResult-Datenpunkt zu erhalten.

Vielleicht hilft auch eine Erklärung der Syntax weiter und Verweise zwischen der AVM-Schnittstellenbeschreibung und den String-Parametern (service, action, params).

Letztendlich wäre es natürlich super, wenn das Beispiel in der Anleitung dieses Adapters vielleicht erweitert werden könnte und weitere Beispiele aufgeführt werden, die nicht nur den Anrufbeantworter betreffen.

Vielen Dank vorab, für weitere Unterstützung!
MfG

**Comment by Cabohne** [comment]
Zur Info ... ich habe mich in der Zwischenzeit auch an den AVM Entwicklungssupport gewandt und grundsätzlich ist wohl die im Form beschriebene Vorgehensweiße korrekt:

> Im ioBroker.net-Forum habe ich dazu bereits einen Eintrag gefunden: [Link ins Forum](https://forum.iobroker.net/topic/44730/solved-fritz-box-ereignisse-bzw-log-auslesen?_=1640010786909&lang=de). Mir ist allerdings nicht klar, warum dort z.B. "urn:dslforum-org:service:DeviceInfo:1" steht?!
> Übernehme ich das Kommando wie im Forum beschrieben, lautet das Ergebnis bei mir nur: {"NewDeviceLog": ""}
> Die tatsächlichen LOG-Einträge erscheinen also ebenfalls nicht.

Dass die tatsächlichen LOG-Einträge nicht erscheinen liegt daran, dass die Zustandsvariable "DeviceLog" seitens AVM (also Fritzbox) nicht mit Inhalt gefüllt wird. So wurde es mir jedenfalls vom AVM Entwicklungssupport bestätigt. Hier ein Auszug aus der Mail:

> Dieses Verhalten   
> _Die Zustandsvariable „DeviceLog“ liefert mir aber nur ein leeres Ergebnis._
> ist aktuell intentional. 
> Die hier ursprünglich vorgesehenen Optionen werden absehbar mit dem nächsten Release von FRITZ!OS (zur Orientierung: Ende Q2/22) dokumentiert zur Verfügung stehen. Stand heute lässt sich noch nicht absehen, ob dann alle in der Benutzeroberfläche angezeigten Ereignisse über TR-064 abrufbar sein werden oder ob es sich um einen ausgewählten Teil der Ereignisse handeln wird. 


Inzwischen bin ich mir sicher, dass es sich also nicht um ein Issue des TR-064-Adapters handelt und werde das Issue dann hiermit auch abschließen.

**Comment by Apollon77** [comment]
Vielen Dank für die Infos und Rückmeldung!
