### ISSUE TITLE
Wlan switches not working on FritzBox 7590 v7.29

### ISSUE THREAD

**Issue by MichaelEuropa** [iobroker-community-adapters/ioBroker.tr-064#327]
Since few weeks the switches
wlan24, wlan50 and wlanGuest have no effect, when changed. 
Other switches like reconnectInternet or wps are still working as well as call lists.
For example wlanGuest is not switching off even if the state was changed directly in ioBroker objects.
There are no ack coming back from Fritz!Box.
Restart of adapter as well as reboot of FB or ioBroker doesn't change anything.

What has changed: 
- FB was updated to v7.29
- JS-Controller was updated to 3.3.22
- Node.js was updated to v14.18.2
(Cannot exactly say when switches stopped working)

TR-064 adapter version is 4.2.14

--Screenshots & Logfiles--  
Sorry Newbie. :-( 
How to get the log file from tr-064? No errors or warnings in ioBroker protocols.

**Comment by Apollon77** [comment]
Please create a debug level logfile: Admin - Instances - enable expertmode - expand tr-064.0 nd change loglevel. Adapter then restarts. grab log of a try to change these states from logfile on difk in /opt/iobroker/logs/...
