### ISSUE TITLE
FRITZ!OS: 07.39-94937 BETA keine vollständige Funktionalität

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.tr-064#363]
Bei der Beta der Fritzbox 07.39-94937 funktioniert die Anruferliste nicht mehr, inbound,outbound etc. wird nicht mehr aktualisiert.
Die Objekte in "Devices" funktionieren weiterhin.

Callmonitor ist aktiviert, habe den Support bei Fritzbox kontaktiert und warte dort auf eine Antwort.

**Comment by Apollon77** [comment]
Na dann warten wir mal auf die Antwort

**Comment by Grothesk242** [comment]
Datenpunkte einmal löschen. Die Datenpunkte füllen sich bei Aktionen des Telefons wieder entsprechend mit Werten.
