### ISSUE TITLE
Fehler 500 bei WLAN-Gerät

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.tr-064#372]
Durch das Hinzufügen meines neuen Laptops zur Fritzbox bekomme ich aktuell alle 10 Sekunden eine "Code 500" Infomeldung im Log.
Das Laptop ist in der Fritzbox erreichbar und kann auch im Adapter erreichbar angezeigt werden.

Die Meldung erscheint immer, auch wenn ich das Gerät, das Laptop aus dem Adapter und dem Datenbaum entferne.

Was mich dabei wundert, ist der Zusammenhang zum dsl-forum in der Meldung.
Wo kommt das her?
Kann man die Meldung entfernen, ist das eine Meldung, die man deaktivieren kann?

Hier die Meldung, die aller 10 Sekunden erscheint:
`2022-04-18 11:47:43.739 - info: tr-064.0 (2691070) forEachConfiguredDevice: in GetSpecificHostEntry 23(Mario-PC/18:C0:4D:9B:3F:C1) device seems offline but we never saw it since adapter was started:Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}`

**Comment by Apollon77** [comment]
iese Meldung kommt an sich wenn ein Gerät per Adapter abgefragt wird was" nicht existiert" in der Fritzbox. Ggf schau mal das du vllt "Immer gleiche IP" setzt das die Fritzbox den Eintrag nicht aufräumt wenn das gerät länger aus ist

**Comment by Siggi0904** [comment]
Hi Ingo,
das Gerät (der Laptop) ist ja da, eingerichtet im IOBroker und dort auch als true dargestellt.
In der Fritzbox sind alle Geräte so eingerichtet, dass Sie nach der ersten IP-Adressvergabe dann immer die gleiche Adresse erhalten.

Kann man das irgendwie abschalten oder beheben?

**Comment by Apollon77** [comment]
Wie gesagt - deser Fehler kommt wenn die genannte IP und Mac in der Fritzbox nicht bekannt sind. Am besten mal reinschauen in de Netzwerk-Liste wenn der Fehler passiert ob und wie da alles gelistet ist. Ist die Mac auch korrekt?

**Comment by Siggi0904** [comment]
Hi,

ja, mac, IP alles korrekt.
Merkwürdig.

Ich bekomme das ja auch nicht deaktiviert.
Auch wenn die den Laptop aus dem Adapter lösche, also in den Einstellungen und im Datenbaum, bleibt die Meldung bestehen.

Danke für weitere Infos.

**Comment by Apollon77** [comment]
Dann bitte mal Debug log posten vom start und dem fehler

**Comment by Siggi0904** [comment]
Hallo Log-file in Debug-Stufe im Anhang.
Vielleicht siehst du ja was.

[Fehler tr064 mit Laptop.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/8514511/Fehler.tr064.mit.Laptop.txt)

**Comment by Apollon77** [comment]
Hi,

also im Log sieht man mario-PC in der Liste der Geräte drin als id 23 it Mac 18:C0:4D:9B:3F:C1 ...

**Comment by Apollon77** [comment]
ääähhmm ... also in dem Log ist mit "Mario-Laptop" alles i.ol ... er meckert bei "Mario-PC"!!

**Comment by Apollon77** [comment]
Für Disable Feature request bitte eigenes issue anlegen
