### ISSUE TITLE
auslesen des WlanGuestPasswords?

### ISSUE THREAD

**Issue by Reiter0303** [iobroker-community-adapters/ioBroker.tr-064#377]
hallo, 
ich habe mit @Glasfaser geschrieben und wir haben festgestellt das das Passwort nicht ausgelesen wird?
kann das jemand bestätigen?
version 4.2.16 des TR-064.0 Adapter

danke

**Comment by Apollon77** [comment]
Ich glaube so eine Frage ist im Forum besser aufgehoben als hier :-)
