### ISSUE TITLE
T64 Anrufe über Ring

### ISSUE THREAD

**Issue by bambi-arch** [iobroker-community-adapters/ioBroker.tr-064#387]
Hallo! Ich versuche verzweifelt über den Datenpunkt "ring" mein FritzTelefon anzurufen. Im Feld steht "**611". Ich habe es auch mit anderen Nummern von internen Geräten probiert, ohne Erfolg. Wenn ich die Nummer auf anderen Geräten eingebe,  klingelt das Telefon. !  Datenpunkte werden geladen.
Der Benutzer ist eingerichtet und hat folgende Berechtigungen! Adapter und Instanz auch schon gelöscht und neu installiert. Auch der Anrufmonitor ist aktiviert. Ohne Erfolg. Bitte um Hilfestellung. Danke 
![Bildschirmfoto 2022-05-23 um 13 20 35](https://user-images.githubusercontent.com/104907692/169809063-d10741e0-db4c-4ad5-b8c4-76b0dd3c260e.png)
![Bildschirmfoto 2022-05-23 um 13 21 59](https://user-images.githubusercontent.com/104907692/169809067-d3b96176-e7f1-4fd4-a68d-a989e01f45db.png)

**Comment by Apollon77** [comment]
> Es hat die Anlage des "dummy"-Telefongerät in der Firtzbox für ioBroker gefehlt. Und die Wahlhilfe nicht auf diesem Gerät. Wäre gut wenn das im Readme stehen würde.

Ok der Bahnhof ist da hinten rechts ... ;-)) Sagt mir nichts. Magst Du einen Vorschlag machen was wo in die Readme sollte?

Oder direkrt vorschlagen: Unter oben Links "Code" die README.md auswählen, auf den Stift oben rechts ... ändern und unten auf Vorschlagen klicken, dann "Create Pull Request"! :-)
