### ISSUE TITLE
feature request: Link zur Fritzbox

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.tr-064#39]
feature request:
feature request:
https://forum.iobroker.net/topic/21949/admin-als-generelles-verwaltungstool-f%C3%BCr-das-heimnetz

Ein Link wie im Forum beschrieben zur fritzbox IP  in der Instanzen-Ansicht

**Comment by bazidibavaria** [comment]
Siehe Pull-Request #147
