### ISSUE TITLE
falsche Typen

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.tr-064#390]
<html><body>

tr-064.0 | 2022-05-24 18:09:12.889 | info | State value to set for "tr-064.0.callmonitor.lastCall.caller" has to be type "number" but received type "string"
-- | -- | -- | --
tr-064.0 | 2022-05-24 18:08:40.051 | info | State value to set for "tr-064.0.callmonitor.connect.caller" has to be type "number" but received type "string"

</body>
</html>

**Comment by Apollon77** [comment]
Welche Version?

**Comment by daniel-lo** [comment]
4.2.16 (1~)

**Comment by Apollon77** [comment]
Bitte betroffene objekte mal löschen und neu anlegen lassen

**Comment by daniel-lo** [comment]
Hab den ganzen Baum weggehauen .. erstmal nichts Auffälliges .. beobachte

**Comment by padrino-x** [comment]
Gleiche Version, gleiches Problem hier.
Hab den Baum jetzt komplett gelöscht und durch Adapter Neustart neu anlegen lassen, jetzt ist wieder Ruhe...

**Comment by Apollon77** [comment]
Genau das ist aktuell die lösung: Objekte löschen
