### ISSUE TITLE
wlanGuestPassword

### ISSUE THREAD

**Issue by Aushilfsarnie** [iobroker-community-adapters/ioBroker.tr-064#398]
The wlanGuestPassword is not transmitted to the Fritzbox.

If I enter the password under wlanGuestPassword, it is not sent to the Fritzbox or not taken over by the Fritzbox,

**Versions:**  
 - Adapter version: 4.2.16
 - JS-Controller version: 4.0.23
 - Node version:  16.16.0
 - Fritzbox: 6590 Cable

**Comment by Apollon77** [comment]
Should be set ... please show a debug log when you try it

**Comment by Aushilfsarnie** [comment]
The issue is solved, sorry
