### ISSUE TITLE
Gerätesuche alles vierfach !

### ISSUE THREAD

**Issue by MSchmitt67** [iobroker-community-adapters/ioBroker.tr-064#405]
Hallo,

wenn ich aus den gefundenen Geräten im Adapter eines lösche und dann speichere verdoppelt sie die Anzahl jedes mal.
In den Objekten ist alles korrekt.
Bei der Gerätesuche werden alle Geräte vierfach angezeigt.

![123](https://user-images.githubusercontent.com/92262454/187861413-98950dfc-6d8b-4bf0-be99-8ad4c20803c8.jpg)

**Versions:**  
 - Adapter version: v4.2.16
 - JS-Controller version: 4.0.23
 - Node version:  v16.17.0
 - Bullseye

Gruß Michael

**Comment by MSchmitt67** [comment]
Hat niemand eine Idee ?

**Comment by Apollon77** [comment]
@simatec will look into this UI issue if he has time. Thanks for that!

**Comment by simatec** [comment]
@MSchmitt67 
Ich habe mich heute Vormittag deinem Issue angenommen.
Den Code habe ich geprüft und auch einige Geräte automatisch und manuell erstellt, gelöscht etc.

Leider kann ich in keine Konstellation deinen Fehler nachstellen.
Eventuell kannst du zu deinem Schritten mal ein Gif oder so erstellen.

Hier tut der Adapter genau da, was er machen soll

**Comment by Apollon77** [comment]
Please try to reproduuce with GitHub version (and yes you need to cleanup your duplicates once yourself, sorry)

**Comment by Ilovegym66** [comment]
Bei mir sind die Devices von der Fritzbox 3fach oder 4fach in der Geraetesuche des TR-064 Adapters vorhanden. Ich habe in der Fritzbox nur die UnifyDreamMachinePro, sonst keine Devices. Der Adapter zeigt die Fritzbox und die UDM jeweils 4fach und 3fach an. 
Waehle ich jeweils einmal die FB und einmal die UDM aus, speichere ab, und rufe die Config des Adapters wieder auf, sind beide Geraete doppelt in der Config des Adapters angelegt.
Das ist auch nachzuvollziehen, benutzt wird die aktuelle Git version, Node 16.17.0 undNPM8.15.0, Debian Buster im LXC.
