### ISSUE TITLE
jsonDeviceList shows inactive devices as active

### ISSUE THREAD

**Issue by Rookiestyle** [iobroker-community-adapters/ioBroker.tr-064#407]
**Describe the bug**  
All devices that I configured are listed as objects and their respective ``active`` state is correct.
The *jsonDeviceList* also lists all configured devices but shows all of them as active.

**Expected behavior**  
If a device' ``active`` state is *false*, it shall be listed as inactive in the *jsonDeviceList* as well
**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: v4.2.16
 - JS-Controller version: 4.0.23
 - Node version: v18.8.0
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Additional context**  
Maybe this part of the debug log is helpful
```
tr-064.0 | 2022-09-04 14:19:34.553 | debug | forEachConfiguredDevice: {
 "NewIPAddress":"192.168.178.52",
 "NewAddressSource":"DHCP",
 "NewLeaseTimeRemaining":"0",
 "NewInterfaceType":"Ethernet",
 "NewActive":"0",
 "NewHostName":"Tina-Laptop",
 "NewMACAddress":"A0:C5:89:42:8C:E0"
}
--
tr-064.0 | 2022-09-04 14:19:34.553 | debug | forEachConfiguredDevice: i=14 Tina-Laptop active=0
```
IP addresses are statically assigned.
I did not see anything regarding creation of *jsonDeviceList* but somehow above *active* indicator is not used.

Let me know which other information you need

**Comment by Apollon77** [comment]
Thank you for the report. "part of  the debug log" ist honestly mostly never helpful ...  Please post a full debug log. And please also post how the jsonDeviceList is looking at the same time.

**Comment by Rookiestyle** [comment]
debug log is attached, jsonDeviceList looks like that:
I configured all devices only once,guess they show up twice her because they show up twice in the instance config as well - no idea, why that's the case.
````
[
  {
    "active": true,
    "ip": "192.168.178.15",
    "name": "Drucker",
    "mac": "DC:CD:2F:6C:71:94"
  },
  {
    "active": true,
    "ip": "192.168.178.6",
    "name": "Hue",
    "mac": "EC:B5:FA:8B:1C:95"
  },
  {
    "active": true,
    "ip": "192.168.178.101",
    "name": "Receiver",
    "mac": "80:1F:02:E9:27:2E"
  },
  {
    "active": true,
    "ip": "192.168.178.52",
    "name": "Tina-Laptop",
    "mac": "A0:C5:89:42:8C:E0"
  },
  {
    "active": true,
    "ip": "192.168.178.15",
    "name": "Drucker",
    "mac": "DC:CD:2F:6C:71:94"
  },
  {
    "active": true,
    "ip": "192.168.178.6",
    "name": "Hue",
    "mac": "EC:B5:FA:8B:1C:95"
  },
  {
    "active": true,
    "ip": "192.168.178.101",
    "name": "Receiver",
    "mac": "80:1F:02:E9:27:2E"
  },
  {
    "active": true,
    "ip": "192.168.178.52",
    "name": "Tina-Laptop",
    "mac": "A0:C5:89:42:8C:E0"
  }
]
```

List of devices shown in objects is correct:
![image](https://user-images.githubusercontent.com/36454520/188322416-e261d473-9b9e-41ae-853a-0f7ca1ad13f7.png)
