### ISSUE TITLE
Nur eine Frage: Was kann ich mit dem Datenpunkt "ring" machen

### ISSUE THREAD

**Issue by CBRocker** [iobroker-community-adapters/ioBroker.tr-064#414]
Hallo,
ich habe schon viel im Internet rumgelesen, weiß aber immer noch nicht, was ich mit dem Datenpunkt "ring" anfangen kann.
Hier ist ja die Beschreibung:

Klingeln (Nummer wählen)

Wenn Sie eine interne Nummer (wie **610) verwenden, lässt der Klingelstatus dieses interne Telefon klingeln.

Bsp.: **610[,timeout]

Wenn Sie eine externe Nummer verwenden, verbindet Sie der Klingelstatus mit der externen Nummer.

Die FritzBox ruft die externe Nummer an und Ihr Standardtelefon klingelt, wenn das angerufene Telefon abgenommen wird. Das Standardtelefon kann in der FritsBox konfiguriert werden unter: Telefonie/Anrufe/[Tab]Wahlhilfe/Wählhilfe verwenden

Was kann ich damit machen? 
Vielen Dank :-)

**Comment by Apollon77** [comment]
Fragen am besten im Forum ... sonst sollte die Beschreibung doch alles beschreiben ... was DU damti tun kannst musst DU selbst definieren. Effektiv könnte dein haus dich anrufen wenn es Probleme gibt, also einen aktiveren "Trigger" als eine E-Mail

**Comment by CBRocker** [comment]
@Apollon77 Moin Apollon77,
war schon spät, deswegen habe ich nicht ans Forum gedacht :-) Ich danke dir für die Info und werde mich ans Forum wenden.
Grüße Christoph
