### ISSUE TITLE
Max length of Fritz!Box user password is 32 chars

### ISSUE THREAD

**Issue by AndreasHD23** [iobroker-community-adapters/ioBroker.tr-064#418]
Maybe you would like to include in the readme that the max length for a Fritz!Box user password is 32 characters.
Even if you past in a longer password (42 chars in my case) it silently gets cut of after 32 chars without warning in the Fritz!Box WebUI.
Learnt the hard way after 45 minutes of searching through firewall logs and wireshark captures :)

**Comment by Apollon77** [comment]
Added to readme, I decided against a löimit or cutting in the adapter to prevent issues if AVM ever changes this
