### ISSUE TITLE
TR-064 Unclear documentation to make sure ring state works

### ISSUE THREAD

**Issue by T-Kaule** [iobroker-community-adapters/ioBroker.tr-064#421]
Hi,

im not sure if i just didnt not read it. But i had the problem that everything was working fine except the ring state, which did not work at all. After some research if figured out, that it is mandatory, that in the fritz box the setting
/Telefonie/Anrufe/Wählhilfe
the "Wählhilfe verwenden" is marked and set to "Verbindung mit dem Telefon ISDN- und Schnurlostelefone". Just setting it to one specific one does not work.

Im not sure if other people have the same problem, but may be it can be included in the documentation!

**Comment by Apollon77** [comment]
added to docs

**Comment by Apollon77** [comment]
Thank you

**Comment by T-Kaule** [comment]
I everyone, just an update to this, because i got a new fritzbox. To make sure all "real" DECT phones are ringing when using the adapter to make a call, i figured out is the easiest to just add a "non-existent" telephone in the FritzBox. in the telephone settings just generate a new telephone and claim it is added to one of the analog connectors (if you have one free of course). If the Box asks you if it ringed, just click yes. Than you can use this telephone as Wählhilfe, allowing the adapter to ring all "real" phones at once
