### ISSUE TITLE
Rückwärtssuche

### ISSUE THREAD

**Issue by freakyfreaky** [iobroker-community-adapters/ioBroker.tr-064#422]
Hallo Team,

es wäre klasse wenn man die Rückwärtssuche per Checkbox über https://www.dasoertliche.de/rueckwaertssuche/ integrieren könnte.
Der Adapter könnte dann die JSON der Anruflisten und sowie den letzten verpassten Anruf modifizieren wenn kein Eintrag im Telefonbuch vorhanden ist.

**Comment by Apollon77** [comment]
Und du glaubst das so viele Leute heutzutage noch da drin sind? :-)

Ich denke das kann man besser über eigene Skripte lösen ... würde das ungern als Feature im Adapter haben. Der sollte keine externe Abhängigkeiot haben
