### ISSUE TITLE
Anzahl neuer verpasster Anrufe/AB Nachrichten 

### ISSUE THREAD

**Issue by d4rkd3v1l** [iobroker-community-adapters/ioBroker.tr-064#423]
Hallo,

erstmal vielen Dank für den coolen Adapter! 
Leider hab ich keine Möglichkeit gefunden, die Anzahl neuer verpasster Anrufe oder AB Nachrichten zu erhalten. Also quasi wie "MissedCalls" nur, dass eben nur neue, die nicht bereits am Telefon/FritzBox als gesehen markiert wurden, angezeigt werden.

Gibt es da eine Möglichkeit? Oder ist sowas geplant umzusetzen?

Danke und VG

**Comment by Apollon77** [comment]
Da es keine Möglichkeit gibt zu sehen was im telefon/Fritzbox schon als gesehen markiert wurde (also keine die ich kenne)  ... nope

**Comment by d4rkd3v1l** [comment]
Danke für dein Feedback, echt schade.
