### ISSUE TITLE
wps & reconnect IOD

### ISSUE THREAD

**Issue by duczz** [iobroker-community-adapters/ioBroker.tr-064#437]
Der state von wps und reconnect bleibt immer auf true und setzt sich nicht wieder auf false zurück

**Comment by Apollon77** [comment]
Ok, das Issue ist sehr Cryptisch ... Ich rate mal ....

beide States sollten (ohne jezzt im Code zu schauen) Buttons sein. Buttons sind per Definition "write only". Das bedeutet das der Wert nach dem Triggern irrelevant ist und ja damit wird er auch nicht zurückgesetzt (warum auch). Das wäre die Formalie.

Wenn es das ist um was es beim Issue geht ist die Gegenfrage: Warum ist das denn ein Problem?

**Comment by duczz** [comment]
Sorry, bin iobroker technisch nicht so fit, ob es ein Button sein soll weiß ich nicht.
ich bin der meinung wenn ich was aktiviere sprich auf true setzte, sollte es auch wieder auf false gehen, vor allem läuft z.b. wps nur 30 sekunden und wenn man diesen state z.b. in einer Visu eingebunden hat und da immer true steht empfinde ich dies als falsch.
beim reconnect selbiges wenn du einen pc neustartetst willst du ja auch wissen ob der renboot nun fertig ist oder nicht.

**Comment by mcm1957** [comment]
Der Zustand REBOOT hat die Role Button. Es ist nur der Schreibzugriff erlaubt. (Read = False). 
![image](https://user-images.githubusercontent.com/28575778/212466185-9de02e9b-0767-4959-b9df-f1c3219aa482.png)

Der Zustand WPS hat die Role State und sowohl read als auch write erlaubt.
![image](https://user-images.githubusercontent.com/28575778/212466285-6de8f804-89d2-4d66-b67d-5239ebb963cb.png)

Das Verhalten des REBOOT Zustands entspricht dem zu erwartenden Verhalten. Button können nicht gelesen werden bzw. werden vom Adapter nicht beschrieben. In VIS ist dafür ein Button zu verwenden.

Bei WPS ist entweder die Implementierung nicht vollständig oder die Konfiguration des States nicht richtig. Wenn die FritzBox den Zustand WPS AKTIV abfragbar anbietet, dann sollte dieser State auch aktualisiert werden. Wenn nicht, dann sollte WPS ein Button sein (read=false, Role=Button).

**Comment by Apollon77** [comment]
> wenn man diesen state z.b. in einer Visu eingebunden hat und da immer true steht empfinde ich dies als falsch.
beim reconnect selbiges wenn du einen pc neustartetst willst du ja auch wissen ob der reboot nun fertig ist oder nicht.

Und genau das haben wir die Crux. Der Adapter sendet das nur. lso "WPS an" bzw "Bitte Reboot". Der Adapter weiss in dem Fal nicht wann/ob das wieder ausgeht oder Fertig ist. Also kann er das gar nicht anzeigen bzw das wären dann (vllt) andere States die das anzeigen könnten.

Bei States von der Rolle "button" sollte man auch einen Button in einer Visualisierung nutzen und nicht einen "Schalter" (button === Taster, der nur "mach was Trigger" ist, Schalter hat ein/aus als Stati).

**Comment by Apollon77** [comment]
Ok, "wps" ist potentiell ein switch weil man es ein und auch ausschalten kann ... dennoch weiss der Adapter nicht den aktuellen WPS Status ... ist also nochmal ein sonderfall :-( Wäre sauberer zwei "Button" states zu machen ... einmal "trigger an" und einmal "trigger aus" ...

Keine Ahnung wie man das sauber lösen soll. Formal ein "write only switch"

**Comment by mcm1957** [comment]
Lt. AVM Docu (https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf) kann der WPS Status scheinbar abgefragt werden. Zumindest gibt es die Schnittstelle X_AVM-DE_GetWPSInfo:

![image](https://user-images.githubusercontent.com/28575778/212488946-4ec9798c-b32a-4c23-b081-1bede5c3ea48.png)

Ob das nun nicht implementiert ist, nicht funktioniert oder AVM nicht so supported wie der Text es vermuten läßt ab ich nicht weiter nachgeforscht. 

Ich schlage daher vor das Issue offen zu lassen (nur in Bezug auf den Zustand wps). Wenn man das genauer analysiert kann man es wahrscheinlich auch gleich fixen oder begründet ablehnen.
