### ISSUE TITLE
Datenpunkt ring ruft nicht mehr an nach Update auf FritzOS 7.50

### ISSUE THREAD

**Issue by danny030** [iobroker-community-adapters/ioBroker.tr-064#440]
Hi,
bisher konnte ich über den "ring"-Datenpunkt des Adapters problemlos einen Anruf starten. Das funktioniert nun nicht mehr. Ich kann es nicht mit Sicherheit sagen, allerdings lässt sich anhand der Anrufliste auf der Fritzbox relativ gut rekonstruieren, dass es vor dem Update auf FritzOS 7.50 (Fritzbox 7490) noch funktioniert hat. Danach leider nicht mehr. 

Ich trage im "ring"-Datenpunkt einfach meine Mobilnummer ein im Format 01723456789. Der Anruf wird nicht durchgeführt. Im Fritzbox Log ist nichts zu finden und im ioBroker Log sehe ich auch nichts vom TR064-Adapter. Andere Funktionen des Adapters funktionieren noch, ich kann bspw. das Gäste-WLAN über den "wlanguest"-Datenpunkt weiterhin an/aus schalten. Es ist also kein Verbindungsproblem o.ä. sondern scheint sich auf das ring zu beschränken.

Mir ist nicht ganz klar, ob das ein Problem des Adapters ist oder mit FritzOS 7.50. Hat jemand ähnliche Erfahrungen gemacht und kann sagen, ob das hier ein Issue ist oder ob ich zu AVM muss?

**Versions:**  
 - Adapter version: 4.2.17 (stable)
 - JS-Controller version: 4.0.23
 - Node version: v14.19.0
 - Operating system: Raspbian

**Comment by Apollon77** [comment]
SO eine Frage ist besser im Forum gestellt als hier auf GitHub. Mal tr-064 im Debug log versucht? Was steht dann da?

**Comment by danny030** [comment]
Das ist wohl wahr, sorry, merke ich mir.
Ich poste mal das Log hier, wenn es nicht passt, ziehe ich auch gerne ins Forum um mit der Frage.

Gewählt im ring-Datenpunkt wurde die Nummer 03012345678 (natürlich maskiert, verschiedene echte Nummern probiert). Erst sieht alles gut aus (die Telefonbucheinträge sind gekürzt). Nach dem Log Eintrag " _Ring : ["03012345678"]_ " passierte nichts mehr. Die nächsten Einträge folgten erst 4 Minuten später mit " _in updateAll_ ".

Das sind die letzten beiden Zeilen, log seit Adapter-Start anbei.

`2023-01-23 22:44:43.986  - [34mdebug[39m: tr-064.0 (29331) State changed: tr-064.0.states.ring = {"val":"03012345678","ack":false,"ts":1674510283981,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1674510283981}`
`2023-01-23 22:44:43.987  - [34mdebug[39m: tr-064.0 (29331) Ring : ["03012345678"]`

[iobroker.current.html.txt](https://github.com/iobroker-community-adapters/ioBroker.tr-064/files/10484018/iobroker.current.html.txt)

**Comment by Apollon77** [comment]
Der eintrag "Ring: [ ... ]" besagt das die Anfrage an die Fritzbox gesendet wurde ...

Die Info in https://github.com/iobroker-community-adapters/ioBroker.tr-064#ring-dial-a-number hast Du beachtet?

**Comment by danny030** [comment]
Achso, ich hätte gedacht da würde noch die Antwort zurückkommen müssen.

Ja, war auf "ISDN- und Schnurlostelefone" eingestellt, da war ich seit dem Update nicht dran. Mit deinem Hinweis habe ich es mal testweise auf das angeschlossene DECT-Gerät "Mobil 1" geändert und das hat plötzlich geklappt. Zurückgestellt auf "ISDN- und Schnurlostelefone" hat wieder nicht geklappt. Mit "Mobil 1" also Problem gelöst, liegt nicht am Adapter und das nächste Mal im Forum. Danke schön!
