### ISSUE TITLE
No Connection to FS-Version: 7.39-102330 BETA

### ISSUE THREAD

**Issue by Mephisto090** [iobroker-community-adapters/ioBroker.tr-064#443]
Hej,

The adapter cannot connect to the new FS-Version: 7.39-102330 BETA

![image](https://user-images.githubusercontent.com/85995176/215853968-e891084b-d7b4-4a0a-aeec-b59f8e03147e.png)

**Comment by mcm1957** [comment]
The error message indicates that the name fritz.box cannotbe resolved. This looks more like a  dns error. Did you verify that fritz.box can be resolved? I.e. using nslokup?

In addition nrwer fritz osrs enable ipv6 per default. Maybe this causes the problem Check iov6 settings at fb if you do not hVe a working ipv6 environment.

In addition version 7.39 neta seems surprising. As far as i know v7.50 is current version for most devices.

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/215868362-f89f756c-128f-450c-b961-a28b0d908607.png)

nslookup :)

**Comment by Mephisto090** [comment]
Laut Profil bist du Österreicher. Lass uns einfach deutsch reden :)

**Comment by Apollon77** [comment]
Node.js löst per Default bevorzugt mit IPv4 auf. Hast Du ein IPv6 only Netz? bzw es scheint so zu sein das dein DNS ipv6 only ist ... Das sieht mir spontan nach dem Problem aus

**Comment by mcm1957** [comment]
Die neuere fritz os haben ipv6 per default enabled. Damit bekommen rechner potenziell auch ipv6 adressen. Wenn das nicht alle komponenten können führt das ev zu problemen. Soll heissen dass ev für frotz.box eine ipv6 geliefert wird die dann irgendwo nicht verarbeitet werden kann

Wenn du also iov6 nicht bewusst verwenden willst od verwendest macht es ev sinn das auf der fb abzuschalten. Zumindest solange bis das problem gelöst ist.

**Comment by Apollon77** [comment]
Nee das ist es nicht. Schau mal oben. Sein DNS ist ipv6 only und das ist das problem! Es scheint kein IPv4 DNS zu geben. Und das ist kein "Standard konfig"

**Comment by mcm1957** [comment]
Ich nichtvmal sicher ob der nslookup vom iob rechner gemacht wurde. Das nslokup oben ist v windows. Und ja es fragt einen dns server über die iov6 ab. Die Antwort liefert aber ipv6 u ipv4 addressen.

Die fritte hat auf jeden fall ipv6 enabled. 

Da gabs vor wochen schon ma wol probleme weil auf der fb ipv6 im zuge des upgrades aufgedreht wurde andere rechner bzw sw das aber nicht verstanden.

**Comment by Mephisto090** [comment]
Das nslookup auf dem Windows war auf dem Server wo Docker läuft. Der Adapter fb-cheackpresence scheint damit klar zu kommen, falls es dir hilft.

Ich kann gerne versuchen ipv4 zu aktivieren.

**Comment by Apollon77** [comment]
Wie siehst denn auf dem ioBroker host ein nslookup (bzw "dig fritz.box") aus?

**Comment by Mephisto090** [comment]
> Wie siehst denn auf dem ioBroker host ein nslookup (bzw "dig fritz.box") aus?

![image](https://user-images.githubusercontent.com/85995176/216121386-e2844157-020b-481e-951e-6aa669a06fa2.png)

**Comment by Mephisto090** [comment]
Das kommt, wenn ich mal die IP eintrage und nicht "fritz.box"

![image](https://user-images.githubusercontent.com/85995176/216123915-8801edad-19bc-4e2d-a1c6-c0aed0ae09c7.png)

**Comment by Apollon77** [comment]
@Mephisto090 so, siehe dein vorletzter Beitrag ... wenn dein Linux Host wo ioBroker läuft schon nicht an der Kommandozeile das auflösen kann dann kanns nodejs auf dem gleichen host auch nicht ... und 127.0.0.11 sieht mehr als komisch aus ... Fixe das und du hast es gefixt. Ich mache hier zu ... ggf besseres Thema für Forum
