### ISSUE TITLE
Call lists are not being updated. debug log shows empty call list

### ISSUE THREAD

**Issue by mule1972** [iobroker-community-adapters/ioBroker.tr-064#447]
**Describe the bug**  
After the adapter and instance of TR-064 had been setup and started the call lists had once being updated.
Since than the update of the call lists has stopped and the debug log only shows an empty call list after the request allthough the call monitor is working fine.
Info: I am using a 5590 with the latest official firmware V7.30.

<html><body>

tr-064.0 | 2023-03-09 23:15:08.806 | debug | Calllist states updated
-- | -- | -- | --
tr-064.0 | 2023-03-09 23:15:08.793 | debug | Calllist outbound regenerated
tr-064.0 | 2023-03-09 23:15:08.793 | debug | Calllist missed regenerated
tr-064.0 | 2023-03-09 23:15:08.792 | debug | Calllist inbound regenerated
tr-064.0 | 2023-03-09 23:15:08.791 | debug | Calllist all regenerated
tr-064.0 | 2023-03-09 23:15:08.789 | debug | Result Calllist JSON: {"root":{"timestamp":"1656235878"}}
tr-064.0 | 2023-03-09 23:15:08.754 | debug | Request Calllist JSON: url = http://192.168.178.1:49000/calllist.lua?sid=1e529e3b0ae5390a&timestamp=1656235878&id=368
tr-064.0 | 2023-03-09 23:15:08.745 | debug | forEachConfiguredDevice
tr-064.0 | 2023-03-09 23:15:08.744 | debug | createConfiguredDevices
tr-064.0 | 2023-03-09 23:15:08.742 | debug | Initialize  HTML template: <div>The last call was  from %(name) at %(date) from %(caller)</div><div>%(type):  %(count)<table><!!--Entry--><tr><td>%(date)</td><td>%(name)</td><td>%(caller)</td></tr><!!--EntryEnd--></table></div>
tr-064.0 | 2023-03-09 23:15:07.636 | debug | Set  Template: "<div>The last call was from %(name) at  %(date) from %(caller)</div><div>%(type):  %(count)<table><!!--Entry--><tr><td>%(date)</td><td>%(name)</td><td>%(caller)</td></tr><!!--EntryEnd--></table></div>"
tr-064.0 | 2023-03-09 23:15:07.543 | debug | Calllist  Config after normalizing:  {"all":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"missed":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"outbound":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"inbound":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"use":true}
tr-064.0 | 2023-03-09 23:15:07.440 | info | starting. Version 4.2.17 in /opt/iobroker/node_modules/iobroker.tr-064, node: v16.16.0, js-controller: 4.0.24

</body>
</html>

**Comment by Apollon77** [comment]
Please check your fritzbox ... the log states that no calls are returned:

> Result Calllist JSON: {"root":{"timestamp":"1656235878"}}

Please pot restart the fritzbox

**Comment by Apollon77** [comment]
Also verify thatthe clock of the iobroker host is correct

**Comment by mule1972** [comment]
Thanks for trying to help!
A restart of the fritzbox did not help and the clock on iobroker host is correct.
As written: After the first start of the tr-064 instance a call list is being returned and correctly written to the tr-064 objects, but than all new calls are being ignored and the log as above only shows an empty list. What is weird is that the callmonitor of tr-064 is filling the objects with new calls.
Any further idea where to look to find the issue?

**Comment by Apollon77** [comment]
No idea, as you see the Adapter requests the data based on id and timestamp ... 

so in general something IS strange!!! maybe some old ID is somehow(somewhere in?

The timestamo in the above log is "GMT: Sunday, 26. June 2022 09:31:18" 

YOu could try to remoce the instance ... or check the object system.adapter.tr-064.0 in admin  with enabled expert mdoe and check for lastTimestam or lastId ... and maybe remove this

**Comment by mule1972** [comment]
Oh, this time stamp is even more weird. Will try as you suggested.

Besides: The "fritzbox" adapter is working fine.

**Comment by mule1972** [comment]
I just installed it the adapter on my test iobroker system and there it is working fine. So issue can be closes. Will have a look to find out the difference between my system and production iobroker system.

**Comment by Apollon77** [comment]
Noone said that it is a state :-)

Go in objects to "system.adapter.tr-064.X" anc lcick the pencil icon in this line ... then you see a JSON ...
