### ISSUE TITLE
SetConfig "NewMacAddressControlEnabled" doesn't work

### ISSUE THREAD

**Issue by exaware** [iobroker-community-adapters/ioBroker.tr-064#482]
I try to enable/disable the WLAN Mac-Filter using folowing command but I get a "Code":"500" as result.

`{
  "service": "urn:dslforum-org:service:WLANConfiguration:1",
  "action": "SetConfig",
  "params": {
    "NewMacAddressControlEnabled": "0"
  }
}
`

Why I get this error?

**Comment by exaware** [comment]
Hallo @Apollon77,
can you check why my command doesn't work? I can gets infos with other commands but this command doesn't work. I think it's a bug.

**Comment by exaware** [comment]
I checkd the command multiple times. I found always the same command. I also checked in doku.

This command works:
`{
  "service": "urn:dslforum-org:service:WLANConfiguration:1",
  "action": "GetInfo",
  "params": {}
}`

This command doesn't work:
`{
  "service": "urn:dslforum-org:service:WLANConfiguration:1",
  "action": "SetConfig",
  "params": {
    "NewMACAddressControlEnabled": "1"
  }
}`

**Comment by Apollon77** [comment]
Maybe check in the ioBroker Forum if someone has experience here ... I never used such commands myself

**Comment by exaware** [comment]
I got the decisive tip from AVM support. 
You have to pass all parameters to the action "SetConfig" not only  "NewMACAddressControlEnabled". 
Now it works as expected.
![image](https://github.com/iobroker-community-adapters/ioBroker.tr-064/assets/55593493/eaaa2b2a-5b4a-4740-9862-8a753f3b19ff)
