### ISSUE TITLE
callmonitor\inbound\callerName UND caller nur nach Neustart einmalig korrekt

### ISSUE THREAD

**Issue by actionbyte** [iobroker-community-adapters/ioBroker.tr-064#73]
Hallo,

nach einem Neustart vom Adapter wird beim ersten Anruf "callerName" ausgefüllt. Danach nie wieder, nur die Nummer wird unter "Caller" eingetragen. Ruft jedoch der gleiche Teilnehmer erneut an bleibt dann auch "Caller" einfach leer. Erst wenn ein anderer Anrufer anruft wird die Nummer unter "Caller" wieder angezeigt, "CallerName" bleibt wie beschrieben immer leer.
Nach dem Auflegen erscheint jedoch beides immer korrekt unter "LastCall"

Im Log sind vom Tr064 keine Eintragungen zu sehen, oder kann ich explizit vom Adapter Debug einschalten?

@edit:
1. wo wird eigentlich angegeben welches Telefonbuch der FB ausgelesen werden soll?
2. bei 2 FBs im Mesh ist es egal auf welcher Box ich den tr064 anmelde?
3. wird hier noch supportet?

**Comment by Apollon77** [comment]
Bitte mit 2.0.0 vom GitHub neu versuchen. ggf debug log senden!

**Comment by Smarty-D** [comment]
Hallo. Ich habe es heute unter 2.0.0 getestet. Der "callerName" aktualisiert sich anscheinen nur, wenn beim eingehenden Anruf eine Nummer mitkommt. Entweder mit einem dazugehörigem Namen aus dem Telefonbuch oder "".
Wenn der eingehende Anruf mit unterdrückter Nummer erfolgt und somit "caller" leer bleibt, wird der "callerName" nicht aktualisiert.

**Comment by Apollon77** [comment]
hast Du mal ein Debug Log von so einem Anruf mit unterdrückter Nummer? Gern an iobroker@fischer-ka.de mit Verweis auf das Issue hier (wegen pot. privaten Daten).

**Comment by Apollon77** [comment]
Bitte vorher nochmal neu von GitHub aktualisieren, Habe noch mehr Logging eingebaut

**Comment by Apollon77** [comment]
PS: Kann es sein das Du irgendwie "von aussen en CallerName änderst? Der Adapter kennt den letzten Stand den Er gesetzt hat und schreibt nur neu wenn sich dieser wert ändert. Am Adapter vorbei den State ändern macht komische Effekte!

**Comment by actionbyte** [comment]
@Apollon77 

habe jetzt die 2.0.0 installiert. Folgendes Problem besteht noch immer:
Wenn 2 mal von der gleichen Nummer hintereinander angerufen wird (Zeitabstand egal) wird /Callmonitor/inbound/json zwar korrekt ausgefüllt, aber der name beim zweiten Anruf NICHT unter callername eingetragen. Diese Feld lese ich aber mit Blockly aus, wenn dieses leer bleibt ist für das Script der Anrufer "unbekannt". 
Ich habe dir ein gezipptes debug.log zugeschickt. Hergang hier: Anrufer A -> callername ok, Anrufer B -> Callername ok, danach erneut Anrufer B -> Callername bleibt leer.

Wäre schön wenn du (m)einen Fehler im Log findest. Danke!

**Comment by Apollon77** [comment]
Wie kommt der leere callerName zustande? Der Adapter löschtest sich keine Daten ausbaden States. 

Kann es sein das du den callerName manuell per Skript auf einen leeren Wert setzt „am Adapter vorbei“? Naja sowas sollte ich im log dann ja sehen   Falls du das tust ist genau das der Grund. 

Wie oben schon geschrieben merkt sich der Adapter seine geschriebenen Werte und schreibt nur neu wenn der Wert anders ist. State changes „von außerhalb“ werden dabei nicht berücksichtigt und damit kommt es zu einer Diskrepanz

**Comment by actionbyte** [comment]
Hi,

 

oh sorry, ich lese gerade im Script das ich anstatt meiner Variable tatsächlich den Callerstate leer überschreibe.
Sorry, mein Fehler, werde mal berichtigen und dann eneut den 2.0 testen.
Danke für den Support!

Gruß
Hans

 

Von: Ingo Fischer <notifications@github.com> 
Gesendet: Dienstag, 17. Dezember 2019 19:39
An: iobroker-community-adapters/ioBroker.tr-064-community <ioBroker.tr-064-community@noreply.github.com>
Cc: actionbyte <niegsch@mail.de>; Author <author@noreply.github.com>
Betreff: Re: [iobroker-community-adapters/ioBroker.tr-064-community] callmonitor\inbound\callerName UND caller nur nach Neustart einmalig korrekt (#73)

 

Wie kommt der leere callerName zustande? Der Adapter löschtest sich keine Daten ausbaden States.

Kann es sein das du den callerName manuell per Skript auf einen leeren Wert setzt „am Adapter vorbei“? Naja sowas sollte ich im log dann ja sehen Falls du das tust ist genau das der Grund.

Wie oben schon geschrieben merkt sich der Adapter seine geschriebenen Werte und schreibt nur neu wenn der Wert anders ist. State changes „von außerhalb“ werden dabei nicht berücksichtigt und damit kommt es zu einer Diskrepanz

**Comment by Apollon77** [comment]
Bin gespannt. Würde erwarten das es dann magisch tut ;-)

**Comment by Apollon77** [comment]
Ok, dann bitte nach dem test nochmal melden :-) ggf neues log ohne "externes überschreiben" schicken wenn noch was nicht tut

**Comment by MaKnoNet** [comment]
Hi, ich hatte das gleiche problem und konnte es lösen indem ich "**Verwende MDNS zum triggern der Aktuallisierung**" in den Einstellungen deaktiviert hatte.

**Comment by Apollon77** [comment]
Das eine sollte mit dem anderen nichts zu tun haben

**Comment by guergen1** [comment]
Der erste Anruf nach einem Adapterneustart wird mit Namen hinterlegt:
` tr-064-community.0	2020-01-02 17:33:22.884	debug	(19990) in updateAll
tr-064-community.0	2020-01-02 17:33:17.719	debug	(19990) State changed: tr-064-community.0.callmonitor.toPauseState = {"val":"ring","ack":true,"ts":1577982797685,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","lc":157798
tr-064-community.0	2020-01-02 17:33:17.717	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.json = {"val":"{\"caller\":\"015127506301\",\"callee\":\"564690\",\"timestamp\":\"02.01.20 17:33:17\",\"id\":\"0\",\"_type\":\"inbound\",\
tr-064-community.0	2020-01-02 17:33:17.713	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.callerName = {"val":"Ralf","ack":true,"ts":1577982797685,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","lc":
tr-064-community.0	2020-01-02 17:33:17.710	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.timestamp = {"val":"02.01.20 17:33:17","ack":true,"ts":1577982797684,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.
tr-064-community.0	2020-01-02 17:33:17.707	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.caller = {"val":"0xxxxx301","ack":true,"ts":1577982797684,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","
tr-064-community.0	2020-01-02 17:33:17.705	debug	(19990) State changed: tr-064-community.0.callmonitor.ringing = {"val":true,"ack":true,"ts":1577982797684,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","lc":1577982797684
tr-064-community.0	2020-01-02 17:33:17.680	debug	(19990) callMonitor.set: type=inbound caller=0xxxxx301 callee=564690 callerName=Ralf
tr-064-community.0	2020-01-02 17:33:17.677	debug	(19990) Search number 0049xxxx564690 in phonebook: undefined
tr-064-community.0	2020-01-02 17:33:17.676	debug	(19990) Search number 0049xxxxxxxx301 in phonebook: {"name":"Ralf","normalizedName":"ralf","number":"0049xxxxx301","id":"68","phonebookId":"0"}
tr-064-community.0	2020-01-02 17:33:17.672	debug	(19990) New Call data inbound: {"caller":"0xxxxx301","callee":"564690","timestamp":"02.01.20 17:33:17","id":"0"}
tr-064-community.0	2020-01-02 17:33:17.669	debug	(19990) Callmonitor Raw: 02.01.20 17:33:17;RING;0;0xxxxx301;564690;SIP0;`

Der nächste Anruf kommt auch mit übermittelter Nummer, aber wird nicht übergeben:
`tr-064-community.0	2020-01-02 17:34:16.675	debug	(19990) in updateAll
tr-064-community.0	2020-01-02 17:34:15.544	debug	(19990) State changed: tr-064-community.0.callmonitor.toPauseState = {"val":"ring","ack":true,"ts":1577982855533,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","lc":157798
tr-064-community.0	2020-01-02 17:34:15.541	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.json = {"val":"{\"caller\":\"0xxxxxx301\",\"callee\":\"564690\",\"timestamp\":\"02.01.20 17:34:15\",\"id\":\"0\",\"_type\":\"inbound\",\
tr-064-community.0	2020-01-02 17:34:15.540	debug	(19990) State changed: tr-064-community.0.callmonitor.inbound.timestamp = {"val":"02.01.20 17:34:15","ack":true,"ts":1577982855531,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.
tr-064-community.0	2020-01-02 17:34:15.538	debug	(19990) State changed: tr-064-community.0.callmonitor.ringing = {"val":true,"ack":true,"ts":1577982855531,"q":0,"from":"system.adapter.tr-064-community.0","user":"system.user.admin","lc":1577982855531
tr-064-community.0	2020-01-02 17:34:15.530	debug	(19990) callMonitor.set: type=inbound caller=0xxxxx301 callee=564690 callerName=Ralf
tr-064-community.0	2020-01-02 17:34:15.529	debug	(19990) Search number 0049xxxxx564690 in phonebook: undefined
tr-064-community.0	2020-01-02 17:34:15.529	debug	(19990) Search number 0049xxxxx301 in phonebook: {"name":"Ralf","normalizedName":"ralf","number":"0049xxxxx301","id":"68","phonebookId":"0"}
tr-064-community.0	2020-01-02 17:34:15.528	debug	(19990) New Call data inbound: {"caller":"0xxxxx301","callee":"564690","timestamp":"02.01.20 17:34:15","id":"0"}
tr-064-community.0	2020-01-02 17:34:15.528	debug	(19990) Callmonitor Raw: 02.01.20 17:34:15;RING;0;0xxxxx301;564690;SIP0; `

Bei mir ist die Version 2.0.3 installiert

**Comment by Apollon77** [comment]
kann es sein das sich der Name nicht ändert? Dann ist das alles korrekt wie oben schon geschrieben ...

**Comment by Smarty-D** [comment]
Hallo und erst einmal sorry für die späte Antwort.
Ich habe den Adapter (2.0.0) komplett entfernt und in Version 2.0.2 neu installiert. Nun funktioniert alles wieder. An was es nun gelegen haben soll ist mir schleierhaft, aber es funktioniert ja jetzt wieder. Vielen Dank trotzdem für den Support!

**Comment by actionbyte** [comment]
Aktuell ist 2.0.3 
;-)

**Comment by guergen1** [comment]
Kann geschlossen werden, funktioniert wieder.... warum auch immer
