### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.tr-064#74]
Hi, the object "command" don't give a result. In the description of https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/hostsSCPD.pdf are some commands, no one of this are working here. 
My Favorite is  GetHostNumberOfEntries , the result must be the number of connected Hosts.

Would be fine to fix this. :-)

I know, tr-064 implementation have a lot of commands, but the number of connected hosts are important for the overview, whats with the complete network.. 
( my objective is to make a script, that give me message, when connected devices are lower as 240 - than something must be offline.. I don't want to ping every 300 devices are in my network..) :-)

**Comment by Apollon77** [comment]
Ok, Infos:
1.) Existing commands can be seen when you enter "dumpServices" into the command state
2.) the value of "command" needs to be an object with at least keys "action" and "params"

Please show an example call and provide debug log please!

**Comment by Ilovegym66** [comment]
dumpServices is working fine, but no other command, no reaction, can you provide a sample for GetHostNumberOfEntries, please? looks like i don't understand the parameters...

**Comment by Apollon77** [comment]
I hoped you know how to do it ;-) I do not really use this so I do most stuff here „blind“ ...

I will check and maybe I can send an idea.

**Comment by Apollon77** [comment]
Can youngest the output or debug log from the dump command please?!

**Comment by Ilovegym66** [comment]
output of "dumpServices" 
`{"urn:dslforum-org:service:DeviceInfo:1":{"actions":{"GetInfo":"fn","SetProvisioningCode":"fn","GetDeviceLog":"fn","GetSecurityPort":"fn"}},"urn:dslforum-org:service:DeviceConfig:1":{"actions":{"GetPersistentData":"fn","SetPersistentData":"fn","ConfigurationStarted":"fn","ConfigurationFinished":"fn","FactoryReset":"fn","Reboot":"fn","X_GenerateUUID":"fn","X_AVM-DE_GetConfigFile":"fn","X_AVM-DE_SetConfigFile":"fn","X_AVM-DE_CreateUrlSID":"fn"}},"urn:dslforum-org:service:Layer3Forwarding:1":{"actions":{"SetDefaultConnectionService":"fn","GetDefaultConnectionService":"fn","GetForwardNumberOfEntries":"fn","AddForwardingEntry":"fn","DeleteForwardingEntry":"fn","GetSpecificForwardingEntry":"fn","GetGenericForwardingEntry":"fn","SetForwardingEntryEnable":"fn"}},"urn:dslforum-org:service:LANConfigSecurity:1":{"actions":{"GetInfo":"fn","X_AVM-DE_GetCurrentUser":"fn","X_AVM-DE_GetAnonymousLogin":"fn","SetConfigPassword":"fn"}},"urn:dslforum-org:service:ManagementServer:1":{"actions":{"GetInfo":"fn","SetManagementServerURL":"fn","SetManagementServerUsername":"fn","SetManagementServerPassword":"fn","SetPeriodicInform":"fn","SetConnectionRequestAuthentication":"fn","SetUpgradeManagement":"fn","X_SetTR069Enable":"fn","X_AVM-DE_GetTR069FirmwareDownloadEnabled":"fn","X_AVM-DE_SetTR069FirmwareDownloadEnabled":"fn"}},"urn:dslforum-org:service:Time:1":{"actions":{"GetInfo":"fn","SetNTPServers":"fn"}},"urn:dslforum-org:service:UserInterface:1":{"actions":{"GetInfo":"fn","X_AVM-DE_CheckUpdate":"fn","X_AVM-DE_DoUpdate":"fn","X_AVM-DE_DoPrepareCGI":"fn","X_AVM-DE_DoManualUpdate":"fn","X_AVM-DE_GetInternationalConfig":"fn","X_AVM-DE_SetInternationalConfig":"fn","X_AVM-DE_GetInfo":"fn","X_AVM-DE_SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Storage:1":{"actions":{"GetInfo":"fn","RequestFTPServerWAN":"fn","SetFTPServer":"fn","SetFTPServerWAN":"fn","SetSMBServer":"fn","GetUserInfo":"fn","SetUserConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_WebDAVClient:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_UPnP:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Speedtest:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_RemoteAccess:1":{"actions":{"GetInfo":"fn","SetConfig":"fn","SetEnable":"fn","GetDDNSInfo":"fn","GetDDNSProviders":"fn","SetDDNSConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_MyFritz:1":{"actions":{"GetInfo":"fn","GetNumberOfServices":"fn","GetServiceByIndex":"fn","SetServiceByIndex":"fn","DeleteServiceByIndex":"fn"}},"urn:dslforum-org:service:X_VoIP:1":{"actions":{"GetInfoEx":"fn","X_AVM-DE_AddVoIPAccount":"fn","X_AVM-DE_GetVoIPAccount":"fn","X_AVM-DE_DelVoIPAccount":"fn","GetInfo":"fn","SetConfig":"fn","GetMaxVoIPNumbers":"fn","GetExistingVoIPNumbers":"fn","X_AVM-DE_GetNumberOfClients":"fn","X_AVM-DE_GetClient":"fn","X_AVM-DE_GetClient2":"fn","X_AVM-DE_SetClient":"fn","X_AVM-DE_SetClient2":"fn","X_AVM-DE_GetClient3":"fn","X_AVM-DE_GetClientByClientId":"fn","X_AVM-DE_SetClient3":"fn","X_AVM-DE_SetClient4":"fn","X_AVM-DE_GetClients":"fn","X_AVM-DE_GetNumberOfNumbers":"fn","X_AVM-DE_GetNumbers":"fn","X_AVM-DE_DeleteClient":"fn","X_AVM-DE_DialGetConfig":"fn","X_AVM-DE_DialSetConfig":"fn","X_AVM-DE_DialNumber":"fn","X_AVM-DE_DialHangup":"fn","X_AVM-DE_GetPhonePort":"fn","X_AVM-DE_SetDelayedCallNotification":"fn","GetVoIPCommonCountryCode":"fn","X_AVM-DE_GetVoIPCommonCountryCode":"fn","SetVoIPCommonCountryCode":"fn","X_AVM-DE_SetVoIPCommonCountryCode":"fn","GetVoIPEnableCountryCode":"fn","SetVoIPEnableCountryCode":"fn","GetVoIPCommonAreaCode":"fn","X_AVM-DE_GetVoIPCommonAreaCode":"fn","SetVoIPCommonAreaCode":"fn","X_AVM-DE_SetVoIPCommonAreaCode":"fn","GetVoIPEnableAreaCode":"fn","SetVoIPEnableAreaCode":"fn","X_AVM-DE_GetAlarmClock":"fn","X_AVM-DE_SetAlarmClockEnable":"fn","X_AVM-DE_GetNumberOfAlarmClocks":"fn"}},"urn:dslforum-org:service:X_AVM-DE_OnTel:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","SetConfig":"fn","GetInfoByIndex":"fn","SetEnableByIndex":"fn","SetConfigByIndex":"fn","DeleteByIndex":"fn","GetNumberOfEntries":"fn","GetCallList":"fn","GetPhonebookList":"fn","GetPhonebook":"fn","AddPhonebook":"fn","DeletePhonebook":"fn","GetPhonebookEntry":"fn","GetPhonebookEntryUID":"fn","SetPhonebookEntry":"fn","SetPhonebookEntryUID":"fn","DeletePhonebookEntry":"fn","DeletePhonebookEntryUID":"fn","GetCallBarringEntry":"fn","GetCallBarringEntryByNum":"fn","GetCallBarringList":"fn","SetCallBarringEntry":"fn","DeleteCallBarringEntryUID":"fn","GetDECTHandsetList":"fn","GetDECTHandsetInfo":"fn","SetDECTHandsetPhonebook":"fn","GetNumberOfDeflections":"fn","GetDeflection":"fn","GetDeflections":"fn","SetDeflectionEnable":"fn"}},"urn:dslforum-org:service:X_AVM-DE_TAM:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","GetMessageList":"fn","MarkMessage":"fn","DeleteMessage":"fn","GetList":"fn"}},"urn:dslforum-org:service:X_AVM-DE_AppSetup:1":{"actions":{"GetInfo":"fn","GetConfig":"fn","GetAppMessageFilter":"fn","RegisterApp":"fn","SetAppVPN":"fn","SetAppVPNwithPFS":"fn","SetAppMessageFilter":"fn","SetAppMessageReceiver":"fn","ResetEvent":"fn","GetAppRemoteInfo":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Homeauto:1":{"actions":{"GetInfo":"fn","GetGenericDeviceInfos":"fn","GetSpecificDeviceInfos":"fn","SetDeviceName":"fn","SetSwitch":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Homeplug:1":{"actions":{"GetNumberOfDeviceEntries":"fn","GetGenericDeviceEntry":"fn","GetSpecificDeviceEntry":"fn","DeviceDoUpdate":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Filelinks:1":{"actions":{"GetNumberOfFilelinkEntries":"fn","GetGenericFilelinkEntry":"fn","GetSpecificFilelinkEntry":"fn","NewFilelinkEntry":"fn","SetFilelinkEntry":"fn","DeleteFilelinkEntry":"fn","GetFilelinkListPath":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Auth:1":{"actions":{"GetInfo":"fn","GetState":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:WLANConfiguration:1":{"actions":{"SetEnable":"fn","GetInfo":"fn","SetConfig":"fn","SetSecurityKeys":"fn","GetSecurityKeys":"fn","SetDefaultWEPKeyIndex":"fn","GetDefaultWEPKeyIndex":"fn","SetBasBeaconSecurityProperties":"fn","GetBasBeaconSecurityProperties":"fn","GetStatistics":"fn","GetPacketStatistics":"fn","GetBSSID":"fn","GetSSID":"fn","SetSSID":"fn","GetBeaconType":"fn","SetBeaconType":"fn","GetChannelInfo":"fn","SetChannel":"fn","GetBeaconAdvertisement":"fn","SetBeaconAdvertisement":"fn","GetTotalAssociations":"fn","GetGenericAssociatedDeviceInfo":"fn","GetSpecificAssociatedDeviceInfo":"fn","X_AVM-DE_GetSpecificAssociatedDeviceInfoByIp":"fn","X_AVM-DE_GetWLANDeviceListPath":"fn","X_AVM-DE_SetStickSurfEnable":"fn","X_AVM-DE_GetIPTVOptimized":"fn","X_AVM-DE_SetIPTVOptimized":"fn","X_AVM-DE_GetNightControl":"fn","X_AVM-DE_GetWLANHybridMode":"fn","X_AVM-DE_SetWLANHybridMode":"fn","X_AVM-DE_GetWLANExtInfo":"fn","X_AVM-DE_GetWPSInfo":"fn","X_AVM-DE_SetWPSConfig":"fn","X_AVM-DE_SetWLANGlobalEnable":"fn"}},"urn:dslforum-org:service:WLANConfiguration:2":{"actions":{"SetEnable":"fn","GetInfo":"fn","SetConfig":"fn","SetSecurityKeys":"fn","GetSecurityKeys":"fn","SetDefaultWEPKeyIndex":"fn","GetDefaultWEPKeyIndex":"fn","SetBasBeaconSecurityProperties":"fn","GetBasBeaconSecurityProperties":"fn","GetStatistics":"fn","GetPacketStatistics":"fn","GetBSSID":"fn","GetSSID":"fn","SetSSID":"fn","GetBeaconType":"fn","SetBeaconType":"fn","GetChannelInfo":"fn","SetChannel":"fn","GetBeaconAdvertisement":"fn","SetBeaconAdvertisement":"fn","GetTotalAssociations":"fn","GetGenericAssociatedDeviceInfo":"fn","GetSpecificAssociatedDeviceInfo":"fn","X_AVM-DE_GetSpecificAssociatedDeviceInfoByIp":"fn","X_AVM-DE_GetWLANDeviceListPath":"fn","X_AVM-DE_SetStickSurfEnable":"fn","X_AVM-DE_GetIPTVOptimized":"fn","X_AVM-DE_SetIPTVOptimized":"fn","X_AVM-DE_GetNightControl":"fn","X_AVM-DE_GetWLANHybridMode":"fn","X_AVM-DE_SetWLANHybridMode":"fn","X_AVM-DE_GetWLANExtInfo":"fn","X_AVM-DE_GetWPSInfo":"fn","X_AVM-DE_SetWPSConfig":"fn","X_AVM-DE_SetWLANGlobalEnable":"fn"}},"urn:dslforum-org:service:WLANConfiguration:3":{"actions":{"SetEnable":"fn","GetInfo":"fn","SetConfig":"fn","SetSecurityKeys":"fn","GetSecurityKeys":"fn","SetDefaultWEPKeyIndex":"fn","GetDefaultWEPKeyIndex":"fn","SetBasBeaconSecurityProperties":"fn","GetBasBeaconSecurityProperties":"fn","GetStatistics":"fn","GetPacketStatistics":"fn","GetBSSID":"fn","GetSSID":"fn","SetSSID":"fn","GetBeaconType":"fn","SetBeaconType":"fn","GetChannelInfo":"fn","SetChannel":"fn","GetBeaconAdvertisement":"fn","SetBeaconAdvertisement":"fn","GetTotalAssociations":"fn","GetGenericAssociatedDeviceInfo":"fn","GetSpecificAssociatedDeviceInfo":"fn","X_AVM-DE_GetSpecificAssociatedDeviceInfoByIp":"fn","X_AVM-DE_GetWLANDeviceListPath":"fn","X_AVM-DE_SetStickSurfEnable":"fn","X_AVM-DE_GetIPTVOptimized":"fn","X_AVM-DE_SetIPTVOptimized":"fn","X_AVM-DE_GetNightControl":"fn","X_AVM-DE_GetWLANHybridMode":"fn","X_AVM-DE_SetWLANHybridMode":"fn","X_AVM-DE_GetWLANExtInfo":"fn","X_AVM-DE_GetWPSInfo":"fn","X_AVM-DE_SetWPSConfig":"fn","X_AVM-DE_SetWLANGlobalEnable":"fn"}},"urn:dslforum-org:service:Hosts:1":{"actions":{"GetHostNumberOfEntries":"fn","GetSpecificHostEntry":"fn","GetGenericHostEntry":"fn","X_AVM-DE_GetChangeCounter":"fn","X_AVM-DE_SetHostNameByMACAddress":"fn","X_AVM-DE_GetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_SetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_WakeOnLANByMACAddress":"fn","X_AVM-DE_GetSpecificHostEntryByIP":"fn","X_AVM-DE_HostsCheckUpdate":"fn","X_AVM-DE_HostDoUpdate":"fn","X_AVM-DE_GetHostListPath":"fn","X_AVM-DE_GetMeshListPath":"fn"}},"urn:dslforum-org:service:LANEthernetInterfaceConfig:1":{"actions":{"SetEnable":"fn","GetInfo":"fn","GetStatistics":"fn"}},"urn:dslforum-org:service:LANHostConfigManagement:1":{"actions":{"GetInfo":"fn","SetDHCPServerEnable":"fn","SetIPInterface":"fn","GetAddressRange":"fn","SetAddressRange":"fn","GetIPRoutersList":"fn","SetIPRouter":"fn","GetSubnetMask":"fn","SetSubnetMask":"fn","GetDNSServers":"fn","GetIPInterfaceNumberOfEntries":"fn"}},"urn:dslforum-org:service:WANCommonInterfaceConfig:1":{"actions":{"GetCommonLinkProperties":"fn","GetTotalBytesSent":"fn","GetTotalBytesReceived":"fn","GetTotalPacketsSent":"fn","GetTotalPacketsReceived":"fn","X_AVM-DE_SetWANAccessType":"fn","X_AVM-DE_GetOnlineMonitor":"fn"}},"urn:dslforum-org:service:WANDSLInterfaceConfig:1":{"actions":{"GetInfo":"fn","GetStatisticsTotal":"fn","X_AVM-DE_GetDSLDiagnoseInfo":"fn","X_AVM-DE_GetDSLInfo":"fn"}},"urn:dslforum-org:service:WANDSLLinkConfig:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","GetAutoConfig":"fn","SetDSLLinkType":"fn","GetDSLLinkInfo":"fn","SetDestinationAddress":"fn","GetDestinationAddress":"fn","SetATMEncapsulation":"fn","GetATMEncapsulation":"fn","GetStatistics":"fn"}},"urn:dslforum-org:service:WANEthernetLinkConfig:1":{"actions":{}},"urn:dslforum-org:service:X_AVM-DE_Dect:1":{"actions":{"GetNumberOfDectEntries":"fn","GetGenericDectEntry":"fn","GetSpecificDectEntry":"fn","DectDoUpdate":"fn","GetDectListPath":"fn"}},"urn:dslforum-org:service:WANPPPConnection:1":{"actions":{"GetInfo":"fn","GetConnectionTypeInfo":"fn","SetConnectionType":"fn","GetStatusInfo":"fn","GetUserName":"fn","SetUserName":"fn","SetPassword":"fn","GetNATRSIPStatus":"fn","SetConnectionTrigger":"fn","ForceTermination":"fn","RequestConnection":"fn","GetGenericPortMappingEntry":"fn","GetSpecificPortMappingEntry":"fn","AddPortMapping":"fn","DeletePortMapping":"fn","GetExternalIPAddress":"fn","X_GetDNSServers":"fn","GetLinkLayerMaxBitRates":"fn","GetPortMappingNumberOfEntries":"fn","SetRouteProtocolRx":"fn","SetIdleDisconnectTime":"fn","X_AVM-DE_GetAutoDisconnectTimeSpan":"fn","X_AVM-DE_SetAutoDisconnectTimeSpan":"fn"}},"urn:dslforum-org:service:WANIPConnection:1":{"actions":{"GetInfo":"fn","GetConnectionTypeInfo":"fn","SetConnectionType":"fn","GetStatusInfo":"fn","GetNATRSIPStatus":"fn","SetConnectionTrigger":"fn","ForceTermination":"fn","RequestConnection":"fn","GetGenericPortMappingEntry":"fn","GetSpecificPortMappingEntry":"fn","AddPortMapping":"fn","DeletePortMapping":"fn","GetExternalIPAddress":"fn","X_GetDNSServers":"fn","GetPortMappingNumberOfEntries":"fn","SetRouteProtocolRx":"fn","SetIdleDisconnectTime":"fn"}}}`

**Comment by Apollon77** [comment]
Generell für Commands: https://github.com/iobroker-community-adapters/ioBroker.tr-064-community#command--commandresult-state

Ok, Hosts unterstützt:
"urn:dslforum-org:service:Hosts:1":{"actions":{"GetHostNumberOfEntries":"fn","GetSpecificHostEntry":"fn","GetGenericHostEntry":"fn","X_AVM-DE_GetChangeCounter":"fn","X_AVM-DE_SetHostNameByMACAddress":"fn","X_AVM-DE_GetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_SetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_WakeOnLANByMACAddress":"fn","X_AVM-DE_GetSpecificHostEntryByIP":"fn","X_AVM-DE_HostsCheckUpdate":"fn","X_AVM-DE_HostDoUpdate":"fn","X_AVM-DE_GetHostListPath":"fn","X_AVM-DE_GetMeshListPath":"fn"}}

also:

ein command mit 

{service: 'urn:dslforum-org:service:Hosts:1', action: 'GetHostNumberOfEntries'}

sollte tun ... oder es muss

{service: 'urn:dslforum-org:service:Hosts:1', action: 'GetHostNumberOfEntries', params: {NewHostNumberOfEntries: ''}}

sein ... ich verstehe den EIngngsparameter für den Call nicht
