### ISSUE TITLE
Rufweiterleitung, => Fehler bei hinzufügen von gesperrten Nummern

### ISSUE THREAD

**Issue by onlyKlausM** [iobroker-community-adapters/ioBroker.tr-064#83]
nach aktivieren von "Rufweiterleitungsoption verwenden" werden entsprechenden Datenpunkte zu allen gesperrten, eingehenden Rufnummern unter "tr-064-community.0.callForwarding" korrekt wie folgt erzeugt.

{
  "type": "state",
  "common": {
    **"name": "fromNumber 02203xxxxxxxxx -> ",**
    "type": "boolean",
    "role": "state"
  },
  "native": {},
  "_id": "tr-064-community.0.callForwarding.0",
  "acl": {
    "object": 1636,
    "state": 1636
  }
}

Werden in der Fritzbox neue Rufsperren definiert, wird im neu erzeugtem Datenpunkt unter .callForwarding anstelle "fromNummer xxxxxxxx -> " der Index der Liste eingetragen, hier 24..
    
{
  "type": "state",
  "common": {
    **"name": "24",**
    "type": "boolean",
    "role": "state"
  },
  "native": {},
  "_id": "tr-064-community.0.callForwarding.24",
  "acl": {
    "object": 1636,
    "state": 1636
  }
}

Hoffe, das verständlich geschrieben zu haben.

**Comment by onlyKlausM** [comment]
Ergänzung: 
Fritzbox: 7490
FRITZ!OS: 07.12
Adapter: 2.0.3
Node.js: v10.17.0

**Comment by FredF63** [comment]
Kann ich nicht bestätigen.
Mit Adapter 2.0.2 und Fritzbox 6490 Cable kann ich Rufnummern sperren ohne das dieser Datenpunkt geändert wird.

**Comment by Apollon77** [comment]
Und wenn Adapter neu gestartet wird? Passt es danach?

**Comment by onlyKlausM** [comment]
leider nein, Adapter restart mit und ohne Änderung der Adapterkonfiguration. Neustart Fritzbox hilft auch nicht.  Nun habe ich in der 7490 ein Telefonbuch mit gesperrten ankommend Nummern eingetragen.  Hatte erhofft, das Datenpunkte mit entsprechenden Nummer aus dem Buch erzeugt werden. Das sieht leider nur wie folgt aus:
`{
  "type": "state",
  "common": {
    **"name": "fromPB  -> ",**
    "type": "boolean",
    "role": "state"
  },
  "native": {},
  "_id": "tr-064-community.0.callForwarding.15",
  "acl": {
    "object": 1636,
    "state": 1636
  }
}`
