### ISSUE TITLE
Call list all json

### ISSUE THREAD

**Issue by Kampfratte** [iobroker-community-adapters/ioBroker.tr-064#88]
Bei der Anruferliste (all - json) wird als erstes immer der Anruf mit der id 9 an erste Stelle geschrieben.
Habe in dieser Liste ca. 400 Anrufe und es sollten nur die letzten 5 drin stehen. Die letzten 4 stehen drin, aber an 2. bis 5. Stelle. Diese werden korrekt angezeigt.

**Comment by Apollon77** [comment]
@maeb3 any idea ?!

**Comment by Kampfratte** [comment]
#Es liegt an der Sortierung. Habe gerade mal ein bisschen herum probiert. Es wird die ID herunter gezählt. 73, 72, 71, 70, 7, 69, 68 u.s.w. auch weiter hinten dann 63, 62, 61, 60, 6, 59, 58. u.s.w

**Comment by maeb3** [comment]
muss an Zeile 208 in calllist.js liegen

`call.sort((a,b) => (a.id > b.id) ? 1 : -1); // was call.reverse(); before`

ich hatte von **call.reverse();** auf **call.sort(...);** gewechselt, weil es anfangs Schwierigkeiten mit der Reihenfolge gab. Habe nicht bedacht, dass sort alphanumerisch sortiert, statt nach Größe.

Wir sollten zurück auf call.reverse(); gehen. ich prüfe nochmal, ob ich den Fehler bei call.reverse nochmal reproduzieren kann und wie man den dann vielleicht anders beseitigen kann.

maeb3

**Comment by Apollon77** [comment]
Perfekt Danke!! Frue mich dann über einen PR wieder. Das klappt so recht gut :-)) Dann fixen wir das ggf noch bevor er in stable repo geht

**Comment by Kampfratte** [comment]
@maeb3 habe das auf meinem iobroker wieder rückgängig gemacht in der calllist.js und damit haut es wieder hin. Die Sortierung stimmt wieder dann.

**Comment by maeb3** [comment]
Wenn ich mich recht erinnere, hatte ich Probleme, wenn der Call mit der höheren Call.id vor einem Call mit der niedrigen call.id beendet wird, was bei parallelen Telefonaten passieren kann.
Ich schaue mir das morgen an.

Bei mir hatte das mit sort immer funktioniert, bin aber auch schon bei 4stelliigen call IDs. Dein Problem kann ja nur auftreten, wenn bei einer Fritzbox-Abfrage call.ids mit unterschiedlicher Anzahl Ziffern enthalten sind (also z.b 1stellig und 2stellig wie bei dir)

**Comment by Kampfratte** [comment]
@maeb3 jupp... da ich mir letztes Jahr ne neue Fritzbox kaufte und die ne ältere Version drauf hatte, wie die alte, konnte ich die Liste nicht mit nehmen und musste neu anfangen. Deswegen habe ich noch nicht so viele Anrufe drauf. Auf der alten war ich auch im 4stelligen Bereich.

**Comment by Kampfratte** [comment]
Übrigens, die ausgehenden Telefonate, wenn ich mir in der Visualisierung die Anrufliste All ausgeben lasse, dann habe ich auch in der Liste bei ausgehenden Anrufen statt der angerufenen Nummer, wie es vorher war, nur SIP: und meine eigene Rufnummer zu stehen.

**Comment by maeb3** [comment]
Habe jetzt einen PR gestellt, um zurück auf "call.reverse();" zu gehen. Habe bei mir diverse Tests durchgeführt und dies sollte das (erste) Problem von Kampfratte beheben. 
Einziger erkennbarer Nachteil aus meiner Sicht: solange noch ein Call über die Fritzbox aktiv ist, werden bei jedem weiteren Abruf von der Fritzbox alle parallelen Calls seit Beginn des ersten aktiven Calls abgerufen (auch, wenn diese schon beendet und in die Liste aufgenommen wurden). 
Falls also nicht gerade ein CallCenter darüber betrieben wird oder jemand Telefonate führt, die Tage dauern, stellt das kein Problem dar. 

Das andere von @Kampfratte beschriebene Problem sollte nicht mit meiner Änderungen zu tun haben. Ich kann dieses Problem bei mir auch nicht reproduzieren. Meine Anrufliste zeigt die korrekte Nummer des Angerufenen (bei outgoing) bzw. des Anrufenden (bei incoming).

maeb3

**Comment by Apollon77** [comment]
Welche Versionen nutzt Uhr? 3.0 odr 3.1?

**Comment by Kampfratte** [comment]
ich die 3.1

**Comment by Apollon77** [comment]
Versuch bitte mal ob die 3.0 anders reagiert

**Comment by Kampfratte** [comment]
die hatte ich heute morgen noch drauf und die reagierte auch nicht anders. Habe die 3.1 erst heute morgen drauf gezogen.

**Comment by maeb3** [comment]
Habe auf meinem produktiven System noch die 2.0.3 mit meinen lokalen Änderungen in der calllist.js auf meinem Testsystem habe ich bereits die 3.1.1 installiert. Greifen aber beide auf die gleiche Fritzbox zu.

**Comment by maeb3** [comment]
Nee, sorry. 3.1.0 auf dem Testsystem. 3.1.1 habe ich noch nicht versucht. Mache ich morgen.

**Comment by Apollon77** [comment]
Bitte 3.1.1. NEU von GitHub ziehen ... da ist der FIx drin und bitte andere nicht funktionierende Dinge retesten

**Comment by Kampfratte** [comment]
Also die Anrufliste All ist bei mir immer noch das selbe. Bei ausgehenden Telefonaten sollten Caller und called umgetauscht werden. Wird es bei mir aber nicht. Warum auch immer.
<img width="665" alt="Bildschirmfoto 2020-01-26 um 09 02 08" src="https://user-images.githubusercontent.com/37498878/73132458-d03a5580-401b-11ea-889b-4af5d75cfab7.png">

**Comment by Kampfratte** [comment]
Stop, Stop, Stop.... war ein Fehler von mir.... ich hatte den Fehler gemacht, und statt external caller und called drin. Also alles gut. Nehme das zurück. Doch kein Fehler.

**Comment by Apollon77** [comment]
;-)

**Comment by maeb3** [comment]
Dieser Issue ist meines Erachtens mittlerweile geschlossen, oder?
maeb3
