### ISSUE TITLE
Guest wifi devices are allways "active"

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064#9]
_From @stundenblume on December 4, 2017 19:3_

Devices in guest wifi allways stated as "active" even if they are turned off or not present.
Status for devices in the normal wifi working well.

_Copied from original issue: soef/ioBroker.tr-064#51_

**Comment by jogibear9988** [comment]
_From @stundenblume on December 4, 2017 20:15_

This is the error massage:

forEachConfiguredDevice: in GetSpecificHostEntry 4(XXXXX-XXXX/11:AA:DD:99:88:99):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"

**Comment by jogibear9988** [comment]
_From @soef on December 10, 2017 17:13_

Are there entries in the errorlog? Could you send them? Did you try to restart your Fritz.box?

**Comment by Apollon77** [comment]
@stundenblume please check with 2.0 from github. still problematic? Please send debug log from such device deactivations and also check that they are rella yoffline shown in FB!
