### ISSUE TITLE
No device activ state change with 3.1.1

### ISSUE THREAD

**Issue by FredF63** [iobroker-community-adapters/ioBroker.tr-064#90]
After installation of 3.1.1 no change of device activ state. No state tr-064-community.0.devices.jsonDeviceList exist.
After changing to 3.0.1 it works. And state tr-064-community.0.devices.jsonDeviceList is there

**Comment by Hildesen** [comment]
Same issue here, First deleded all tr-064 adapter, then new installation with 3.1.1 and got no "green light", changend to 3.0.1 and all works fine...

**Comment by Apollon77** [comment]
Please get 3.1.1 new from GitHub (if installed before 20:36!) and retest please

**Comment by Feuer-sturm** [comment]
I just updated from 3.0.1 to 3.1.1. I have two devices in my list and both devices show the correct status in state tr-064.0.devices.xxx.active

The state "tr-064-community.0.devices.jsonDeviceList" I did not have in version 3.0.1 and 3.1.1. Must this state be available?

**Comment by Hildesen** [comment]
updated again from 3.0.1 to 3.1.1. I have devices in my list and now they show the correct status and object-states are right and changeable, thanks ☺

**Comment by Apollon77** [comment]
I will check for the json state later

**Comment by Apollon77** [comment]
Hast DU in der Konfig auch aktiviert das eine json device liste erzeugt werden soll?

**Comment by FredF63** [comment]
Na klar.
Zwischendrin ging es auch, nun mit der 3.1.3 wieder keine...

**Comment by Apollon77** [comment]
kann an sich nicht sein! ggf werden objekte auch verzögert erst dann angelegt wenn sie passieren.
