### ISSUE TITLE
Anrufweiterleitungsoptionene bringen den Adapter zum Neustarten

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.tr-064#92]
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at Parser.emit (events.js:198:13)
-- | -- | -- | --
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:306:18)
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.tr-064/main.js:82:28
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at tr064Client.init.err (/opt/iobroker/node_modules/iobroker.tr-064/main.js:1144:27)
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at new Deflections (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:21:10)
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at Deflections.init (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:156:17)
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at getFunctions (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:149:12)
host.Beelink | 2020-01-26 08:03:38.587 | error | Caught by controller[0]:     at Array.forEach (<anonymous>)
host.Beelink | 2020-01-26 08:03:38.586 | error | Caught by controller[0]:     at ar.forEach.fn (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:149:37)
host.Beelink | 2020-01-26 08:03:38.586 | error | Caught by controller[0]: ReferenceError: fndest is not defined
tr-064.0 | 2020-01-26 08:03:38.041 | info | (26532) Terminated (NO_ERROR): Without reason
tr-064.0 | 2020-01-26 08:03:38.036 | info | (26532) terminating
tr-064.0 | 2020-01-26 08:03:37.528 | error | at Parser.emit (events.js:198:13)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:306:18)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17
tr-064.0 | 2020-01-26 08:03:37.528 | error | at /opt/iobroker/node_modules/iobroker.tr-064/main.js:82:28
tr-064.0 | 2020-01-26 08:03:37.528 | error | at tr064Client.init.err (/opt/iobroker/node_modules/iobroker.tr-064/main.js:1144:27)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at new Deflections (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:21:10)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at Deflections.init (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:156:17)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at getFunctions (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:149:12)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at Array.forEach (<anonymous>)
tr-064.0 | 2020-01-26 08:03:37.528 | error | at ar.forEach.fn (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:149:37)
tr-064.0 | 2020-01-26 08:03:37.528 | error | (26532) ReferenceError: fndest is not defined
tr-064.0 | 2020-01-26 08:03:37.527 | error | (26532) uncaught exception: fndest is not defined

**Comment by Apollon77** [comment]
should be fixed in 3.1.2
