### ISSUE TITLE
Active state change more freqently since update

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.tr-064#93]
Since updating to 3.1.0 the active state of my phones report a change much more often.
Keep getting push notifications .. which wasn't the case earlier.

Host update to 2.2.8 was done close to that time .. not sure which is the problem.

**Comment by Apollon77** [comment]
Please check 3.1.1 but when it changes there is a reason and fritzbox triggers it. Please check back in forum for other user solutions.

**Comment by daniel-lo** [comment]
Renewed device objects and updated to 3.1.1 .. (and ran installation fixer). Looks better at the moment.
Thanks!
