### ISSUE TITLE
Anrufbeantworter zählt nicht

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.tr-064#98]
Hallo,
Der AB zählt die Anzahl der Sprachnachrichten nicht unter den DP:
tr-064.0.states.abIndex

Log am 28.01.2020 per Mail gesendet.

**Comment by sigi2345** [comment]
Fehler besteht noch immer.

Version 4.0.4

**Comment by Feuer-sturm** [comment]
Laut diesem Posting https://forum.iobroker.net/topic/14288/tr-064-fritzbox-anrufbeantworter/14 wird der Datenpunkt wohl für folgendes verwendet: 
`
Wenn man mehrere Anrufbeantworter in der FritzBox eingerichtet hat, kann man z.B. den zweiten schalten indem man im TR-064 den Datenpunkt abIndex vorher auf 1 setzt. (0=AB1, 1=AB2)`

Ich bin auch auf der Suche nach einem Datenpunkt, in welchem man sieht wieviele Nachrichten auf dem Anrufbeantworter sind. Bin bisher aber nicht fündig geworden.
