### ISSUE TITLE
Exception when callmonitor in FB is not enabled

### ISSUE THREAD

**Issue by JojoS62** [iobroker-community-adapters/ioBroker.tr-064#99]
**Describe the bug**  
Adapter terminates with exception when callmonitor is not enabled in FritzBox. An error message is shown as in previous versions, but the exception is not caught the adapter terminates.

**To Reproduce**  
1. disable callmonitor in fb
2. start tr-064 adapter
3. See error in logfile

**Expected behavior**  
show error and continue adapter function

**Screenshots & Logfiles**  

 
```
tr-064.2 | 2020-02-01 22:21:17.078 | info | (3516) terminating
tr-064.2 | 2020-02-01 22:21:17.077 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
tr-064.2 | 2020-02-01 22:21:17.077 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
tr-064.2 | 2020-02-01 22:21:17.077 | error | at emitErrorNT (internal/streams/destroy.js:91:8)
tr-064.2 | 2020-02-01 22:21:17.077 | error | at Socket.emit (events.js:203:15)
tr-064.2 | 2020-02-01 22:21:17.077 | error | at Socket.client.on.err (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.tr-064\lib\callmonitor.js:65:22)
tr-064.2 | 2020-02-01 22:21:17.077 | error | (3516) TypeError: Cannot read property 'close' of undefined
tr-064.2 | 2020-02-01 22:21:17.076 | error | (3516) uncaught exception: Cannot read property 'close' of undefined
tr-064.2 | 2020-02-01 22:21:17.075 | error | (3516) --- To use the callmonitor, enable connects to port 1012 on  FritzBox by dialing #96*5* with a directly connected phone (line/dect)  and restart this adapter
```

**Versions:**  
 - Adapter version: 3.1.4
 - JS-Controller version: 2.1.1
 - Node version: v10.16.0 
 - Operating system: Windows7-x64

**Comment by Diginix** [comment]
I had the same problem with v3.x and saw the log entry with the hint for the #96*5* only by accident.
JS-Controller 2.2.8
nodejs 10.18.1
Ubuntu 19.10

**Comment by Apollon77** [comment]
Will be fixed in next version

**Comment by AlCalzone** [comment]
What is the next version? A user did totally not see the message in 3.1.4:
https://forum.iobroker.net/post/388912
